\c pokedabe
DELETE FROM Attacks;

INSERT INTO Attacks VALUES('Absorb',25,100,20,'User recovers half the HP inflicted on opponent.','GRASS');
INSERT INTO Attacks VALUES('Accelerock',20,100,40,'User attacks first.','ROCK');
INSERT INTO Attacks VALUES('Acid',30,100,40,'May lower opponents Special Defense.','POISON');
INSERT INTO Attacks VALUES('Acid Armor',20,null,null,'Sharply raises user s Defense.','POISON');
INSERT INTO Attacks VALUES('Acid Downpour',1,null,null,'Poison type Z-Move.','POISON');
INSERT INTO Attacks VALUES('Acid Spray',20,100,40,'Sharply lowers opponent s Special Defense.','POISON');
INSERT INTO Attacks VALUES('Acrobatics',15,100,55,'Stronger when the user does not have a held item.','FLYING');
INSERT INTO Attacks VALUES('Acupressure',30,null,null,'Sharply raises a random stat.','NORMAL');
INSERT INTO Attacks VALUES('Aerial Ace',20,110,60,'Ignores Accuracy and Evasiveness.','FLYING');
INSERT INTO Attacks VALUES('Aeroblast',5,95,100,'High critical hit ratio.','FLYING');
INSERT INTO Attacks VALUES('After You',15,null,null,'Gives target priority in the next turn.','NORMAL');
INSERT INTO Attacks VALUES('Agility',30,null,null,'Sharply raises user s Speed.','PSYCHIC');
INSERT INTO Attacks VALUES('Air Cutter',25,95,60,'High critical hit ratio.','FLYING');
INSERT INTO Attacks VALUES('Air Slash',20,95,75,'May cause flinching.','FLYING');
INSERT INTO Attacks VALUES('All-Out Pummeling',1,null,null,'Fighting type Z-Move.','FIGHTING');
INSERT INTO Attacks VALUES('Ally Switch',15,null,null,'User switches with opposite teammate.','PSYCHIC');
INSERT INTO Attacks VALUES('Amnesia',20,null,null,'Sharply raises user s Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Anchor Shot',20,100,80,'The user entangles the target with its anchor chain while attacking. The target becomes unable to flee.','STEEL');
INSERT INTO Attacks VALUES('Ancient Power',5,100,60,'May raise all user s stats at once.','ROCK');
INSERT INTO Attacks VALUES('Aqua Jet',20,100,40,'User attacks first.','WATER');
INSERT INTO Attacks VALUES('Aqua Ring',20,null,null,'Restores a little HP each turn.','WATER');
INSERT INTO Attacks VALUES('Aqua Tail',10,90,90,'null','WATER');
INSERT INTO Attacks VALUES('Arm Thrust',20,100,15,'Hits 2-5 times in one turn.','FIGHTING');
INSERT INTO Attacks VALUES('Aromatherapy',5,null,null,'Cures all status problems in your party.','GRASS');
INSERT INTO Attacks VALUES('Aromatic Mist',20,null,null,'Raises Special Defense of allies.','FAIRY');
INSERT INTO Attacks VALUES('Assist',20,null,null,'User performs a move known by its allies at random.','NORMAL');
INSERT INTO Attacks VALUES('Assurance',10,100,60,'Power doubles if opponent already took damage in the same turn.','DARK');
INSERT INTO Attacks VALUES('Astonish',15,100,30,'May cause flinching.','GHOST');
INSERT INTO Attacks VALUES('Attack Order',15,100,90,'High critical hit ratio.','BUG');
INSERT INTO Attacks VALUES('Attract',15,100,null,'If opponent is the opposite gender, it s less likely to attack.','NORMAL');
INSERT INTO Attacks VALUES('Aura Sphere',20,110,80,'Ignores Accuracy and Evasiveness.','FIGHTING');
INSERT INTO Attacks VALUES('Aurora Beam',20,100,65,'May lower opponent s Attack.','ICE');
INSERT INTO Attacks VALUES('Aurora Veil',20,null,null,'Halves damage from Physical and Special attacks for five turns.','ICE');
INSERT INTO Attacks VALUES('Autotomize',15,null,null,'Reduces weight and sharply raises Speed.','STEEL');
INSERT INTO Attacks VALUES('Avalanche',10,100,60,'Power doubles if user took damage first.','ICE');
INSERT INTO Attacks VALUES('Baby-Doll Eyes',30,100,null,'Always goes first. Lowers the target s attack.','FAIRY');
INSERT INTO Attacks VALUES('Baddy Bad',15,100,90,'Reduces damage from Physical attacks.','DARK');
INSERT INTO Attacks VALUES('Baneful Bunker',10,null,null,'Protects the user and poisons opponent on contact.','POISON');
INSERT INTO Attacks VALUES('Barrage',20,85,15,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Barrier',20,null,null,'Sharply raises user s Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Baton Pass',40,null,null,'User switches out and gives stat changes to the incoming Pokémon.','NORMAL');
INSERT INTO Attacks VALUES('Beak Blast',15,100,100,'The user first heats up its beak, and then it attacks the target. Making direct contact with the Pokémon while it s heating up its beak results in a burn.','FLYING');
INSERT INTO Attacks VALUES('Beat Up',30,100,null,'Each Pokémon in your party attacks.','DARK');
INSERT INTO Attacks VALUES('Belch',10,90,120,'User must have consumed a Berry.','POISON');
INSERT INTO Attacks VALUES('Belly Drum',10,null,null,'User loses 50% of its max HP, but Attack raises to maximum.','NORMAL');
INSERT INTO Attacks VALUES('Bestow',15,null,null,'Gives the user s held item to the target.','NORMAL');
INSERT INTO Attacks VALUES('Bide',10,null,null,'User takes damage for two turns then strikes back double.','NORMAL');
INSERT INTO Attacks VALUES('Bind',20,85,15,'Traps opponent, damaging them for 4-5 turns.','NORMAL');
INSERT INTO Attacks VALUES('Bite',25,100,60,'May cause flinching.','DARK');
INSERT INTO Attacks VALUES('Black Hole Eclipse',1,null,null,'Dark type Z-Move.','DARK');
INSERT INTO Attacks VALUES('Blast Burn',5,90,150,'User must recharge next turn.','FIRE');
INSERT INTO Attacks VALUES('Blaze Kick',10,90,85,'High critical hit ratio. May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Blizzard',5,70,110,'May freeze opponent.','ICE');
INSERT INTO Attacks VALUES('Block',5,null,null,'Opponent cannot flee or switch.','NORMAL');
INSERT INTO Attacks VALUES('Bloom Doom',1,null,null,'Grass type Z-Move.','GRASS');
INSERT INTO Attacks VALUES('Blue Flare',5,85,130,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Body Slam',15,100,85,'May paralyze opponent.','NORMAL');
INSERT INTO Attacks VALUES('Bolt Strike',5,85,130,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Bone Club',20,85,65,'May cause flinching.','GROUND');
INSERT INTO Attacks VALUES('Bone Rush',10,90,25,'Hits 2-5 times in one turn.','GROUND');
INSERT INTO Attacks VALUES('Bonemerang',10,90,50,'Hits twice in one turn.','GROUND');
INSERT INTO Attacks VALUES('Boomburst',10,100,140,'Hits all adjacent Pokémon.','NORMAL');
INSERT INTO Attacks VALUES('Bounce',5,85,85,'Springs up on first turn, attacks on second. May paralyze opponent.','FLYING');
INSERT INTO Attacks VALUES('Bouncy Bubble',15,100,90,'User recovers half the HP inflicted on opponent.','WATER');
INSERT INTO Attacks VALUES('Brave Bird',15,100,120,'User receives recoil damage.','FLYING');
INSERT INTO Attacks VALUES('Breakneck Blitz',1,null,null,'Normal type Z-Move.','NORMAL');
INSERT INTO Attacks VALUES('Brick Break',15,100,75,'Breaks through Reflect and Light Screen barriers.','FIGHTING');
INSERT INTO Attacks VALUES('Brine',10,100,65,'Power doubles if opponent s HP is less than 50%.','WATER');
INSERT INTO Attacks VALUES('Brutal Swing',20,100,60,'The user swings its body around violently to inflict damage on everything in its vicinity.','DARK');
INSERT INTO Attacks VALUES('Bubble',30,100,40,'May lower opponent s Speed.','WATER');
INSERT INTO Attacks VALUES('Bubble Beam',20,100,65,'May lower opponent s Speed.','WATER');
INSERT INTO Attacks VALUES('Bug Bite',20,100,60,'Receives the effect from the opponent s held berry.','BUG');
INSERT INTO Attacks VALUES('Bug Buzz',10,100,90,'May lower opponent s Special Defense.','BUG');
INSERT INTO Attacks VALUES('Bulk Up',20,null,null,'Raises user s Attack and Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Bulldoze',20,100,60,'Lowers opponent s Speed.','GROUND');
INSERT INTO Attacks VALUES('Bullet Punch',30,100,40,'User attacks first.','STEEL');
INSERT INTO Attacks VALUES('Bullet Seed',30,100,25,'Hits 2-5 times in one turn.','GRASS');
INSERT INTO Attacks VALUES('Burn Up',5,100,130,'To inflict massive damage, the user burns itself out. After using this move, the user will no longer be Fire type.','FIRE');
INSERT INTO Attacks VALUES('Buzzy Buzz',15,100,90,'Paralyzes the opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Calm Mind',20,null,null,'Raises user s Special Attack and Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Camouflage',20,null,null,'Changes user s type according to the location.','NORMAL');
INSERT INTO Attacks VALUES('Captivate',20,100,null,'Sharply lowers opponent s Special Attack if opposite gender.','NORMAL');
INSERT INTO Attacks VALUES('Catastropika',1,null,210,'Pikachu-exclusive Z-Move.','ELECTRIC');
INSERT INTO Attacks VALUES('Celebrate',40,null,null,'The Pokémon congratulates you on your special day. No battle effect.','NORMAL');
INSERT INTO Attacks VALUES('Charge',20,null,null,'Raises user s Special Defense and next Electric move s power increases.','ELECTRIC');
INSERT INTO Attacks VALUES('Charge Beam',10,90,50,'May raise user s Special Attack.','ELECTRIC');
INSERT INTO Attacks VALUES('Charm',20,100,null,'Sharply lowers opponent s Attack.','FAIRY');
INSERT INTO Attacks VALUES('Chatter',20,100,65,'Confuses opponent.','FLYING');
INSERT INTO Attacks VALUES('Chip Away',20,100,70,'Ignores opponent s stat changes.','NORMAL');
INSERT INTO Attacks VALUES('Circle Throw',10,90,60,'In battles, the opponent switches. In the wild, the Pokémon runs.','FIGHTING');
INSERT INTO Attacks VALUES('Clamp',10,85,35,'Traps opponent, damaging them for 4-5 turns.','WATER');
INSERT INTO Attacks VALUES('Clanging Scales',5,100,110,'Lowers user s Defense.','DRAGON');
INSERT INTO Attacks VALUES('Clangorous Soulblaze',1,null,185,'Kommo-o exclusive Z-Move.','DRAGON');
INSERT INTO Attacks VALUES('Clear Smog',15,null,50,'Removes all of the target s stat changes.','POISON');
INSERT INTO Attacks VALUES('Close Combat',5,100,120,'Lowers user s Defense and Special Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Coil',20,null,null,'Raises user s Attack, Defense and Accuracy.','POISON');
INSERT INTO Attacks VALUES('Comet Punch',15,85,18,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Confide',20,null,null,'Lowers opponent s Special Attack.','NORMAL');
INSERT INTO Attacks VALUES('Confuse Ray',10,100,null,'Confuses opponent.','GHOST');
INSERT INTO Attacks VALUES('Confusion',25,100,50,'May confuse opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Constrict',35,100,10,'May lower opponent s Speed by one stage.','NORMAL');
INSERT INTO Attacks VALUES('Continental Crush',1,null,null,'Rock type Z-Move.','ROCK');
INSERT INTO Attacks VALUES('Conversion',30,null,null,'Changes user s type to that of its first move.','NORMAL');
INSERT INTO Attacks VALUES('Conversion 2',30,null,null,'User changes type to become resistant to opponent s last move.','NORMAL');
INSERT INTO Attacks VALUES('Copycat',20,null,null,'Copies opponent s last move.','NORMAL');
INSERT INTO Attacks VALUES('Core Enforcer',10,100,100,'Scorches a Z pattern on the ground.','DRAGON');
INSERT INTO Attacks VALUES('Corkscrew Crash',1,null,null,'Steel type Z-Move.','STEEL');
INSERT INTO Attacks VALUES('Cosmic Power',20,null,null,'Raises user s Defense and Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Cotton Guard',10,null,null,'Drastically raises user s Defense.','GRASS');
INSERT INTO Attacks VALUES('Cotton Spore',40,100,null,'Sharply lowers opponent s Speed.','GRASS');
INSERT INTO Attacks VALUES('Counter',20,100,null,'When hit by a Physical Attack, user strikes back with 2x power.','FIGHTING');
INSERT INTO Attacks VALUES('Covet',25,100,60,'opponent s item is stolen by the user.','NORMAL');
INSERT INTO Attacks VALUES('Crabhammer',10,90,100,'High critical hit ratio.','WATER');
INSERT INTO Attacks VALUES('Crafty Shield',10,null,null,'Protects the Pokémon from status moves.','FAIRY');
INSERT INTO Attacks VALUES('Cross Chop',5,80,100,'High critical hit ratio.','FIGHTING');
INSERT INTO Attacks VALUES('Cross Poison',20,100,70,'High critical hit ratio. May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Crunch',15,100,80,'May lower opponent s Defense.','DARK');
INSERT INTO Attacks VALUES('Crush Claw',10,95,75,'May lower opponent s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Crush Grip',5,100,null,'More powerful when opponent has higher HP.','NORMAL');
INSERT INTO Attacks VALUES('Curse',10,null,null,'Ghosts lose 50% of max HP and curse the opponent; Non-Ghosts raise Attack, Defense and lower Speed.','GHOST');
INSERT INTO Attacks VALUES('Cut',30,95,50,'null','NORMAL');
INSERT INTO Attacks VALUES('Dark Pulse',15,100,80,'May cause flinching.','DARK');
INSERT INTO Attacks VALUES('Dark Void',10,50,null,'Puts all adjacent opponents to sleep.','DARK');
INSERT INTO Attacks VALUES('Darkest Lariat',10,100,85,'Ignores opponent s stat changes.','DARK');
INSERT INTO Attacks VALUES('Dazzling Gleam',10,100,80,'Hits all adjacent opponents.','FAIRY');
INSERT INTO Attacks VALUES('Defend Order',10,null,null,'Raises user s Defense and Special Defense.','BUG');
INSERT INTO Attacks VALUES('Defense Curl',40,null,null,'Raises user s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Defog',15,null,null,'Lowers opponent s Evasiveness and clears fog.','FLYING');
INSERT INTO Attacks VALUES('Destiny Bond',5,null,null,'If the user faints, the opponent also faints.','GHOST');
INSERT INTO Attacks VALUES('Detect',5,null,null,'Protects the user, but may fail if used consecutively.','FIGHTING');
INSERT INTO Attacks VALUES('Devastating Drake',1,null,null,'Dragon type Z-Move.','DRAGON');
INSERT INTO Attacks VALUES('Diamond Storm',5,95,100,'May raise user s Defense','ROCK');
INSERT INTO Attacks VALUES('Dig',10,100,80,'Digs underground on first turn, attacks on second. Can also escape from caves.','GROUND');
INSERT INTO Attacks VALUES('Disable',20,100,null,'Opponent can t use its last attack for a few turns.','NORMAL');
INSERT INTO Attacks VALUES('Disarming Voice',15,110,40,'Ignores Accuracy and Evasiveness.','FAIRY');
INSERT INTO Attacks VALUES('Discharge',15,100,80,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Dive',10,100,80,'Dives underwater on first turn, attacks on second turn.','WATER');
INSERT INTO Attacks VALUES('Dizzy Punch',10,100,70,'May confuse opponent.','NORMAL');
INSERT INTO Attacks VALUES('Doom Desire',5,100,140,'Damage occurs 2 turns later.','STEEL');
INSERT INTO Attacks VALUES('Double Hit',10,90,35,'Hits twice in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Double Iron Bash',5,100,60,'Hits twice in one turn; may cause flinching.','STEEL');
INSERT INTO Attacks VALUES('Double Kick',30,100,30,'Hits twice in one turn.','FIGHTING');
INSERT INTO Attacks VALUES('Double Slap',10,85,15,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Double Team',15,null,null,'Raises user s Evasiveness.','NORMAL');
INSERT INTO Attacks VALUES('Double-Edge',15,100,120,'User receives recoil damage.','NORMAL');
INSERT INTO Attacks VALUES('Draco Meteor',5,90,130,'Sharply lowers user s Special Attack.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Ascent',5,100,120,'Lowers user s Defense and Special Defense.','FLYING');
INSERT INTO Attacks VALUES('Dragon Breath',20,100,60,'May paralyze opponent.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Claw',15,100,80,'null','DRAGON');
INSERT INTO Attacks VALUES('Dragon Dance',20,null,null,'Raises user s Attack and Speed.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Hammer',15,100,90,'The user uses its body like a hammer to attack the target and inflict damage.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Pulse',10,100,85,'null','DRAGON');
INSERT INTO Attacks VALUES('Dragon Rage',10,100,null,'Always inflicts 40 HP.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Rush',10,75,100,'May cause flinching.','DRAGON');
INSERT INTO Attacks VALUES('Dragon Tail',10,90,60,'In battles, the opponent switches. In the wild, the Pokémon runs.','DRAGON');
INSERT INTO Attacks VALUES('Drain Punch',10,100,75,'User recovers half the HP inflicted on opponent.','FIGHTING');
INSERT INTO Attacks VALUES('Draining Kiss',10,100,50,'User recovers most the HP inflicted on opponent.','FAIRY');
INSERT INTO Attacks VALUES('Dream Eater',15,100,100,'User recovers half the HP inflicted on a sleeping opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Drill Peck',20,100,80,'null','FLYING');
INSERT INTO Attacks VALUES('Drill Run',10,95,80,'High critical hit ratio.','GROUND');
INSERT INTO Attacks VALUES('Dual Chop',15,90,40,'Hits twice in one turn.','DRAGON');
INSERT INTO Attacks VALUES('Dynamic Punch',5,50,100,'Confuses opponent.','FIGHTING');
INSERT INTO Attacks VALUES('Earth Power',10,100,90,'May lower opponent s Special Defense.','GROUND');
INSERT INTO Attacks VALUES('Earthquake',10,100,100,'Power is doubled if opponent is underground from using Dig.','GROUND');
INSERT INTO Attacks VALUES('Echoed Voice',15,100,40,'Power increases each turn.','NORMAL');
INSERT INTO Attacks VALUES('Eerie Impulse',15,100,null,'Sharply lowers opponent s Special Attack.','ELECTRIC');
INSERT INTO Attacks VALUES('Egg Bomb',10,75,100,'null','NORMAL');
INSERT INTO Attacks VALUES('Electric Terrain',10,null,null,'Prevents all Pokémon from falling asleep for 5 turns.','ELECTRIC');
INSERT INTO Attacks VALUES('Electrify',20,null,null,'Changes the target s move to Electric type.','ELECTRIC');
INSERT INTO Attacks VALUES('Electro Ball',10,100,null,'The faster the user, the stronger the attack.','ELECTRIC');
INSERT INTO Attacks VALUES('Electroweb',15,95,55,'Lowers opponent s Speed.','ELECTRIC');
INSERT INTO Attacks VALUES('Embargo',15,100,null,'Opponent cannot use items.','DARK');
INSERT INTO Attacks VALUES('Ember',25,100,40,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Encore',5,100,null,'Forces opponent to keep using its last move for 3 turns.','NORMAL');
INSERT INTO Attacks VALUES('Endeavor',5,100,null,'Reduces opponent s HP to same as user s.','NORMAL');
INSERT INTO Attacks VALUES('Endure',10,null,null,'Always left with at least 1 HP, but may fail if used consecutively.','NORMAL');
INSERT INTO Attacks VALUES('Energy Ball',10,100,90,'May lower opponent s Special Defense.','GRASS');
INSERT INTO Attacks VALUES('Entrainment',15,100,null,'Makes target s ability same as user s.','NORMAL');
INSERT INTO Attacks VALUES('Eruption',5,100,150,'Stronger when the user s HP is higher.','FIRE');
INSERT INTO Attacks VALUES('Explosion',5,100,250,'User faints.','NORMAL');
INSERT INTO Attacks VALUES('Extrasensory',20,100,80,'May cause flinching.','PSYCHIC');
INSERT INTO Attacks VALUES('Extreme Evoboost',1,null,null,'Eevee-exclusive Z-Move. Sharply raises all stats.','NORMAL');
INSERT INTO Attacks VALUES('Extreme Speed',5,100,80,'User attacks first.','NORMAL');
INSERT INTO Attacks VALUES('Facade',20,100,70,'Power doubles if user is burned, poisoned, or paralyzed.','NORMAL');
INSERT INTO Attacks VALUES('Fairy Lock',10,null,null,'Prevents fleeing in the next turn.','FAIRY');
INSERT INTO Attacks VALUES('Fairy Wind',30,100,40,'null','FAIRY');
INSERT INTO Attacks VALUES('Fake Out',10,100,40,'User attacks first, foe flinches. Only usable on first turn.','NORMAL');
INSERT INTO Attacks VALUES('Fake Tears',20,100,null,'Sharply lowers opponent s Special Defense.','DARK');
INSERT INTO Attacks VALUES('False Swipe',40,100,40,'Always leaves opponent with at least 1 HP.','NORMAL');
INSERT INTO Attacks VALUES('Feather Dance',15,100,null,'Sharply lowers opponent s Attack.','FLYING');
INSERT INTO Attacks VALUES('Feint',10,100,30,'Only hits if opponent uses Protect or Detect in the same turn.','NORMAL');
INSERT INTO Attacks VALUES('Feint Attack',20,110,60,'Ignores Accuracy and Evasiveness.','DARK');
INSERT INTO Attacks VALUES('Fell Stinger',25,100,50,'Drastically raises user s Attack if target is KO d.','BUG');
INSERT INTO Attacks VALUES('Fiery Dance',10,100,80,'May raise user s Special Attack.','FIRE');
INSERT INTO Attacks VALUES('Final Gambit',5,100,null,'Inflicts damage equal to the user s remaining HP. User faints.','FIGHTING');
INSERT INTO Attacks VALUES('Fire Blast',5,85,110,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Fire Fang',15,95,65,'May cause flinching and/or burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Fire Lash',15,100,80,'The user strikes the target with a burning lash. This also lowers the target s Defense stat.','FIRE');
INSERT INTO Attacks VALUES('Fire Pledge',10,100,80,'Added effects appear if combined with Grass Pledge or Water Pledge.','FIRE');
INSERT INTO Attacks VALUES('Fire Punch',15,100,75,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Fire Spin',15,85,35,'Traps opponent, damaging them for 4-5 turns.','FIRE');
INSERT INTO Attacks VALUES('First Impression',10,100,90,'Although this move has great power, it only works the first turn the user is in battle.','BUG');
INSERT INTO Attacks VALUES('Fissure',5,null,null,'One-Hit-KO, if it hits.','GROUND');
INSERT INTO Attacks VALUES('Flail',15,100,null,'The lower the user s HP, the higher the power.','NORMAL');
INSERT INTO Attacks VALUES('Flame Burst',15,100,70,'May also injure nearby Pokémon.','FIRE');
INSERT INTO Attacks VALUES('Flame Charge',20,100,50,'Raises user s Speed.','FIRE');
INSERT INTO Attacks VALUES('Flame Wheel',25,100,60,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Flamethrower',15,100,90,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Flare Blitz',15,100,120,'User receives recoil damage. May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Flash',20,100,null,'Lowers opponent s Accuracy.','NORMAL');
INSERT INTO Attacks VALUES('Flash Cannon',10,100,80,'May lower opponent s Special Defense.','STEEL');
INSERT INTO Attacks VALUES('Flatter',15,100,null,'Confuses opponent, but raises its Special Attack by two stages.','DARK');
INSERT INTO Attacks VALUES('Fleur Cannon',5,90,130,'Sharply lowers user s Special Attack.','FAIRY');
INSERT INTO Attacks VALUES('Fling',10,100,null,'Power depends on held item.','DARK');
INSERT INTO Attacks VALUES('Floaty Fall',15,95,90,'May cause flinching.','FLYING');
INSERT INTO Attacks VALUES('Floral Healing',10,null,null,'The user restores the target s HP by up to half of its max HP. It restores more HP when the terrain is grass.','FAIRY');
INSERT INTO Attacks VALUES('Flower Shield',10,null,null,'Sharply raises Defense of all Grass-type Pokémon on the field.','FAIRY');
INSERT INTO Attacks VALUES('Fly',15,95,90,'Flies up on first turn, attacks on second turn.','FLYING');
INSERT INTO Attacks VALUES('Flying Press',10,95,100,'Deals Fighting and Flying type damage.','FIGHTING');
INSERT INTO Attacks VALUES('Focus Blast',5,70,120,'May lower opponent s Special Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Focus Energy',30,null,null,'Increases critical hit ratio.','NORMAL');
INSERT INTO Attacks VALUES('Focus Punch',20,100,150,'If the user is hit before attacking, it flinches instead.','FIGHTING');
INSERT INTO Attacks VALUES('Follow Me',20,null,null,'In Double Battle, the user takes all the attacks.','NORMAL');
INSERT INTO Attacks VALUES('Force Palm',10,100,60,'May paralyze opponent.','FIGHTING');
INSERT INTO Attacks VALUES('Foresight',40,null,null,'Resets opponent s Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.','NORMAL');
INSERT INTO Attacks VALUES('Forest s Curse',20,100,null,'Adds Grass type to opponent.','GRASS');
INSERT INTO Attacks VALUES('Foul Play',15,100,95,'Uses the opponent s Attack stat.','DARK');
INSERT INTO Attacks VALUES('Freeze Shock',5,90,140,'Charges on first turn, attacks on second. May paralyze opponent.','ICE');
INSERT INTO Attacks VALUES('Freeze-Dry',20,100,70,'May freeze opponent. Super-effective against Water types.','ICE');
INSERT INTO Attacks VALUES('Freezy Frost',15,100,90,'Resets all stat changes.','ICE');
INSERT INTO Attacks VALUES('Frenzy Plant',5,90,150,'User must recharge next turn.','GRASS');
INSERT INTO Attacks VALUES('Frost Breath',10,90,60,'Always results in a critical hit.','ICE');
INSERT INTO Attacks VALUES('Frustration',20,100,null,'Power decreases with higher Friendship.','NORMAL');
INSERT INTO Attacks VALUES('Fury Attack',20,85,15,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Fury Cutter',20,95,40,'Power increases each turn.','BUG');
INSERT INTO Attacks VALUES('Fury Swipes',15,80,18,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Fusion Bolt',5,100,100,'Power increases if Fusion Flare is used in the same turn.','ELECTRIC');
INSERT INTO Attacks VALUES('Fusion Flare',5,100,100,'Power increases if Fusion Bolt is used in the same turn.','FIRE');
INSERT INTO Attacks VALUES('Future Sight',10,100,120,'Damage occurs 2 turns later.','PSYCHIC');
INSERT INTO Attacks VALUES('Gastro Acid',10,100,null,'Cancels out the effect of the opponent s Ability.','POISON');
INSERT INTO Attacks VALUES('Gear Grind',15,85,50,'Hits twice in one turn.','STEEL');
INSERT INTO Attacks VALUES('Gear Up',20,null,null,'The user engages its gears to raise the Attack and Sp. Atk stats of ally Pokémon with the Plus or Minus Ability.','STEEL');
INSERT INTO Attacks VALUES('Genesis Supernova',1,null,185,'Mew-exclusive Z-Move.','PSYCHIC');
INSERT INTO Attacks VALUES('Geomancy',10,null,null,'Charges on first turn, sharply raises user s Sp. Attack, Sp. Defense and Speed on the second.','FAIRY');
INSERT INTO Attacks VALUES('Giga Drain',10,100,75,'User recovers half the HP inflicted on opponent.','GRASS');
INSERT INTO Attacks VALUES('Giga Impact',5,90,150,'User must recharge next turn.','NORMAL');
INSERT INTO Attacks VALUES('Gigavolt Havoc',1,null,null,'Electric type Z-Move.','ELECTRIC');
INSERT INTO Attacks VALUES('Glaciate',10,95,65,'Lowers opponent s Speed.','ICE');
INSERT INTO Attacks VALUES('Glare',30,100,null,'Paralyzes opponent.','NORMAL');
INSERT INTO Attacks VALUES('Glitzy Glow',15,100,90,'Reduces damage from Special attacks.','PSYCHIC');
INSERT INTO Attacks VALUES('Grass Knot',20,100,null,'The heavier the opponent, the stronger the attack.','GRASS');
INSERT INTO Attacks VALUES('Grass Pledge',10,100,80,'Added effects appear if preceded by Water Pledge or succeeded by Fire Pledge.','GRASS');
INSERT INTO Attacks VALUES('Grass Whistle',15,55,null,'Puts opponent to sleep.','GRASS');
INSERT INTO Attacks VALUES('Grassy Terrain',10,null,null,'Restores a little HP of all Pokémon for 5 turns.','GRASS');
INSERT INTO Attacks VALUES('Gravity',5,null,null,'Prevents moves like Fly and Bounce and the Ability Levitate for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Growl',40,100,null,'Lowers opponent s Attack.','NORMAL');
INSERT INTO Attacks VALUES('Growth',40,null,null,'Raises user s Attack and Special Attack.','NORMAL');
INSERT INTO Attacks VALUES('Grudge',5,null,null,'If the users faints after using this move, the PP for the opponent s last move is depleted.','GHOST');
INSERT INTO Attacks VALUES('Guard Split',10,null,null,'Averages Defense and Special Defense with the target.','PSYCHIC');
INSERT INTO Attacks VALUES('Guard Swap',10,null,null,'User and opponent swap Defense and Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Guardian of Alola',1,null,null,'Tapu-exclusive Z-move. Cuts opponent s HP by 75%.','FAIRY');
INSERT INTO Attacks VALUES('Guillotine',5,null,null,'One-Hit-KO, if it hits.','NORMAL');
INSERT INTO Attacks VALUES('Gunk Shot',5,80,120,'May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Gust',35,100,40,'Hits Pokémon using Fly/Bounce with double power.','FLYING');
INSERT INTO Attacks VALUES('Gyro Ball',5,100,null,'The slower the user, the stronger the attack.','STEEL');
INSERT INTO Attacks VALUES('Hail',10,null,null,'Non-Ice types are damaged for 5 turns.','ICE');
INSERT INTO Attacks VALUES('Hammer Arm',10,90,100,'Lowers user s Speed.','FIGHTING');
INSERT INTO Attacks VALUES('Happy Hour',30,null,null,'Doubles prize money from trainer battles.','NORMAL');
INSERT INTO Attacks VALUES('Harden',30,null,null,'Raises user s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Haze',30,null,null,'Resets all stat changes.','ICE');
INSERT INTO Attacks VALUES('Head Charge',15,100,120,'User receives recoil damage.','NORMAL');
INSERT INTO Attacks VALUES('Head Smash',5,80,150,'User receives recoil damage.','ROCK');
INSERT INTO Attacks VALUES('Headbutt',15,100,70,'May cause flinching.','NORMAL');
INSERT INTO Attacks VALUES('Heal Bell',5,null,null,'Heals the user s party s status conditions.','NORMAL');
INSERT INTO Attacks VALUES('Heal Block',15,null,null,'Prevents the opponent from restoring HP for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Heal Order',10,null,null,'User recovers half its max HP.','BUG');
INSERT INTO Attacks VALUES('Heal Pulse',10,null,null,'Restores half the target s max HP.','PSYCHIC');
INSERT INTO Attacks VALUES('Healing Wish',10,null,null,'The user faints and the next Pokémon released is fully healed.','PSYCHIC');
INSERT INTO Attacks VALUES('Heart Stamp',25,100,60,'May cause flinching.','PSYCHIC');
INSERT INTO Attacks VALUES('Heart Swap',10,null,null,'Stat changes are swapped with the opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Heat Crash',10,100,null,'The heavier the user, the stronger the attack.','FIRE');
INSERT INTO Attacks VALUES('Heat Wave',10,90,95,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Heavy Slam',10,100,null,'The heavier the user, the stronger the attack.','STEEL');
INSERT INTO Attacks VALUES('Helping Hand',20,null,null,'In Double Battles, boosts the power of the partner s move.','NORMAL');
INSERT INTO Attacks VALUES('Hex',10,100,65,'Inflicts more damage if the target has a status condition.','GHOST');
INSERT INTO Attacks VALUES('Hidden Power',15,100,60,'Type and power depends on user s IVs.','NORMAL');
INSERT INTO Attacks VALUES('High Horsepower',10,95,95,'The user fiercely attacks the target using its entire body.','GROUND');
INSERT INTO Attacks VALUES('High Jump Kick',10,90,130,'If it misses, the user loses half their HP.','FIGHTING');
INSERT INTO Attacks VALUES('Hold Back',40,100,40,'Always leaves opponent with at least 1 HP.','NORMAL');
INSERT INTO Attacks VALUES('Hold Hands',40,null,null,'Makes the user and an ally very happy.','NORMAL');
INSERT INTO Attacks VALUES('Hone Claws',15,null,null,'Raises user s Attack and Accuracy.','DARK');
INSERT INTO Attacks VALUES('Horn Attack',25,100,65,'null','NORMAL');
INSERT INTO Attacks VALUES('Horn Drill',5,null,null,'One-Hit-KO, if it hits.','NORMAL');
INSERT INTO Attacks VALUES('Horn Leech',10,100,75,'User recovers half the HP inflicted on opponent.','GRASS');
INSERT INTO Attacks VALUES('Howl',40,null,null,'Raises user s Attack.','NORMAL');
INSERT INTO Attacks VALUES('Hurricane',10,70,110,'May confuse opponent.','FLYING');
INSERT INTO Attacks VALUES('Hydro Cannon',5,90,150,'User must recharge next turn.','WATER');
INSERT INTO Attacks VALUES('Hydro Pump',5,80,110,'null','WATER');
INSERT INTO Attacks VALUES('Hydro Vortex',1,null,null,'Water type Z-Move.','WATER');
INSERT INTO Attacks VALUES('Hyper Beam',5,90,150,'User must recharge next turn.','NORMAL');
INSERT INTO Attacks VALUES('Hyper Fang',15,90,80,'May cause flinching.','NORMAL');
INSERT INTO Attacks VALUES('Hyper Voice',10,100,90,'null','NORMAL');
INSERT INTO Attacks VALUES('Hyperspace Fury',5,110,100,'Lowers user s Defense. Can strike through Protect/Detect.','DARK');
INSERT INTO Attacks VALUES('Hyperspace Hole',5,110,80,'Can strike through Protect/Detect.','PSYCHIC');
INSERT INTO Attacks VALUES('Hypnosis',20,60,null,'Puts opponent to sleep.','PSYCHIC');
INSERT INTO Attacks VALUES('Ice Ball',20,90,30,'Doubles in power each turn for 5 turns.','ICE');
INSERT INTO Attacks VALUES('Ice Beam',10,100,90,'May freeze opponent.','ICE');
INSERT INTO Attacks VALUES('Ice Burn',5,90,140,'Charges on first turn, attacks on second. May burn opponent.','ICE');
INSERT INTO Attacks VALUES('Ice Fang',15,95,65,'May cause flinching and/or freeze opponent.','ICE');
INSERT INTO Attacks VALUES('Ice Hammer',10,90,100,'The user swings and hits with its strong, heavy fist. It lowers the user s Speed, however.','ICE');
INSERT INTO Attacks VALUES('Ice Punch',15,100,75,'May freeze opponent.','ICE');
INSERT INTO Attacks VALUES('Ice Shard',30,100,40,'User attacks first.','ICE');
INSERT INTO Attacks VALUES('Icicle Crash',10,90,85,'May cause flinching.','ICE');
INSERT INTO Attacks VALUES('Icicle Spear',30,100,25,'Hits 2-5 times in one turn.','ICE');
INSERT INTO Attacks VALUES('Icy Wind',15,95,55,'Lowers opponent s Speed.','ICE');
INSERT INTO Attacks VALUES('Imprison',10,null,null,'Opponent is unable to use moves that the user also knows.','PSYCHIC');
INSERT INTO Attacks VALUES('Incinerate',15,100,60,'Destroys the target s held berry.','FIRE');
INSERT INTO Attacks VALUES('Inferno',5,50,100,'Burns opponent.','FIRE');
INSERT INTO Attacks VALUES('Inferno Overdrive',1,null,null,'Fire type Z-Move.','FIRE');
INSERT INTO Attacks VALUES('Infestation',20,100,20,'Traps opponent, damaging them for 4-5 turns.','BUG');
INSERT INTO Attacks VALUES('Ingrain',20,null,null,'User restores HP each turn. User cannot escape/switch.','GRASS');
INSERT INTO Attacks VALUES('Instruct',15,null,null,'Allows an ally to use a move instead.','PSYCHIC');
INSERT INTO Attacks VALUES('Ion Deluge',25,null,null,'Changes Normal-type moves to Electric-type.','ELECTRIC');
INSERT INTO Attacks VALUES('Iron Defense',15,null,null,'Sharply raises user s Defense.','STEEL');
INSERT INTO Attacks VALUES('Iron Head',15,100,80,'May cause flinching.','STEEL');
INSERT INTO Attacks VALUES('Iron Tail',15,75,100,'May lower opponent s Defense.','STEEL');
INSERT INTO Attacks VALUES('Judgment',10,100,100,'Type depends on the Arceus Plate being held.','NORMAL');
INSERT INTO Attacks VALUES('Jump Kick',10,95,100,'If it misses, the user loses half their HP.','FIGHTING');
INSERT INTO Attacks VALUES('Karate Chop',25,100,50,'High critical hit ratio.','FIGHTING');
INSERT INTO Attacks VALUES('Kinesis',15,80,null,'Lowers opponent s Accuracy.','PSYCHIC');
INSERT INTO Attacks VALUES('King s Shield',10,null,null,'Protects the user and lowers opponent s Attack on contact.','STEEL');
INSERT INTO Attacks VALUES('Knock Off',20,100,65,'Removes opponent s held item for the rest of the battle.','DARK');
INSERT INTO Attacks VALUES('Land s Wrath',10,100,90,'null','GROUND');
INSERT INTO Attacks VALUES('Laser Focus',30,null,null,'user s next attack is guaranteed to result in a critical hit.','NORMAL');
INSERT INTO Attacks VALUES('Last Resort',5,100,140,'Can only be used after all other moves are used.','NORMAL');
INSERT INTO Attacks VALUES('Lava Plume',15,100,80,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Leaf Blade',15,100,90,'High critical hit ratio.','GRASS');
INSERT INTO Attacks VALUES('Leaf Storm',5,90,130,'Sharply lowers user s Special Attack.','GRASS');
INSERT INTO Attacks VALUES('Leaf Tornado',10,90,65,'May lower opponent s Accuracy.','GRASS');
INSERT INTO Attacks VALUES('Leafage',40,100,40,'Strikes opponent with leaves.','GRASS');
INSERT INTO Attacks VALUES('Leech Life',10,100,80,'User recovers half the HP inflicted on opponent.','BUG');
INSERT INTO Attacks VALUES('Leech Seed',10,90,null,'Drains HP from opponent each turn.','GRASS');
INSERT INTO Attacks VALUES('Leer',30,100,null,'Lowers opponent s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Let s Snuggle Forever',1,null,190,'Mimikyu-exclusive Z-Move.','FAIRY');
INSERT INTO Attacks VALUES('Lick',30,100,30,'May paralyze opponent.','GHOST');
INSERT INTO Attacks VALUES('Light of Ruin',5,90,140,'User receives recoil damage.','FAIRY');
INSERT INTO Attacks VALUES('Light Screen',30,null,null,'Halves damage from Special attacks for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Light That Burns the Sky',1,null,200,'Ultra Necrozma-exclusive Z-Move. Ignores target s ability; uses highest Attack stat.','PSYCHIC');
INSERT INTO Attacks VALUES('Liquidation',10,100,85,'The user slams into the target using a full-force blast of water. This may also lower the target s Defense stat.','WATER');
INSERT INTO Attacks VALUES('Lock-On',5,null,null,'user s next attack is guaranteed to hit.','NORMAL');
INSERT INTO Attacks VALUES('Lovely Kiss',10,75,null,'Puts opponent to sleep.','NORMAL');
INSERT INTO Attacks VALUES('Low Kick',20,100,null,'The heavier the opponent, the stronger the attack.','FIGHTING');
INSERT INTO Attacks VALUES('Low Sweep',20,100,65,'Lowers opponent s Speed.','FIGHTING');
INSERT INTO Attacks VALUES('Lucky Chant',30,null,null,'Opponent cannot land critical hits for 5 turns.','NORMAL');
INSERT INTO Attacks VALUES('Lunar Dance',10,null,null,'The user faints but the next Pokémon released is fully healed.','PSYCHIC');
INSERT INTO Attacks VALUES('Lunge',15,100,80,'The user makes a lunge at the target, attacking with full force. This also lowers the target s Attack stat.','BUG');
INSERT INTO Attacks VALUES('Luster Purge',5,100,70,'May lower opponent s Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Mach Punch',30,100,40,'User attacks first.','FIGHTING');
INSERT INTO Attacks VALUES('Magic Coat',15,null,null,'Reflects moves that cause status conditions back to the attacker.','PSYCHIC');
INSERT INTO Attacks VALUES('Magic Room',10,null,null,'Suppresses the effects of held items for five turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Magical Leaf',20,110,60,'Ignores Accuracy and Evasiveness.','GRASS');
INSERT INTO Attacks VALUES('Magma Storm',5,75,100,'Traps opponent, damaging them for 4-5 turns.','FIRE');
INSERT INTO Attacks VALUES('Magnet Bomb',20,110,60,'Ignores Accuracy and Evasiveness.','STEEL');
INSERT INTO Attacks VALUES('Magnet Rise',10,null,null,'User becomes immune to Ground-type moves for 5 turns.','ELECTRIC');
INSERT INTO Attacks VALUES('Magnetic Flux',20,null,null,'Raises Defense and Sp. Defense of Plus/Minus Pokémon.','ELECTRIC');
INSERT INTO Attacks VALUES('Magnitude',30,100,null,'Hits with random power.','GROUND');
INSERT INTO Attacks VALUES('Malicious Moonsault',1,null,180,'Incineroar-exclusive Z-Move.','DARK');
INSERT INTO Attacks VALUES('Mat Block',10,null,null,'Protects teammates from damaging moves.','FIGHTING');
INSERT INTO Attacks VALUES('Me First',20,null,null,'User copies the opponent s attack with 1.5× power.','NORMAL');
INSERT INTO Attacks VALUES('Mean Look',5,null,null,'Opponent cannot flee or switch.','NORMAL');
INSERT INTO Attacks VALUES('Meditate',40,null,null,'Raises user s Attack.','PSYCHIC');
INSERT INTO Attacks VALUES('Mega Drain',15,100,40,'User recovers half the HP inflicted on opponent.','GRASS');
INSERT INTO Attacks VALUES('Mega Kick',5,75,120,'null','NORMAL');
INSERT INTO Attacks VALUES('Mega Punch',20,85,80,'null','NORMAL');
INSERT INTO Attacks VALUES('Megahorn',10,85,120,'null','BUG');
INSERT INTO Attacks VALUES('Memento',10,100,null,'User faints, sharply lowers opponent s Attack and Special Attack.','DARK');
INSERT INTO Attacks VALUES('Menacing Moonraze Maelstrom',1,null,200,'Lunala-exclusive Z-Move.','GHOST');
INSERT INTO Attacks VALUES('Metal Burst',10,100,null,'Deals damage equal to 1.5x opponent s attack.','STEEL');
INSERT INTO Attacks VALUES('Metal Claw',35,95,50,'May raise user s Attack.','STEEL');
INSERT INTO Attacks VALUES('Metal Sound',40,85,null,'Sharply lowers opponent s Special Defense.','STEEL');
INSERT INTO Attacks VALUES('Meteor Mash',10,90,90,'May raise user s Attack.','STEEL');
INSERT INTO Attacks VALUES('Metronome',10,null,null,'User performs almost any move in the game at random.','NORMAL');
INSERT INTO Attacks VALUES('Milk Drink',10,null,null,'User recovers half its max HP.','NORMAL');
INSERT INTO Attacks VALUES('Mimic',10,null,null,'Copies the opponent s last move.','NORMAL');
INSERT INTO Attacks VALUES('Mind Blown',5,100,150,'User receives recoil damage.','FIRE');
INSERT INTO Attacks VALUES('Mind Reader',5,null,null,'user s next attack is guaranteed to hit.','NORMAL');
INSERT INTO Attacks VALUES('Minimize',10,null,null,'Sharply raises user s Evasiveness.','NORMAL');
INSERT INTO Attacks VALUES('Miracle Eye',40,null,null,'Resets opponent s Evasiveness, removes Dark s Psychic immunity.','PSYCHIC');
INSERT INTO Attacks VALUES('Mirror Coat',20,100,null,'When hit by a Special Attack, user strikes back with 2x power.','PSYCHIC');
INSERT INTO Attacks VALUES('Mirror Move',20,null,null,'User performs the opponent s last move.','FLYING');
INSERT INTO Attacks VALUES('Mirror Shot',10,85,65,'May lower opponent s Accuracy.','STEEL');
INSERT INTO Attacks VALUES('Mist',30,null,null,'user s stats cannot be changed for a period of time.','ICE');
INSERT INTO Attacks VALUES('Mist Ball',5,100,70,'May lower opponent s Special Attack.','PSYCHIC');
INSERT INTO Attacks VALUES('Misty Terrain',10,null,null,'Protects the field from status conditions for 5 turns.','FAIRY');
INSERT INTO Attacks VALUES('Moonblast',15,100,95,'May lower opponent s Special Attack.','FAIRY');
INSERT INTO Attacks VALUES('Moongeist Beam',5,100,100,'Ignores the target s ability.','GHOST');
INSERT INTO Attacks VALUES('Moonlight',5,null,null,'User recovers HP. Amount varies with the weather.','FAIRY');
INSERT INTO Attacks VALUES('Morning Sun',5,null,null,'User recovers HP. Amount varies with the weather.','NORMAL');
INSERT INTO Attacks VALUES('Mud Bomb',10,85,65,'May lower opponent s Accuracy.','GROUND');
INSERT INTO Attacks VALUES('Mud Shot',15,95,55,'Lowers opponent s Speed.','GROUND');
INSERT INTO Attacks VALUES('Mud Sport',15,null,null,'Weakens the power of Electric-type moves.','GROUND');
INSERT INTO Attacks VALUES('Mud-Slap',10,100,20,'Lowers opponent s Accuracy.','GROUND');
INSERT INTO Attacks VALUES('Muddy Water',10,85,90,'May lower opponent s Accuracy.','WATER');
INSERT INTO Attacks VALUES('Multi-Attack',10,100,90,'Type matches user s current type.','NORMAL');
INSERT INTO Attacks VALUES('Mystical Fire',10,100,75,'Lowers opponent s Special Attack.','FIRE');
INSERT INTO Attacks VALUES('Nasty Plot',20,null,null,'Sharply raises user s Special Attack.','DARK');
INSERT INTO Attacks VALUES('Natural Gift',15,100,null,'Power and type depend on the user s held berry.','NORMAL');
INSERT INTO Attacks VALUES('Nature Power',20,null,null,'Uses a certain move based on the current terrain.','NORMAL');
INSERT INTO Attacks VALUES('Nature s Madness',10,90,null,'Halves the foe s HP.','FAIRY');
INSERT INTO Attacks VALUES('Needle Arm',15,100,60,'May cause flinching.','GRASS');
INSERT INTO Attacks VALUES('Never-Ending Nightmare',1,null,null,'Ghost type Z-Move.','GHOST');
INSERT INTO Attacks VALUES('Night Daze',10,95,85,'May lower opponent s Accuracy.','DARK');
INSERT INTO Attacks VALUES('Night Shade',15,100,null,'Inflicts damage equal to user s level.','GHOST');
INSERT INTO Attacks VALUES('Night Slash',15,100,70,'High critical hit ratio.','DARK');
INSERT INTO Attacks VALUES('Nightmare',15,100,null,'The sleeping opponent loses 25% of its max HP each turn.','GHOST');
INSERT INTO Attacks VALUES('Noble Roar',30,100,null,'Lowers opponent s Attack and Special Attack.','NORMAL');
INSERT INTO Attacks VALUES('Nuzzle',20,100,20,'Paralyzes opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Oblivion Wing',10,100,80,'User recovers most of the HP inflicted on opponent.','FLYING');
INSERT INTO Attacks VALUES('Oceanic Operetta',1,null,195,'Primarina-exclusive Z-Move.','WATER');
INSERT INTO Attacks VALUES('Octazooka',10,85,65,'May lower opponent s Accuracy.','WATER');
INSERT INTO Attacks VALUES('Odor Sleuth',40,null,null,'Resets opponent s Evasiveness, Normal-type and Fighting-type attacks can now hit Ghosts, and Ghost-type attacks hit Normal.','NORMAL');
INSERT INTO Attacks VALUES('Ominous Wind',5,100,60,'May raise all user s stats at once.','GHOST');
INSERT INTO Attacks VALUES('Origin Pulse',10,85,110,'Hits all adjacent opponents.','WATER');
INSERT INTO Attacks VALUES('Outrage',10,100,120,'User attacks for 2-3 turns but then becomes confused.','DRAGON');
INSERT INTO Attacks VALUES('Overheat',5,90,130,'Sharply lowers user s Special Attack.','FIRE');
INSERT INTO Attacks VALUES('Pain Split',20,null,null,'The user s and opponent s HP becomes the average of both.','NORMAL');
INSERT INTO Attacks VALUES('Parabolic Charge',20,100,65,'User recovers half the HP inflicted on opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Parting Shot',20,100,null,'Lowers opponent s Attack and Special Attack then switches out.','DARK');
INSERT INTO Attacks VALUES('Pay Day',20,100,40,'A small amount of money is gained after the battle resolves.','NORMAL');
INSERT INTO Attacks VALUES('Payback',10,100,50,'Power doubles if the user was attacked first.','DARK');
INSERT INTO Attacks VALUES('Peck',35,100,35,'null','FLYING');
INSERT INTO Attacks VALUES('Perish Song',5,null,null,'Any Pokémon in play when this attack is used faints in 3 turns.','NORMAL');
INSERT INTO Attacks VALUES('Petal Blizzard',15,100,90,'Hits all adjacent Pokémon.','GRASS');
INSERT INTO Attacks VALUES('Petal Dance',10,100,120,'User attacks for 2-3 turns but then becomes confused.','GRASS');
INSERT INTO Attacks VALUES('Phantom Force',10,100,90,'Disappears on first turn, attacks on second. Can strike through Protect/Detect.','GHOST');
INSERT INTO Attacks VALUES('Photon Geyser',5,100,100,'Uses Attack or Special Attack stat, whichever is higher.','PSYCHIC');
INSERT INTO Attacks VALUES('Pika Papow',20,110,null,'Power increases when player s bond is stronger.','ELECTRIC');
INSERT INTO Attacks VALUES('Pin Missile',20,95,25,'Hits 2-5 times in one turn.','BUG');
INSERT INTO Attacks VALUES('Plasma Fists',15,100,100,'Changes Normal-type moves to Electric-type moves.','ELECTRIC');
INSERT INTO Attacks VALUES('Play Nice',20,null,null,'Lowers opponent s Attack. Always hits.','NORMAL');
INSERT INTO Attacks VALUES('Play Rough',10,90,90,'May lower opponent s Attack.','FAIRY');
INSERT INTO Attacks VALUES('Pluck',20,100,60,'If the opponent is holding a berry, its effect is stolen by user.','FLYING');
INSERT INTO Attacks VALUES('Poison Fang',15,100,50,'May badly poison opponent.','POISON');
INSERT INTO Attacks VALUES('Poison Gas',40,90,null,'Poisons opponent.','POISON');
INSERT INTO Attacks VALUES('Poison Jab',20,100,80,'May poison the opponent.','POISON');
INSERT INTO Attacks VALUES('Poison Powder',35,75,null,'Poisons opponent.','POISON');
INSERT INTO Attacks VALUES('Poison Sting',35,100,15,'May poison the opponent.','POISON');
INSERT INTO Attacks VALUES('Poison Tail',25,100,50,'High critical hit ratio. May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Pollen Puff',15,100,90,'The user attacks the enemy with a pollen puff that explodes. If the target is an ally, it gives the ally a pollen puff that restores its HP instead.','BUG');
INSERT INTO Attacks VALUES('Pound',35,100,40,'null','NORMAL');
INSERT INTO Attacks VALUES('Powder',20,100,null,'Damages Pokémon using Fire type moves.','BUG');
INSERT INTO Attacks VALUES('Powder Snow',25,100,40,'May freeze opponent.','ICE');
INSERT INTO Attacks VALUES('Power Gem',20,100,80,'null','ROCK');
INSERT INTO Attacks VALUES('Power Split',10,null,null,'Averages Attack and Special Attack with the target.','PSYCHIC');
INSERT INTO Attacks VALUES('Power Swap',10,null,null,'User and opponent swap Attack and Special Attack.','PSYCHIC');
INSERT INTO Attacks VALUES('Power Trick',10,null,null,'user s own Attack and Defense switch.','PSYCHIC');
INSERT INTO Attacks VALUES('Power Trip',10,100,20,'The user boasts its strength and attacks the target. The more the user s stats are raised, the greater the move s power.','DARK');
INSERT INTO Attacks VALUES('Power Whip',10,85,120,'null','GRASS');
INSERT INTO Attacks VALUES('Power-Up Punch',10,100,40,'Raises Attack.','FIGHTING');
INSERT INTO Attacks VALUES('Precipice Blades',10,85,120,'Hits all adjacent opponents.','GROUND');
INSERT INTO Attacks VALUES('Present',15,90,null,'Either deals damage or heals.','NORMAL');
INSERT INTO Attacks VALUES('Prismatic Laser',10,100,160,'The user shoots powerful lasers using the power of a prism. The user can t move on the next turn.','PSYCHIC');
INSERT INTO Attacks VALUES('Protect',10,null,null,'Protects the user, but may fail if used consecutively.','NORMAL');
INSERT INTO Attacks VALUES('Psybeam',20,100,65,'May confuse opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Psych Up',10,null,null,'Copies the opponent s stat changes.','NORMAL');
INSERT INTO Attacks VALUES('Psychic',10,100,90,'May lower opponent s Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Psychic Fangs',10,100,85,'The user bites the target with its psychic capabilities. This can also destroy Light Screen and Reflect.','PSYCHIC');
INSERT INTO Attacks VALUES('Psychic Terrain',10,null,null,'Prevents priority moves from being used for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Psycho Boost',5,90,140,'Sharply lowers user s Special Attack.','PSYCHIC');
INSERT INTO Attacks VALUES('Psycho Cut',20,100,70,'High critical hit ratio.','PSYCHIC');
INSERT INTO Attacks VALUES('Psycho Shift',10,90,null,'Gives the opponent the user s status condition, if it hits.','PSYCHIC');
INSERT INTO Attacks VALUES('Psyshock',10,100,80,'Inflicts damage based on the target s Defense, not Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Psystrike',10,100,100,'Inflicts damage based on the target s Defense, not Special Defense.','PSYCHIC');
INSERT INTO Attacks VALUES('Psywave',15,80,null,'Inflicts damage 50-150% of user s level.','PSYCHIC');
INSERT INTO Attacks VALUES('Pulverizing Pancake',1,null,210,'Snorlax-exclusive Normal type Z-Move.','NORMAL');
INSERT INTO Attacks VALUES('Punishment',5,100,null,'Power increases when opponent s stats have been raised.','DARK');
INSERT INTO Attacks VALUES('Purify',20,null,null,'The user heals the target s status condition. If the move succeeds, it also restores the user s own HP.','POISON');
INSERT INTO Attacks VALUES('Pursuit',20,100,40,'Double power if the opponent is switching out.','DARK');
INSERT INTO Attacks VALUES('Quash',15,100,null,'Makes the target act last this turn.','DARK');
INSERT INTO Attacks VALUES('Quick Attack',30,100,40,'User attacks first.','NORMAL');
INSERT INTO Attacks VALUES('Quick Guard',15,null,null,'Protects the user s team from high-priority moves.','FIGHTING');
INSERT INTO Attacks VALUES('Quiver Dance',20,null,null,'Raises user s Special Attack, Special Defense and Speed.','BUG');
INSERT INTO Attacks VALUES('Rage',20,100,20,'Raises user s Attack when hit.','NORMAL');
INSERT INTO Attacks VALUES('Rage Powder',20,null,null,'Forces attacks to hit user, not team-mates.','BUG');
INSERT INTO Attacks VALUES('Rain Dance',5,null,null,'Makes it rain for 5 turns.','WATER');
INSERT INTO Attacks VALUES('Rapid Spin',40,100,20,'Removes effects of trap moves.','NORMAL');
INSERT INTO Attacks VALUES('Razor Leaf',25,95,55,'High critical hit ratio.','GRASS');
INSERT INTO Attacks VALUES('Razor Shell',10,95,75,'May lower opponent s Defense.','WATER');
INSERT INTO Attacks VALUES('Razor Wind',10,100,80,'Charges on first turn, attacks on second. High critical hit ratio.','NORMAL');
INSERT INTO Attacks VALUES('Recover',10,null,null,'User recovers half its max HP.','NORMAL');
INSERT INTO Attacks VALUES('Recycle',10,null,null,'user s used hold item is restored.','NORMAL');
INSERT INTO Attacks VALUES('Reflect',20,null,null,'Halves damage from Physical attacks for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Reflect Type',15,null,null,'User becomes the target s type.','NORMAL');
INSERT INTO Attacks VALUES('Refresh',20,null,null,'Cures paralysis, poison, and burns.','NORMAL');
INSERT INTO Attacks VALUES('Relic Song',10,100,75,'May put the target to sleep.','NORMAL');
INSERT INTO Attacks VALUES('Rest',10,null,null,'User sleeps for 2 turns, but user is fully healed.','PSYCHIC');
INSERT INTO Attacks VALUES('Retaliate',5,100,70,'Inflicts double damage if a teammate fainted on the last turn.','NORMAL');
INSERT INTO Attacks VALUES('Return',20,100,null,'Power increases with higher Friendship.','NORMAL');
INSERT INTO Attacks VALUES('Revelation Dance',15,100,90,'Type changes based on Oricorio s form.','NORMAL');
INSERT INTO Attacks VALUES('Revenge',10,100,60,'Power increases if user was hit first.','FIGHTING');
INSERT INTO Attacks VALUES('Reversal',15,100,null,'The lower the user s HP, the higher the power.','FIGHTING');
INSERT INTO Attacks VALUES('Roar',20,null,null,'In battles, the opponent switches. In the wild, the Pokémon runs.','NORMAL');
INSERT INTO Attacks VALUES('Roar of Time',5,90,150,'User must recharge next turn.','DRAGON');
INSERT INTO Attacks VALUES('Rock Blast',10,90,25,'Hits 2-5 times in one turn.','ROCK');
INSERT INTO Attacks VALUES('Rock Climb',20,85,90,'May confuse opponent.','NORMAL');
INSERT INTO Attacks VALUES('Rock Polish',20,null,null,'Sharply raises user s Speed.','ROCK');
INSERT INTO Attacks VALUES('Rock Slide',10,90,75,'May cause flinching.','ROCK');
INSERT INTO Attacks VALUES('Rock Smash',15,100,40,'May lower opponent s Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Rock Throw',15,90,50,'null','ROCK');
INSERT INTO Attacks VALUES('Rock Tomb',15,95,60,'Lowers opponent s Speed.','ROCK');
INSERT INTO Attacks VALUES('Rock Wrecker',5,90,150,'User must recharge next turn.','ROCK');
INSERT INTO Attacks VALUES('Role Play',15,null,null,'User copies the opponent s Ability.','PSYCHIC');
INSERT INTO Attacks VALUES('Rolling Kick',15,85,60,'May cause flinching.','FIGHTING');
INSERT INTO Attacks VALUES('Rollout',20,90,30,'Doubles in power each turn for 5 turns.','ROCK');
INSERT INTO Attacks VALUES('Roost',10,null,null,'User recovers half of its max HP and loses the Flying type temporarily.','FLYING');
INSERT INTO Attacks VALUES('Rototiller',10,null,null,'Raises Attack and Special Attack of Grass-types.','GROUND');
INSERT INTO Attacks VALUES('Round',15,100,60,'Power increases if teammates use it in the same turn.','NORMAL');
INSERT INTO Attacks VALUES('Sacred Fire',5,95,100,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Sacred Sword',20,100,90,'Ignores opponent s stat changes.','FIGHTING');
INSERT INTO Attacks VALUES('Safeguard',25,null,null,'The user s party is protected from status conditions.','NORMAL');
INSERT INTO Attacks VALUES('Sand Attack',15,100,null,'Lowers opponent s Accuracy.','GROUND');
INSERT INTO Attacks VALUES('Sand Tomb',15,85,35,'Traps opponent, damaging them for 4-5 turns.','GROUND');
INSERT INTO Attacks VALUES('Sandstorm',10,null,null,'Creates a sandstorm for 5 turns.','ROCK');
INSERT INTO Attacks VALUES('Sappy Seed',15,100,90,'Drains HP from opponent each turn.','GRASS');
INSERT INTO Attacks VALUES('Savage Spin-Out',1,null,null,'Bug type Z-Move.','BUG');
INSERT INTO Attacks VALUES('Scald',15,100,80,'May burn opponent.','WATER');
INSERT INTO Attacks VALUES('Scary Face',10,100,null,'Sharply lowers opponent s Speed.','NORMAL');
INSERT INTO Attacks VALUES('Scratch',35,100,40,'null','NORMAL');
INSERT INTO Attacks VALUES('Screech',40,85,null,'Sharply lowers opponent s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Searing Shot',5,100,100,'May burn opponent.','FIRE');
INSERT INTO Attacks VALUES('Searing Sunraze Smash',1,null,200,'Solgaleo-exclusive Z-Move.','STEEL');
INSERT INTO Attacks VALUES('Secret Power',20,100,70,'Effects of the attack vary with the location.','NORMAL');
INSERT INTO Attacks VALUES('Secret Sword',10,100,85,'Inflicts damage based on the target s Defense, not Special Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Seed Bomb',15,100,80,'null','GRASS');
INSERT INTO Attacks VALUES('Seed Flare',5,85,120,'May lower opponent s Special Defense.','GRASS');
INSERT INTO Attacks VALUES('Seismic Toss',20,100,null,'Inflicts damage equal to user s level.','FIGHTING');
INSERT INTO Attacks VALUES('Self-Destruct',5,100,200,'User faints.','NORMAL');
INSERT INTO Attacks VALUES('Shadow Ball',15,100,80,'May lower opponent s Special Defense.','GHOST');
INSERT INTO Attacks VALUES('Shadow Bone',10,100,85,'The user attacks by beating the target with a bone that contains a spirit. This may also lower the target s Defense stat.','GHOST');
INSERT INTO Attacks VALUES('Shadow Claw',15,100,70,'High critical hit ratio.','GHOST');
INSERT INTO Attacks VALUES('Shadow Force',5,100,120,'Disappears on first turn, attacks on second. Can strike through Protect/Detect.','GHOST');
INSERT INTO Attacks VALUES('Shadow Punch',20,110,60,'Ignores Accuracy and Evasiveness.','GHOST');
INSERT INTO Attacks VALUES('Shadow Sneak',30,100,40,'User attacks first.','GHOST');
INSERT INTO Attacks VALUES('Sharpen',30,null,null,'Raises user s Attack.','NORMAL');
INSERT INTO Attacks VALUES('Shattered Psyche',1,null,null,'Psychic type Z-Move.','PSYCHIC');
INSERT INTO Attacks VALUES('Sheer Cold',5,null,null,'One-Hit-KO, if it hits.','ICE');
INSERT INTO Attacks VALUES('Shell Smash',15,null,null,'Sharply raises user s Attack, Special Attack and Speed but lowers Defense and Special Defense.','NORMAL');
INSERT INTO Attacks VALUES('Shell Trap',5,100,150,'Deals more damage to opponent if hit by a Physical move.','FIRE');
INSERT INTO Attacks VALUES('Shift Gear',10,null,null,'Raises user s Attack and sharply raises Speed.','STEEL');
INSERT INTO Attacks VALUES('Shock Wave',20,110,60,'Ignores Accuracy and Evasiveness.','ELECTRIC');
INSERT INTO Attacks VALUES('Shore Up',10,null,null,'The user regains up to half of its max HP. It restores more HP in a sandstorm.','GROUND');
INSERT INTO Attacks VALUES('Signal Beam',15,100,75,'May confuse opponent.','BUG');
INSERT INTO Attacks VALUES('Silver Wind',5,100,60,'May raise all stats of user at once.','BUG');
INSERT INTO Attacks VALUES('Simple Beam',15,100,null,'Changes target s ability to Simple.','NORMAL');
INSERT INTO Attacks VALUES('Sing',15,55,null,'Puts opponent to sleep.','NORMAL');
INSERT INTO Attacks VALUES('Sinister Arrow Raid',1,null,180,'Decidueye-exclusive Z-Move.','GHOST');
INSERT INTO Attacks VALUES('Sizzly Slide',15,100,90,'Burns the opponent.','FIRE');
INSERT INTO Attacks VALUES('Sketch',1,null,null,'Permanently copies the opponent s last move.','NORMAL');
INSERT INTO Attacks VALUES('Skill Swap',10,null,null,'The user swaps Abilities with the opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Skull Bash',10,100,130,'Raises Defense on first turn, attacks on second.','NORMAL');
INSERT INTO Attacks VALUES('Sky Attack',5,90,140,'Charges on first turn, attacks on second. May cause flinching.','FLYING');
INSERT INTO Attacks VALUES('Sky Drop',10,100,60,'Takes opponent into the air on first turn, drops them on second turn.','FLYING');
INSERT INTO Attacks VALUES('Sky Uppercut',15,90,85,'Hits the opponent, even during Fly.','FIGHTING');
INSERT INTO Attacks VALUES('Slack Off',10,null,null,'User recovers half its max HP.','NORMAL');
INSERT INTO Attacks VALUES('Slam',20,75,80,'null','NORMAL');
INSERT INTO Attacks VALUES('Slash',20,100,70,'High critical hit ratio.','NORMAL');
INSERT INTO Attacks VALUES('Sleep Powder',15,75,null,'Puts opponent to sleep.','GRASS');
INSERT INTO Attacks VALUES('Sleep Talk',10,null,null,'User performs one of its own moves while sleeping.','NORMAL');
INSERT INTO Attacks VALUES('Sludge',20,100,65,'May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Sludge Bomb',10,100,90,'May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Sludge Wave',10,100,95,'May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Smack Down',15,100,50,'Makes Flying-type Pokémon vulnerable to Ground moves.','ROCK');
INSERT INTO Attacks VALUES('Smart Strike',10,null,70,'The user stabs the target with a sharp horn. This attack never misses.','STEEL');
INSERT INTO Attacks VALUES('Smelling Salts',10,100,70,'Power doubles if opponent is paralyzed, but cures it.','NORMAL');
INSERT INTO Attacks VALUES('Smog',20,70,30,'May poison opponent.','POISON');
INSERT INTO Attacks VALUES('Smokescreen',20,100,null,'Lowers opponent s Accuracy.','NORMAL');
INSERT INTO Attacks VALUES('Snarl',15,95,55,'Lowers opponent s Special Attack.','DARK');
INSERT INTO Attacks VALUES('Snatch',10,null,null,'Steals the effects of the opponent s next move.','DARK');
INSERT INTO Attacks VALUES('Snore',15,100,50,'Can only be used if asleep. May cause flinching.','NORMAL');
INSERT INTO Attacks VALUES('Soak',20,100,null,'Changes the target s type to water.','WATER');
INSERT INTO Attacks VALUES('Soft-Boiled',10,null,null,'User recovers half its max HP.','NORMAL');
INSERT INTO Attacks VALUES('Solar Beam',10,100,120,'Charges on first turn, attacks on second.','GRASS');
INSERT INTO Attacks VALUES('Solar Blade',10,100,125,'Charges on first turn, attacks on second.','GRASS');
INSERT INTO Attacks VALUES('Sonic Boom',20,90,null,'Always inflicts 20 HP.','NORMAL');
INSERT INTO Attacks VALUES('Soul-Stealing 7-Star Strike',1,null,195,'Marshadow-exclusive Z-Move.','GHOST');
INSERT INTO Attacks VALUES('Spacial Rend',5,95,100,'High critical hit ratio.','DRAGON');
INSERT INTO Attacks VALUES('Spark',20,100,65,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Sparkling Aria',10,100,90,'Heals the burns of its target.','WATER');
INSERT INTO Attacks VALUES('Sparkly Swirl',15,100,90,'Cures all status problems in the party Pokémon.','FAIRY');
INSERT INTO Attacks VALUES('Spectral Thief',10,100,90,'The user hides in the target s shadow, steals the target s stat boosts, and then attacks.','GHOST');
INSERT INTO Attacks VALUES('Speed Swap',10,null,null,'The user exchanges Speed stats with the target.','PSYCHIC');
INSERT INTO Attacks VALUES('Spider Web',10,null,null,'Opponent cannot escape/switch.','BUG');
INSERT INTO Attacks VALUES('Spike Cannon',15,100,20,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Spikes',20,null,null,'Hurts opponents when they switch into battle.','GROUND');
INSERT INTO Attacks VALUES('Spiky Shield',10,null,null,'Protects the user and inflicts damage on contact.','GRASS');
INSERT INTO Attacks VALUES('Spirit Shackle',10,100,80,'Prevents the opponent switching out.','GHOST');
INSERT INTO Attacks VALUES('Spit Up',10,100,null,'Power depends on how many times the user performed Stockpile.','NORMAL');
INSERT INTO Attacks VALUES('Spite',10,100,null,'The opponent s last move loses 2-5 PP.','GHOST');
INSERT INTO Attacks VALUES('Splash',40,null,null,'Doesn t do ANYTHING.','NORMAL');
INSERT INTO Attacks VALUES('Splintered Stormshards',1,null,190,'Lycanroc-exclusive Z-Move.','ROCK');
INSERT INTO Attacks VALUES('Splishy Splash',15,100,90,'May paralyze opponent.','WATER');
INSERT INTO Attacks VALUES('Spore',15,100,null,'Puts opponent to sleep.','GRASS');
INSERT INTO Attacks VALUES('Spotlight',15,null,null,'The user shines a spotlight on the target so that only the target will be attacked during the turn.','NORMAL');
INSERT INTO Attacks VALUES('Stealth Rock',20,null,null,'Damages opponent switching into battle.','ROCK');
INSERT INTO Attacks VALUES('Steam Eruption',5,95,110,'May burn opponent.','WATER');
INSERT INTO Attacks VALUES('Steamroller',20,100,65,'May cause flinching.','BUG');
INSERT INTO Attacks VALUES('Steel Wing',25,90,70,'May raise user s Defense.','STEEL');
INSERT INTO Attacks VALUES('Sticky Web',20,null,null,'Lowers opponent s Speed when switching into battle.','BUG');
INSERT INTO Attacks VALUES('Stockpile',20,null,null,'Stores energy for use with Spit Up and Swallow.','NORMAL');
INSERT INTO Attacks VALUES('Stoked Sparksurfer',1,null,175,'Alolan Raichu-exclusive Electric type Z-Move.','ELECTRIC');
INSERT INTO Attacks VALUES('Stomp',20,100,65,'May cause flinching.','NORMAL');
INSERT INTO Attacks VALUES('Stomping Tantrum',10,100,75,'Driven by frustration, the user attacks the target. If the user s previous move has failed, the power of this move doubles.','GROUND');
INSERT INTO Attacks VALUES('Stone Edge',5,80,100,'High critical hit ratio.','ROCK');
INSERT INTO Attacks VALUES('Stored Power',10,100,20,'Power increases when user s stats have been raised.','PSYCHIC');
INSERT INTO Attacks VALUES('Storm Throw',10,100,60,'Always results in a critical hit.','FIGHTING');
INSERT INTO Attacks VALUES('Strength',15,100,80,'null','NORMAL');
INSERT INTO Attacks VALUES('Strength Sap',10,100,null,'The user restores its HP by the same amount as the target s Attack stat. It also lowers the target s Attack stat.','GRASS');
INSERT INTO Attacks VALUES('String Shot',40,95,null,'Sharply lowers opponent s Speed.','BUG');
INSERT INTO Attacks VALUES('Struggle',null,100,50,'Only usable when all PP are gone. Hurts the user.','NORMAL');
INSERT INTO Attacks VALUES('Struggle Bug',20,100,50,'Lowers opponent s Special Attack.','BUG');
INSERT INTO Attacks VALUES('Stun Spore',30,75,null,'Paralyzes opponent.','GRASS');
INSERT INTO Attacks VALUES('Submission',20,80,80,'User receives recoil damage.','FIGHTING');
INSERT INTO Attacks VALUES('Substitute',10,null,null,'Uses HP to creates a decoy that takes hits.','NORMAL');
INSERT INTO Attacks VALUES('Subzero Slammer',1,null,null,'Ice type Z-Move.','ICE');
INSERT INTO Attacks VALUES('Sucker Punch',5,100,70,'User attacks first, but only works if opponent is readying an attack.','DARK');
INSERT INTO Attacks VALUES('Sunny Day',5,null,null,'Makes it sunny for 5 turns.','FIRE');
INSERT INTO Attacks VALUES('Sunsteel Strike',5,100,100,'Ignores the target s ability.','STEEL');
INSERT INTO Attacks VALUES('Super Fang',10,90,null,'Always takes off half of the opponent s HP.','NORMAL');
INSERT INTO Attacks VALUES('Superpower',5,100,120,'Lowers user s Attack and Defense.','FIGHTING');
INSERT INTO Attacks VALUES('Supersonic',20,55,null,'Confuses opponent.','NORMAL');
INSERT INTO Attacks VALUES('Supersonic Skystrike',1,null,null,'Flying type Z-Move.','FLYING');
INSERT INTO Attacks VALUES('Surf',15,100,90,'Hits all adjacent Pokémon.','WATER');
INSERT INTO Attacks VALUES('Swagger',15,85,null,'Opponent becomes confused, but its Attack is sharply raised.','NORMAL');
INSERT INTO Attacks VALUES('Swallow',10,null,null,'The more times the user has performed Stockpile, the more HP is recovered.','NORMAL');
INSERT INTO Attacks VALUES('Sweet Kiss',10,75,null,'Confuses opponent.','FAIRY');
INSERT INTO Attacks VALUES('Sweet Scent',20,null,null,'Lowers opponent s Evasiveness.','NORMAL');
INSERT INTO Attacks VALUES('Swift',20,110,60,'Ignores Accuracy and Evasiveness.','NORMAL');
INSERT INTO Attacks VALUES('Switcheroo',15,100,null,'Swaps held items with the opponent.','DARK');
INSERT INTO Attacks VALUES('Swords Dance',20,null,null,'Sharply raises user s Attack.','NORMAL');
INSERT INTO Attacks VALUES('Synchronoise',15,100,120,'Hits any Pokémon that shares a type with the user.','PSYCHIC');
INSERT INTO Attacks VALUES('Synthesis',5,null,null,'User recovers HP. Amount varies with the weather.','GRASS');
INSERT INTO Attacks VALUES('Tackle',35,100,40,'null','NORMAL');
INSERT INTO Attacks VALUES('Tail Glow',20,null,null,'Drastically raises user s Special Attack.','BUG');
INSERT INTO Attacks VALUES('Tail Slap',10,85,25,'Hits 2-5 times in one turn.','NORMAL');
INSERT INTO Attacks VALUES('Tail Whip',30,100,null,'Lowers opponent s Defense.','NORMAL');
INSERT INTO Attacks VALUES('Tailwind',30,null,null,'Doubles Speed for 4 turns.','FLYING');
INSERT INTO Attacks VALUES('Take Down',20,85,90,'User receives recoil damage.','NORMAL');
INSERT INTO Attacks VALUES('Taunt',20,100,null,'Opponent can only use moves that attack.','DARK');
INSERT INTO Attacks VALUES('Tearful Look',20,null,null,'The user gets teary eyed to make the target lose its combative spirit. This lowers the target s Attack and Sp. Atk stats.','NORMAL');
INSERT INTO Attacks VALUES('Techno Blast',5,100,120,'Type depends on the Drive being held.','NORMAL');
INSERT INTO Attacks VALUES('Tectonic Rage',1,null,null,'Ground type Z-Move.','GROUND');
INSERT INTO Attacks VALUES('Teeter Dance',20,100,null,'Confuses all Pokémon.','NORMAL');
INSERT INTO Attacks VALUES('Telekinesis',15,null,null,'Ignores opponent s Evasiveness for three turns, add Ground immunity.','PSYCHIC');
INSERT INTO Attacks VALUES('Teleport',20,null,null,'Allows user to flee wild battles; also warps player to last PokéCenter.','PSYCHIC');
INSERT INTO Attacks VALUES('Thief',25,100,60,'Also steals opponent s held item.','DARK');
INSERT INTO Attacks VALUES('Thousand Arrows',10,100,90,'Makes Flying-type Pokémon vulnerable to Ground moves.','GROUND');
INSERT INTO Attacks VALUES('Thousand Waves',10,100,90,'Opponent cannot flee or switch.','GROUND');
INSERT INTO Attacks VALUES('Thrash',10,100,120,'User attacks for 2-3 turns but then becomes confused.','NORMAL');
INSERT INTO Attacks VALUES('Throat Chop',15,100,80,'Prevents use of sound moves for two turns.','DARK');
INSERT INTO Attacks VALUES('Thunder',10,70,110,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Thunder Fang',15,95,65,'May cause flinching and/or paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Thunder Punch',15,100,75,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Thunder Shock',30,100,40,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Thunder Wave',20,90,null,'Paralyzes opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Thunderbolt',15,100,90,'May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Tickle',20,100,null,'Lowers opponent s Attack and Defense.','NORMAL');
INSERT INTO Attacks VALUES('Topsy-Turvy',20,null,null,'Reverses stat changes of opponent.','DARK');
INSERT INTO Attacks VALUES('Torment',15,100,null,'Opponent cannot use the same move in a row.','DARK');
INSERT INTO Attacks VALUES('Toxic',10,90,null,'Badly poisons opponent.','POISON');
INSERT INTO Attacks VALUES('Toxic Spikes',20,null,null,'Poisons opponents when they switch into battle.','POISON');
INSERT INTO Attacks VALUES('Toxic Thread',20,100,null,'The user shoots poisonous threads to poison the target and lower the target s Speed stat.','POISON');
INSERT INTO Attacks VALUES('Transform',10,null,null,'User takes on the form and attacks of the opponent.','NORMAL');
INSERT INTO Attacks VALUES('Tri Attack',10,100,80,'May paralyze, burn or freeze opponent.','NORMAL');
INSERT INTO Attacks VALUES('Trick',10,100,null,'Swaps held items with the opponent.','PSYCHIC');
INSERT INTO Attacks VALUES('Trick Room',5,null,null,'Slower Pokémon move first in the turn for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Trick-or-Treat',20,100,null,'Adds Ghost type to opponent.','GHOST');
INSERT INTO Attacks VALUES('Triple Kick',10,90,10,'Hits thrice in one turn at increasing power.','FIGHTING');
INSERT INTO Attacks VALUES('Trop Kick',15,100,70,'Lowers opponent s Attack.','GRASS');
INSERT INTO Attacks VALUES('Trump Card',5,110,null,'The lower the PP, the higher the power.','NORMAL');
INSERT INTO Attacks VALUES('Twineedle',20,100,25,'Hits twice in one turn. May poison opponent.','BUG');
INSERT INTO Attacks VALUES('Twinkle Tackle',1,null,null,'Fairy type Z-Move.','FAIRY');
INSERT INTO Attacks VALUES('Twister',20,100,40,'May cause flinching. Hits Pokémon using Fly/Bounce with double power.','DRAGON');
INSERT INTO Attacks VALUES('U-turn',20,100,70,'User switches out immediately after attacking.','BUG');
INSERT INTO Attacks VALUES('Uproar',10,100,90,'User attacks for 3 turns and prevents sleep.','NORMAL');
INSERT INTO Attacks VALUES('V-create',5,95,180,'Lowers user s Defense, Special Defense and Speed.','FIRE');
INSERT INTO Attacks VALUES('Vacuum Wave',30,100,40,'User attacks first.','FIGHTING');
INSERT INTO Attacks VALUES('Veevee Volley',20,110,null,'Power increases when player s bond is stronger.','NORMAL');
INSERT INTO Attacks VALUES('Venom Drench',20,100,null,'Lowers poisoned opponent s Special Attack and Speed.','POISON');
INSERT INTO Attacks VALUES('Venoshock',10,100,65,'Inflicts double damage if the target is poisoned.','POISON');
INSERT INTO Attacks VALUES('Vice Grip',30,100,55,'null','NORMAL');
INSERT INTO Attacks VALUES('Vine Whip',25,100,45,'null','GRASS');
INSERT INTO Attacks VALUES('Vital Throw',10,110,70,'User attacks last, but ignores Accuracy and Evasiveness.','FIGHTING');
INSERT INTO Attacks VALUES('Volt Switch',20,100,70,'User must switch out after attacking.','ELECTRIC');
INSERT INTO Attacks VALUES('Volt Tackle',15,100,120,'User receives recoil damage. May paralyze opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Wake-Up Slap',10,100,70,'Power doubles if opponent is asleep, but wakes it up.','FIGHTING');
INSERT INTO Attacks VALUES('Water Gun',25,100,40,'null','WATER');
INSERT INTO Attacks VALUES('Water Pledge',10,100,80,'Added effects appear if preceded by Fire Pledge or succeeded by Grass Pledge.','WATER');
INSERT INTO Attacks VALUES('Water Pulse',20,100,60,'May confuse opponent.','WATER');
INSERT INTO Attacks VALUES('Water Shuriken',20,100,15,'Hits 2-5 times in one turn.','WATER');
INSERT INTO Attacks VALUES('Water Sport',15,null,null,'Weakens the power of Fire-type moves.','WATER');
INSERT INTO Attacks VALUES('Water Spout',5,100,150,'The higher the user s HP, the higher the damage caused.','WATER');
INSERT INTO Attacks VALUES('Waterfall',15,100,80,'May cause flinching.','WATER');
INSERT INTO Attacks VALUES('Weather Ball',10,100,50,'Move s power and type changes with the weather.','NORMAL');
INSERT INTO Attacks VALUES('Whirlpool',15,85,35,'Traps opponent, damaging them for 4-5 turns.','WATER');
INSERT INTO Attacks VALUES('Whirlwind',20,null,null,'In battles, the opponent switches. In the wild, the Pokémon runs.','NORMAL');
INSERT INTO Attacks VALUES('Wide Guard',10,null,null,'Protects the user s team from multi-target attacks.','ROCK');
INSERT INTO Attacks VALUES('Wild Charge',15,100,90,'User receives recoil damage.','ELECTRIC');
INSERT INTO Attacks VALUES('Will-O-Wisp',15,85,null,'Burns opponent.','FIRE');
INSERT INTO Attacks VALUES('Wing Attack',35,100,60,'null','FLYING');
INSERT INTO Attacks VALUES('Wish',10,null,null,'The user recovers HP in the following turn.','NORMAL');
INSERT INTO Attacks VALUES('Withdraw',40,null,null,'Raises user s Defense.','WATER');
INSERT INTO Attacks VALUES('Wonder Room',10,null,null,'Swaps every Pokémon s Defense and Special Defense for 5 turns.','PSYCHIC');
INSERT INTO Attacks VALUES('Wood Hammer',15,100,120,'User receives recoil damage.','GRASS');
INSERT INTO Attacks VALUES('Work Up',30,null,null,'Raises user s Attack and Special Attack.','NORMAL');
INSERT INTO Attacks VALUES('Worry Seed',10,100,null,'Changes the opponent s Ability to Insomnia.','GRASS');
INSERT INTO Attacks VALUES('Wrap',20,90,15,'Traps opponent, damaging them for 4-5 turns.','NORMAL');
INSERT INTO Attacks VALUES('Wring Out',5,100,null,'The higher the opponent s HP, the higher the damage.','NORMAL');
INSERT INTO Attacks VALUES('X-Scissor',15,100,80,'null','BUG');
INSERT INTO Attacks VALUES('Yawn',10,null,null,'Puts opponent to sleep in the next turn.','NORMAL');
INSERT INTO Attacks VALUES('Zap Cannon',5,50,120,'Paralyzes opponent.','ELECTRIC');
INSERT INTO Attacks VALUES('Zen Headbutt',15,90,80,'May cause flinching.','PSYCHIC');
INSERT INTO Attacks VALUES('Zing Zap',10,100,80,'A strong electric blast crashes down on the target, giving it an electric shock. This may also make the target flinch.','ELECTRIC');
INSERT INTO Attacks VALUES('Zippy Zap',15,100,50,'High critical-hit ratio.','ELECTRIC');