\c pokedabe
DELETE FROM Pokemon_Gym;
INSERT INTO Pokemon_Gym VALUES('Stone Badge',342592,'HOENN','ROCK');
INSERT INTO Pokemon_Gym VALUES('Knuckle Badge',734567,'HOENN','FIGHTING');
INSERT INTO Pokemon_Gym VALUES('Dynamo Badge',645323,'HOENN','ELECTRIC');
INSERT INTO Pokemon_Gym VALUES('Heat Badge',349506,'HOENN','FIRE');
INSERT INTO Pokemon_Gym VALUES('Balance Badge',958345,'HOENN','NORMAL');
INSERT INTO Pokemon_Gym VALUES('Feather Badge',456445,'HOENN','FLYING');
INSERT INTO Pokemon_Gym VALUES('Mind Badge',983453,'HOENN','PSYCHIC');
INSERT INTO Pokemon_Gym VALUES('Rain Badge',376453,'HOENN','WATER');
INSERT INTO Pokemon_Gym VALUES('Boulder Badge',567345,'KANTO','ROCK');
INSERT INTO Pokemon_Gym VALUES('Cascade Badge',871293,'KANTO','WATER');
INSERT INTO Pokemon_Gym VALUES('Thunder Badge',378102,'KANTO','ELECTRIC');
INSERT INTO Pokemon_Gym VALUES('Rainbow Badge',953137,'KANTO','GRASS');
INSERT INTO Pokemon_Gym VALUES('Soul Badge',763492,'KANTO','POISON');
INSERT INTO Pokemon_Gym VALUES('Marsh Badge',452945,'KANTO','PSYCHIC');
INSERT INTO Pokemon_Gym VALUES('Valcano Badge',763489,'KANTO','FIRE');
INSERT INTO Pokemon_Gym VALUES('Earth Badge',453267,'KANTO','GROUND');