\c pokedabe
DELETE FROM Attacks_Learnt;
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Leech Seed',7);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Vine Whip',13);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Poison Powder',20);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Razor Leaf',27);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Growth',34);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Sleep Powder',41);
INSERT INTO Attacks_Learnt VALUES('Bulbasaur','Solar Beam',48);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Vine Whip',13);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Poison Powder',22);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Razor Leaf',30);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Growth',38);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Sleep Powder',46);
INSERT INTO Attacks_Learnt VALUES('Ivysaur','Solar Beam',54);
INSERT INTO Attacks_Learnt VALUES('Venusaur','Growth',43);
INSERT INTO Attacks_Learnt VALUES('Venusaur','Sleep Powder',55);
INSERT INTO Attacks_Learnt VALUES('Venusaur','Solar Beam',65);
INSERT INTO Attacks_Learnt VALUES('Charmander','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Charmander','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Charmander','Ember',9);
INSERT INTO Attacks_Learnt VALUES('Charmander','Leer',15);
INSERT INTO Attacks_Learnt VALUES('Charmander','Rage',22);
INSERT INTO Attacks_Learnt VALUES('Charmander','Slash',30);
INSERT INTO Attacks_Learnt VALUES('Charmander','Flamethrower',38);
INSERT INTO Attacks_Learnt VALUES('Charmander','Fire Spin',46);
INSERT INTO Attacks_Learnt VALUES('Charmeleon','Leer',15);
INSERT INTO Attacks_Learnt VALUES('Charmeleon','Rage',24);
INSERT INTO Attacks_Learnt VALUES('Charmeleon','Slash',33);
INSERT INTO Attacks_Learnt VALUES('Charmeleon','Flamethrower',42);
INSERT INTO Attacks_Learnt VALUES('Charmeleon','Fire Spin',56);
INSERT INTO Attacks_Learnt VALUES('Charizard','Slash',36);
INSERT INTO Attacks_Learnt VALUES('Charizard','Flamethrower',46);
INSERT INTO Attacks_Learnt VALUES('Charizard','Fire Spin',55);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Tail Whip',0);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Bubble',8);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Water Gun',15);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Bite',22);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Withdraw',28);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Skull Bash',35);
INSERT INTO Attacks_Learnt VALUES('Squirtle','Hydro Pump',42);
INSERT INTO Attacks_Learnt VALUES('Wartortle','Water Gun',15);
INSERT INTO Attacks_Learnt VALUES('Wartortle','Bite',24);
INSERT INTO Attacks_Learnt VALUES('Wartortle','Withdraw',31);
INSERT INTO Attacks_Learnt VALUES('Wartortle','Skull Bash',39);
INSERT INTO Attacks_Learnt VALUES('Wartortle','Hydro Pump',47);
INSERT INTO Attacks_Learnt VALUES('Blastoise','Bite',24);
INSERT INTO Attacks_Learnt VALUES('Blastoise','Withdraw',31);
INSERT INTO Attacks_Learnt VALUES('Blastoise','Skull Bash',42);
INSERT INTO Attacks_Learnt VALUES('Blastoise','Hydro Pump',52);
INSERT INTO Attacks_Learnt VALUES('Caterpie','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Caterpie','String Shot',0);
INSERT INTO Attacks_Learnt VALUES('Metapod','Harden',0);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Confusion',12);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Poison Powder',15);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Stun Spore',16);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Sleep Powder',17);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Supersonic',21);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Whirlwind',26);
INSERT INTO Attacks_Learnt VALUES('Butterfree','Psybeam',32);
INSERT INTO Attacks_Learnt VALUES('Weedle','Poison Sting',0);
INSERT INTO Attacks_Learnt VALUES('Weedle','String Shot',0);
INSERT INTO Attacks_Learnt VALUES('Kakuna','Harden',0);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Fury Attack',12);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Focus Energy',16);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Twineedle',20);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Rage',25);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Pin Missile',30);
INSERT INTO Attacks_Learnt VALUES('Beedrill','Agility',35);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Gust',0);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Sand Attack',5);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Quick Attack',12);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Whirlwind',19);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Wing Attack',28);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Agility',36);
INSERT INTO Attacks_Learnt VALUES('Pidgey','Mirror Move',44);
INSERT INTO Attacks_Learnt VALUES('Pidgeotto','Whirlwind',21);
INSERT INTO Attacks_Learnt VALUES('Pidgeotto','Wing Attack',31);
INSERT INTO Attacks_Learnt VALUES('Pidgeotto','Agility',40);
INSERT INTO Attacks_Learnt VALUES('Pidgeotto','Mirror Move',49);
INSERT INTO Attacks_Learnt VALUES('Pidgeot','Agility',44);
INSERT INTO Attacks_Learnt VALUES('Pidgeot','Mirror Move',54);
INSERT INTO Attacks_Learnt VALUES('Rattata','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Rattata','Tail Whip',0);
INSERT INTO Attacks_Learnt VALUES('Rattata','Quick Attack',7);
INSERT INTO Attacks_Learnt VALUES('Rattata','Hyper Fang',14);
INSERT INTO Attacks_Learnt VALUES('Rattata','Focus Energy',23);
INSERT INTO Attacks_Learnt VALUES('Rattata','Super Fang',34);
INSERT INTO Attacks_Learnt VALUES('Raticate','Hyper Fang',14);
INSERT INTO Attacks_Learnt VALUES('Raticate','Focus Energy',27);
INSERT INTO Attacks_Learnt VALUES('Raticate','Super Fang',41);
INSERT INTO Attacks_Learnt VALUES('Spearow','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Spearow','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Spearow','Leer',9);
INSERT INTO Attacks_Learnt VALUES('Spearow','Fury Attack',15);
INSERT INTO Attacks_Learnt VALUES('Spearow','Mirror Move',22);
INSERT INTO Attacks_Learnt VALUES('Spearow','Drill Peck',29);
INSERT INTO Attacks_Learnt VALUES('Spearow','Agility',36);
INSERT INTO Attacks_Learnt VALUES('Fearow','Mirror Move',25);
INSERT INTO Attacks_Learnt VALUES('Fearow','Drill Peck',34);
INSERT INTO Attacks_Learnt VALUES('Fearow','Agility',43);
INSERT INTO Attacks_Learnt VALUES('Ekans','Wrap',0);
INSERT INTO Attacks_Learnt VALUES('Ekans','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Ekans','Poison Sting',10);
INSERT INTO Attacks_Learnt VALUES('Ekans','Bite',17);
INSERT INTO Attacks_Learnt VALUES('Ekans','Glare',24);
INSERT INTO Attacks_Learnt VALUES('Ekans','Screech',31);
INSERT INTO Attacks_Learnt VALUES('Ekans','Acid',38);
INSERT INTO Attacks_Learnt VALUES('Arbok','Bite',17);
INSERT INTO Attacks_Learnt VALUES('Arbok','Glare',27);
INSERT INTO Attacks_Learnt VALUES('Arbok','Screech',36);
INSERT INTO Attacks_Learnt VALUES('Arbok','Acid',47);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Thunder Shock',0);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Thunder Wave',9);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Quick Attack',16);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Swift',26);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Agility',33);
INSERT INTO Attacks_Learnt VALUES('Pikachu','Thunder',43);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Sand Attack',10);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Slash',17);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Poison Sting',24);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Swift',31);
INSERT INTO Attacks_Learnt VALUES('Sandshrew','Fury Swipes',38);
INSERT INTO Attacks_Learnt VALUES('Sandslash','Poison Sting',27);
INSERT INTO Attacks_Learnt VALUES('Sandslash','Swift',36);
INSERT INTO Attacks_Learnt VALUES('Sandslash','Fury Swipes',47);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Scratch',8);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Poison Sting',14);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Tail Whip',21);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Bite',29);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Fury Swipes',36);
INSERT INTO Attacks_Learnt VALUES('Nidoran♀','Double Kick',43);
INSERT INTO Attacks_Learnt VALUES('Nidorina','Poison Sting',14);
INSERT INTO Attacks_Learnt VALUES('Nidorina','Tail Whip',23);
INSERT INTO Attacks_Learnt VALUES('Nidorina','Bite',32);
INSERT INTO Attacks_Learnt VALUES('Nidorina','Fury Swipes',41);
INSERT INTO Attacks_Learnt VALUES('Nidorina','Double Kick',50);
INSERT INTO Attacks_Learnt VALUES('Nidoqueen','Poison Sting',14);
INSERT INTO Attacks_Learnt VALUES('Nidoqueen','Body Slam',23);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Horn Attack',8);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Poison Sting',14);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Focus Energy',21);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Fury Attack',29);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Horn Drill',36);
INSERT INTO Attacks_Learnt VALUES('Nidoran♂','Double Kick',43);
INSERT INTO Attacks_Learnt VALUES('Nidorino','Focus Energy',23);
INSERT INTO Attacks_Learnt VALUES('Nidorino','Fury Attack',32);
INSERT INTO Attacks_Learnt VALUES('Nidorino','Horn Drill',41);
INSERT INTO Attacks_Learnt VALUES('Nidorino','Double Kick',50);
INSERT INTO Attacks_Learnt VALUES('Nidoking','Thrash',23);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Sing',13);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Double Slap',18);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Minimize',24);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Metronome',31);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Defense Curl',39);
INSERT INTO Attacks_Learnt VALUES('Clefairy','Light Screen',48);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Ember',0);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Tail Whip',0);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Quick Attack',16);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Roar',21);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Confuse Ray',28);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Flamethrower',35);
INSERT INTO Attacks_Learnt VALUES('Vulpix','Fire Spin',42);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Sing',0);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Pound',9);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Disable',14);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Defense Curl',19);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Double Slap',24);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Rest',29);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Body Slam',34);
INSERT INTO Attacks_Learnt VALUES('Jigglypuff','Double-Edge',39);
INSERT INTO Attacks_Learnt VALUES('Zubat','Leech Life',0);
INSERT INTO Attacks_Learnt VALUES('Zubat','Supersonic',10);
INSERT INTO Attacks_Learnt VALUES('Zubat','Bite',15);
INSERT INTO Attacks_Learnt VALUES('Zubat','Confuse Ray',21);
INSERT INTO Attacks_Learnt VALUES('Zubat','Wing Attack',28);
INSERT INTO Attacks_Learnt VALUES('Zubat','Haze',36);
INSERT INTO Attacks_Learnt VALUES('Golbat','Wing Attack',32);
INSERT INTO Attacks_Learnt VALUES('Golbat','Haze',43);
INSERT INTO Attacks_Learnt VALUES('Oddish','Absorb',0);
INSERT INTO Attacks_Learnt VALUES('Oddish','Poison Powder',15);
INSERT INTO Attacks_Learnt VALUES('Oddish','Stun Spore',17);
INSERT INTO Attacks_Learnt VALUES('Oddish','Sleep Powder',19);
INSERT INTO Attacks_Learnt VALUES('Oddish','Acid',24);
INSERT INTO Attacks_Learnt VALUES('Oddish','Petal Dance',33);
INSERT INTO Attacks_Learnt VALUES('Oddish','Solar Beam',46);
INSERT INTO Attacks_Learnt VALUES('Gloom','Acid',28);
INSERT INTO Attacks_Learnt VALUES('Gloom','Petal Dance',38);
INSERT INTO Attacks_Learnt VALUES('Gloom','Solar Beam',52);
INSERT INTO Attacks_Learnt VALUES('Paras','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Paras','Stun Spore',13);
INSERT INTO Attacks_Learnt VALUES('Paras','Leech Life',20);
INSERT INTO Attacks_Learnt VALUES('Paras','Spore',27);
INSERT INTO Attacks_Learnt VALUES('Paras','Slash',34);
INSERT INTO Attacks_Learnt VALUES('Paras','Growth',41);
INSERT INTO Attacks_Learnt VALUES('Parasect','Spore',30);
INSERT INTO Attacks_Learnt VALUES('Parasect','Slash',39);
INSERT INTO Attacks_Learnt VALUES('Parasect','Growth',48);
INSERT INTO Attacks_Learnt VALUES('Venonat','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Venonat','Disable',0);
INSERT INTO Attacks_Learnt VALUES('Venonat','Poison Powder',24);
INSERT INTO Attacks_Learnt VALUES('Venonat','Leech Life',27);
INSERT INTO Attacks_Learnt VALUES('Venonat','Stun Spore',30);
INSERT INTO Attacks_Learnt VALUES('Venonat','Psybeam',35);
INSERT INTO Attacks_Learnt VALUES('Venonat','Sleep Powder',38);
INSERT INTO Attacks_Learnt VALUES('Venonat','Psychic',43);
INSERT INTO Attacks_Learnt VALUES('Venomoth','Psybeam',38);
INSERT INTO Attacks_Learnt VALUES('Venomoth','Sleep Powder',43);
INSERT INTO Attacks_Learnt VALUES('Venomoth','Psychic',50);
INSERT INTO Attacks_Learnt VALUES('Diglett','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Diglett','Growl',15);
INSERT INTO Attacks_Learnt VALUES('Diglett','Dig',19);
INSERT INTO Attacks_Learnt VALUES('Diglett','Sand Attack',24);
INSERT INTO Attacks_Learnt VALUES('Diglett','Slash',31);
INSERT INTO Attacks_Learnt VALUES('Diglett','Earthquake',40);
INSERT INTO Attacks_Learnt VALUES('Dugtrio','Slash',35);
INSERT INTO Attacks_Learnt VALUES('Dugtrio','Earthquake',47);
INSERT INTO Attacks_Learnt VALUES('Meowth','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Meowth','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Meowth','Bite',12);
INSERT INTO Attacks_Learnt VALUES('Meowth','Pay Day',17);
INSERT INTO Attacks_Learnt VALUES('Meowth','Screech',24);
INSERT INTO Attacks_Learnt VALUES('Meowth','Fury Swipes',33);
INSERT INTO Attacks_Learnt VALUES('Meowth','Slash',44);
INSERT INTO Attacks_Learnt VALUES('Persian','Fury Swipes',37);
INSERT INTO Attacks_Learnt VALUES('Persian','Slash',51);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Tail Whip',28);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Disable',31);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Confusion',36);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Fury Swipes',43);
INSERT INTO Attacks_Learnt VALUES('Psyduck','Hydro Pump',52);
INSERT INTO Attacks_Learnt VALUES('Golduck','Confusion',39);
INSERT INTO Attacks_Learnt VALUES('Golduck','Fury Swipes',48);
INSERT INTO Attacks_Learnt VALUES('Golduck','Hydro Pump',59);
INSERT INTO Attacks_Learnt VALUES('Mankey','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Mankey','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Mankey','Karate Chop',15);
INSERT INTO Attacks_Learnt VALUES('Mankey','Fury Attack',21);
INSERT INTO Attacks_Learnt VALUES('Mankey','Focus Energy',27);
INSERT INTO Attacks_Learnt VALUES('Mankey','Seismic Toss',33);
INSERT INTO Attacks_Learnt VALUES('Mankey','Thrash',39);
INSERT INTO Attacks_Learnt VALUES('Primeape','Seismic Toss',37);
INSERT INTO Attacks_Learnt VALUES('Primeape','Thrash',46);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Bite',0);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Roar',0);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Ember',18);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Leer',23);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Take Down',30);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Agility',39);
INSERT INTO Attacks_Learnt VALUES('Growlithe','Flamethrower',50);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Bubble',0);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Hypnosis',16);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Water Gun',19);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Double Slap',25);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Body Slam',31);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Amnesia',38);
INSERT INTO Attacks_Learnt VALUES('Poliwag','Hydro Pump',45);
INSERT INTO Attacks_Learnt VALUES('Poliwhirl','Double Slap',26);
INSERT INTO Attacks_Learnt VALUES('Poliwhirl','Body Slam',33);
INSERT INTO Attacks_Learnt VALUES('Poliwhirl','Amnesia',41);
INSERT INTO Attacks_Learnt VALUES('Poliwhirl','Hydro Pump',49);
INSERT INTO Attacks_Learnt VALUES('Abra','Teleport',0);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Teleport',0);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Confusion',0);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Disable',20);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Psybeam',27);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Recover',31);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Psychic',38);
INSERT INTO Attacks_Learnt VALUES('Kadabra','Reflect',42);
INSERT INTO Attacks_Learnt VALUES('Alakazam','Disable',20);
INSERT INTO Attacks_Learnt VALUES('Alakazam','Psybeam',27);
INSERT INTO Attacks_Learnt VALUES('Alakazam','Recover',31);
INSERT INTO Attacks_Learnt VALUES('Alakazam','Psychic',38);
INSERT INTO Attacks_Learnt VALUES('Alakazam','Reflect',42);
INSERT INTO Attacks_Learnt VALUES('Machop','Karate Chop',0);
INSERT INTO Attacks_Learnt VALUES('Machop','Low Kick',20);
INSERT INTO Attacks_Learnt VALUES('Machop','Leer',25);
INSERT INTO Attacks_Learnt VALUES('Machop','Focus Energy',32);
INSERT INTO Attacks_Learnt VALUES('Machop','Seismic Toss',39);
INSERT INTO Attacks_Learnt VALUES('Machop','Submission',46);
INSERT INTO Attacks_Learnt VALUES('Machoke','Focus Energy',36);
INSERT INTO Attacks_Learnt VALUES('Machoke','Seismic Toss',44);
INSERT INTO Attacks_Learnt VALUES('Machoke','Submission',52);
INSERT INTO Attacks_Learnt VALUES('Machamp','Focus Energy',36);
INSERT INTO Attacks_Learnt VALUES('Machamp','Seismic Toss',44);
INSERT INTO Attacks_Learnt VALUES('Machamp','Submission',52);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Vine Whip',0);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Growth',0);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Wrap',13);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Poison Powder',15);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Sleep Powder',18);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Stun Spore',21);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Acid',26);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Razor Leaf',33);
INSERT INTO Attacks_Learnt VALUES('Bellsprout','Slam',42);
INSERT INTO Attacks_Learnt VALUES('Weepinbell','Stun Spore',23);
INSERT INTO Attacks_Learnt VALUES('Weepinbell','Acid',29);
INSERT INTO Attacks_Learnt VALUES('Weepinbell','Razor Leaf',38);
INSERT INTO Attacks_Learnt VALUES('Weepinbell','Slam',49);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Acid',0);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Supersonic',7);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Wrap',13);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Poison Sting',18);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Water Gun',22);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Constrict',27);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Barrier',33);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Screech',40);
INSERT INTO Attacks_Learnt VALUES('Tentacool','Hydro Pump',48);
INSERT INTO Attacks_Learnt VALUES('Tentacruel','Barrier',35);
INSERT INTO Attacks_Learnt VALUES('Tentacruel','Screech',43);
INSERT INTO Attacks_Learnt VALUES('Tentacruel','Hydro Pump',50);
INSERT INTO Attacks_Learnt VALUES('Geodude','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Geodude','Defense Curl',11);
INSERT INTO Attacks_Learnt VALUES('Geodude','Rock Throw',16);
INSERT INTO Attacks_Learnt VALUES('Geodude','Self-Destruct',21);
INSERT INTO Attacks_Learnt VALUES('Geodude','Harden',26);
INSERT INTO Attacks_Learnt VALUES('Geodude','Earthquake',31);
INSERT INTO Attacks_Learnt VALUES('Geodude','Explosion',36);
INSERT INTO Attacks_Learnt VALUES('Graveler','Harden',29);
INSERT INTO Attacks_Learnt VALUES('Graveler','Earthquake',36);
INSERT INTO Attacks_Learnt VALUES('Graveler','Explosion',43);
INSERT INTO Attacks_Learnt VALUES('Golem','Harden',29);
INSERT INTO Attacks_Learnt VALUES('Golem','Earthquake',36);
INSERT INTO Attacks_Learnt VALUES('Golem','Explosion',43);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Ember',0);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Tail Whip',30);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Stomp',32);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Growl',35);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Fire Spin',39);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Take Down',43);
INSERT INTO Attacks_Learnt VALUES('Ponyta','Agility',48);
INSERT INTO Attacks_Learnt VALUES('Rapidash','Take Down',47);
INSERT INTO Attacks_Learnt VALUES('Rapidash','Agility',55);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Confusion',0);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Disable',18);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Headbutt',22);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Growl',27);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Water Gun',33);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Amnesia',40);
INSERT INTO Attacks_Learnt VALUES('Slowpoke','Psychic',48);
INSERT INTO Attacks_Learnt VALUES('Slowbro','Amnesia',44);
INSERT INTO Attacks_Learnt VALUES('Slowbro','Psychic',55);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Sonic Boom',21);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Thunder Shock',25);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Supersonic',29);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Thunder Wave',35);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Swift',41);
INSERT INTO Attacks_Learnt VALUES('Magnemite','Screech',47);
INSERT INTO Attacks_Learnt VALUES('Magneton','Thunder Wave',38);
INSERT INTO Attacks_Learnt VALUES('Magneton','Swift',46);
INSERT INTO Attacks_Learnt VALUES('Magneton','Screech',54);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Sand Attack',0);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Leer',7);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Fury Attack',15);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Swords Dance',23);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Agility',31);
INSERT INTO Attacks_Learnt VALUES('Farfetchd','Slash',39);
INSERT INTO Attacks_Learnt VALUES('Doduo','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Doduo','Growl',20);
INSERT INTO Attacks_Learnt VALUES('Doduo','Fury Attack',24);
INSERT INTO Attacks_Learnt VALUES('Doduo','Drill Peck',30);
INSERT INTO Attacks_Learnt VALUES('Doduo','Rage',36);
INSERT INTO Attacks_Learnt VALUES('Doduo','Tri Attack',40);
INSERT INTO Attacks_Learnt VALUES('Doduo','Agility',44);
INSERT INTO Attacks_Learnt VALUES('Dodrio','Rage',39);
INSERT INTO Attacks_Learnt VALUES('Dodrio','Tri Attack',45);
INSERT INTO Attacks_Learnt VALUES('Dodrio','Agility',51);
INSERT INTO Attacks_Learnt VALUES('Seel','Headbutt',0);
INSERT INTO Attacks_Learnt VALUES('Seel','Growl',30);
INSERT INTO Attacks_Learnt VALUES('Seel','Aurora Beam',35);
INSERT INTO Attacks_Learnt VALUES('Seel','Rest',40);
INSERT INTO Attacks_Learnt VALUES('Seel','Take Down',45);
INSERT INTO Attacks_Learnt VALUES('Seel','Ice Beam',50);
INSERT INTO Attacks_Learnt VALUES('Dewgong','Aurora Beam',35);
INSERT INTO Attacks_Learnt VALUES('Dewgong','Rest',44);
INSERT INTO Attacks_Learnt VALUES('Dewgong','Take Down',50);
INSERT INTO Attacks_Learnt VALUES('Dewgong','Ice Beam',56);
INSERT INTO Attacks_Learnt VALUES('Grimer','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Grimer','Disable',0);
INSERT INTO Attacks_Learnt VALUES('Grimer','Poison Gas',30);
INSERT INTO Attacks_Learnt VALUES('Grimer','Minimize',33);
INSERT INTO Attacks_Learnt VALUES('Grimer','Sludge',37);
INSERT INTO Attacks_Learnt VALUES('Grimer','Harden',42);
INSERT INTO Attacks_Learnt VALUES('Grimer','Screech',48);
INSERT INTO Attacks_Learnt VALUES('Grimer','Acid Armor',55);
INSERT INTO Attacks_Learnt VALUES('Muk','Harden',45);
INSERT INTO Attacks_Learnt VALUES('Muk','Screech',53);
INSERT INTO Attacks_Learnt VALUES('Muk','Acid Armor',60);
INSERT INTO Attacks_Learnt VALUES('Shellder','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Shellder','Withdraw',0);
INSERT INTO Attacks_Learnt VALUES('Shellder','Supersonic',18);
INSERT INTO Attacks_Learnt VALUES('Shellder','Clamp',23);
INSERT INTO Attacks_Learnt VALUES('Shellder','Aurora Beam',30);
INSERT INTO Attacks_Learnt VALUES('Shellder','Leer',39);
INSERT INTO Attacks_Learnt VALUES('Shellder','Ice Beam',50);
INSERT INTO Attacks_Learnt VALUES('Cloyster','Spike Cannon',50);
INSERT INTO Attacks_Learnt VALUES('Gastly','Lick',0);
INSERT INTO Attacks_Learnt VALUES('Gastly','Confuse Ray',0);
INSERT INTO Attacks_Learnt VALUES('Gastly','Night Shade',0);
INSERT INTO Attacks_Learnt VALUES('Gastly','Hypnosis',27);
INSERT INTO Attacks_Learnt VALUES('Gastly','Dream Eater',35);
INSERT INTO Attacks_Learnt VALUES('Haunter','Hypnosis',29);
INSERT INTO Attacks_Learnt VALUES('Haunter','Dream Eater',38);
INSERT INTO Attacks_Learnt VALUES('Gengar','Hypnosis',29);
INSERT INTO Attacks_Learnt VALUES('Gengar','Dream Eater',38);
INSERT INTO Attacks_Learnt VALUES('Onix','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Onix','Screech',0);
INSERT INTO Attacks_Learnt VALUES('Onix','Bind',15);
INSERT INTO Attacks_Learnt VALUES('Onix','Rock Throw',19);
INSERT INTO Attacks_Learnt VALUES('Onix','Rage',25);
INSERT INTO Attacks_Learnt VALUES('Onix','Slam',33);
INSERT INTO Attacks_Learnt VALUES('Onix','Harden',43);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Hypnosis',0);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Disable',12);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Confusion',17);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Headbutt',24);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Poison Gas',29);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Psychic',32);
INSERT INTO Attacks_Learnt VALUES('Drowzee','Meditate',37);
INSERT INTO Attacks_Learnt VALUES('Hypno','Poison Gas',33);
INSERT INTO Attacks_Learnt VALUES('Hypno','Psychic',37);
INSERT INTO Attacks_Learnt VALUES('Hypno','Meditate',43);
INSERT INTO Attacks_Learnt VALUES('Krabby','Bubble',0);
INSERT INTO Attacks_Learnt VALUES('Krabby','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Krabby','Vice Grip',20);
INSERT INTO Attacks_Learnt VALUES('Krabby','Guillotine',25);
INSERT INTO Attacks_Learnt VALUES('Krabby','Stomp',30);
INSERT INTO Attacks_Learnt VALUES('Krabby','Crabhammer',35);
INSERT INTO Attacks_Learnt VALUES('Krabby','Harden',40);
INSERT INTO Attacks_Learnt VALUES('Kingler','Stomp',34);
INSERT INTO Attacks_Learnt VALUES('Kingler','Crabhammer',42);
INSERT INTO Attacks_Learnt VALUES('Kingler','Harden',49);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Screech',0);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Sonic Boom',17);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Self-Destruct',22);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Light Screen',29);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Swift',36);
INSERT INTO Attacks_Learnt VALUES('Voltorb','Explosion',43);
INSERT INTO Attacks_Learnt VALUES('Electrode','Swift',40);
INSERT INTO Attacks_Learnt VALUES('Electrode','Explosion',50);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Barrage',0);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Hypnosis',0);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Reflect',25);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Leech Seed',28);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Stun Spore',32);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Poison Powder',37);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Solar Beam',42);
INSERT INTO Attacks_Learnt VALUES('Exeggcute','Sleep Powder',48);
INSERT INTO Attacks_Learnt VALUES('Exeggutor','Stomp',28);
INSERT INTO Attacks_Learnt VALUES('Cubone','Bone Club',0);
INSERT INTO Attacks_Learnt VALUES('Cubone','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Cubone','Leer',25);
INSERT INTO Attacks_Learnt VALUES('Cubone','Focus Energy',31);
INSERT INTO Attacks_Learnt VALUES('Cubone','Thrash',38);
INSERT INTO Attacks_Learnt VALUES('Cubone','Bonemerang',43);
INSERT INTO Attacks_Learnt VALUES('Cubone','Rage',46);
INSERT INTO Attacks_Learnt VALUES('Marowak','Focus Energy',33);
INSERT INTO Attacks_Learnt VALUES('Marowak','Thrash',41);
INSERT INTO Attacks_Learnt VALUES('Marowak','Bonemerang',48);
INSERT INTO Attacks_Learnt VALUES('Marowak','Rage',55);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Double Kick',0);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Meditate',0);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Rolling Kick',33);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Jump Kick',38);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Focus Energy',43);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','High Jump Kick',48);
INSERT INTO Attacks_Learnt VALUES('Hitmonlee','Mega Kick',53);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Comet Punch',0);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Agility',0);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Fire Punch',33);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Ice Punch',38);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Thunder Punch',43);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Mega Punch',48);
INSERT INTO Attacks_Learnt VALUES('Hitmonchan','Counter',53);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Wrap',0);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Supersonic',0);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Stomp',7);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Disable',15);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Defense Curl',23);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Slam',31);
INSERT INTO Attacks_Learnt VALUES('Lickitung','Screech',39);
INSERT INTO Attacks_Learnt VALUES('Koffing','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Koffing','Smog',0);
INSERT INTO Attacks_Learnt VALUES('Koffing','Sludge',32);
INSERT INTO Attacks_Learnt VALUES('Koffing','Smokescreen',37);
INSERT INTO Attacks_Learnt VALUES('Koffing','Self-Destruct',40);
INSERT INTO Attacks_Learnt VALUES('Koffing','Haze',45);
INSERT INTO Attacks_Learnt VALUES('Koffing','Explosion',48);
INSERT INTO Attacks_Learnt VALUES('Weezing','Smokescreen',39);
INSERT INTO Attacks_Learnt VALUES('Weezing','Self-Destruct',43);
INSERT INTO Attacks_Learnt VALUES('Weezing','Haze',49);
INSERT INTO Attacks_Learnt VALUES('Weezing','Explosion',53);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Horn Attack',0);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Stomp',30);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Tail Whip',35);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Fury Attack',40);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Horn Drill',45);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Leer',50);
INSERT INTO Attacks_Learnt VALUES('Rhyhorn','Take Down',55);
INSERT INTO Attacks_Learnt VALUES('Rhydon','Horn Drill',48);
INSERT INTO Attacks_Learnt VALUES('Rhydon','Leer',55);
INSERT INTO Attacks_Learnt VALUES('Rhydon','Take Down',64);
INSERT INTO Attacks_Learnt VALUES('Chansey','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Chansey','Double Slap',0);
INSERT INTO Attacks_Learnt VALUES('Chansey','Sing',24);
INSERT INTO Attacks_Learnt VALUES('Chansey','Growl',30);
INSERT INTO Attacks_Learnt VALUES('Chansey','Minimize',38);
INSERT INTO Attacks_Learnt VALUES('Chansey','Defense Curl',44);
INSERT INTO Attacks_Learnt VALUES('Chansey','Light Screen',48);
INSERT INTO Attacks_Learnt VALUES('Chansey','Double-Edge',54);
INSERT INTO Attacks_Learnt VALUES('Tangela','Constrict',0);
INSERT INTO Attacks_Learnt VALUES('Tangela','Bind',0);
INSERT INTO Attacks_Learnt VALUES('Tangela','Absorb',29);
INSERT INTO Attacks_Learnt VALUES('Tangela','Poison Powder',32);
INSERT INTO Attacks_Learnt VALUES('Tangela','Stun Spore',36);
INSERT INTO Attacks_Learnt VALUES('Tangela','Sleep Powder',39);
INSERT INTO Attacks_Learnt VALUES('Tangela','Slam',45);
INSERT INTO Attacks_Learnt VALUES('Tangela','Growth',49);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Comet Punch',0);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Rage',0);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Bite',26);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Tail Whip',31);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Mega Punch',36);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Leer',41);
INSERT INTO Attacks_Learnt VALUES('Kangaskhan','Dizzy Punch',46);
INSERT INTO Attacks_Learnt VALUES('Horsea','Bubble',0);
INSERT INTO Attacks_Learnt VALUES('Horsea','Smokescreen',19);
INSERT INTO Attacks_Learnt VALUES('Horsea','Leer',24);
INSERT INTO Attacks_Learnt VALUES('Horsea','Water Gun',30);
INSERT INTO Attacks_Learnt VALUES('Horsea','Agility',37);
INSERT INTO Attacks_Learnt VALUES('Horsea','Hydro Pump',45);
INSERT INTO Attacks_Learnt VALUES('Seadra','Agility',41);
INSERT INTO Attacks_Learnt VALUES('Seadra','Hydro Pump',52);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Tail Whip',0);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Supersonic',19);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Horn Attack',24);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Fury Attack',30);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Waterfall',37);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Horn Drill',45);
INSERT INTO Attacks_Learnt VALUES('Goldeen','Agility',54);
INSERT INTO Attacks_Learnt VALUES('Seaking','Waterfall',39);
INSERT INTO Attacks_Learnt VALUES('Seaking','Horn Drill',48);
INSERT INTO Attacks_Learnt VALUES('Seaking','Agility',54);
INSERT INTO Attacks_Learnt VALUES('Staryu','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Staryu','Water Gun',17);
INSERT INTO Attacks_Learnt VALUES('Staryu','Harden',22);
INSERT INTO Attacks_Learnt VALUES('Staryu','Recover',27);
INSERT INTO Attacks_Learnt VALUES('Staryu','Swift',32);
INSERT INTO Attacks_Learnt VALUES('Staryu','Minimize',37);
INSERT INTO Attacks_Learnt VALUES('Staryu','Light Screen',42);
INSERT INTO Attacks_Learnt VALUES('Staryu','Hydro Pump',47);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Confusion',0);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Barrier',0);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Light Screen',23);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Double Slap',31);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Meditate',39);
INSERT INTO Attacks_Learnt VALUES('Mr. Mime','Substitute',47);
INSERT INTO Attacks_Learnt VALUES('Scyther','Quick Attack',0);
INSERT INTO Attacks_Learnt VALUES('Scyther','Leer',17);
INSERT INTO Attacks_Learnt VALUES('Scyther','Focus Energy',20);
INSERT INTO Attacks_Learnt VALUES('Scyther','Double Team',24);
INSERT INTO Attacks_Learnt VALUES('Scyther','Slash',29);
INSERT INTO Attacks_Learnt VALUES('Scyther','Swords Dance',35);
INSERT INTO Attacks_Learnt VALUES('Scyther','Agility',42);
INSERT INTO Attacks_Learnt VALUES('Jynx','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Jynx','Lovely Kiss',0);
INSERT INTO Attacks_Learnt VALUES('Jynx','Sing',15);
INSERT INTO Attacks_Learnt VALUES('Jynx','Double Slap',23);
INSERT INTO Attacks_Learnt VALUES('Jynx','Ice Punch',31);
INSERT INTO Attacks_Learnt VALUES('Jynx','Meditate',39);
INSERT INTO Attacks_Learnt VALUES('Jynx','Blizzard',47);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Quick Attack',0);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Thunder Shock',34);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Screech',37);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Thunder Punch',42);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Light Screen',49);
INSERT INTO Attacks_Learnt VALUES('Electabuzz','Thunder',54);
INSERT INTO Attacks_Learnt VALUES('Magmar','Ember',0);
INSERT INTO Attacks_Learnt VALUES('Magmar','Leer',36);
INSERT INTO Attacks_Learnt VALUES('Magmar','Confuse Ray',39);
INSERT INTO Attacks_Learnt VALUES('Magmar','Fire Punch',43);
INSERT INTO Attacks_Learnt VALUES('Magmar','Smokescreen',48);
INSERT INTO Attacks_Learnt VALUES('Magmar','Smog',52);
INSERT INTO Attacks_Learnt VALUES('Magmar','Flamethrower',55);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Vice Grip',0);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Seismic Toss',25);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Guillotine',30);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Focus Energy',36);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Harden',43);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Slash',49);
INSERT INTO Attacks_Learnt VALUES('Pinsir','Swords Dance',54);
INSERT INTO Attacks_Learnt VALUES('Tauros','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Tauros','Stomp',21);
INSERT INTO Attacks_Learnt VALUES('Tauros','Tail Whip',28);
INSERT INTO Attacks_Learnt VALUES('Tauros','Leer',35);
INSERT INTO Attacks_Learnt VALUES('Tauros','Rage',44);
INSERT INTO Attacks_Learnt VALUES('Tauros','Take Down',51);
INSERT INTO Attacks_Learnt VALUES('Magikarp','Splash',0);
INSERT INTO Attacks_Learnt VALUES('Magikarp','Tackle',15);
INSERT INTO Attacks_Learnt VALUES('Gyarados','Bite',20);
INSERT INTO Attacks_Learnt VALUES('Gyarados','Dragon Rage',25);
INSERT INTO Attacks_Learnt VALUES('Gyarados','Leer',32);
INSERT INTO Attacks_Learnt VALUES('Gyarados','Hydro Pump',41);
INSERT INTO Attacks_Learnt VALUES('Gyarados','Hyper Beam',52);
INSERT INTO Attacks_Learnt VALUES('Lapras','Water Gun',0);
INSERT INTO Attacks_Learnt VALUES('Lapras','Growl',0);
INSERT INTO Attacks_Learnt VALUES('Lapras','Sing',16);
INSERT INTO Attacks_Learnt VALUES('Lapras','Mist',20);
INSERT INTO Attacks_Learnt VALUES('Lapras','Body Slam',25);
INSERT INTO Attacks_Learnt VALUES('Lapras','Confuse Ray',31);
INSERT INTO Attacks_Learnt VALUES('Lapras','Ice Beam',38);
INSERT INTO Attacks_Learnt VALUES('Lapras','Hydro Pump',46);
INSERT INTO Attacks_Learnt VALUES('Ditto','Transform',0);
INSERT INTO Attacks_Learnt VALUES('Eevee','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Eevee','Sand Attack',0);
INSERT INTO Attacks_Learnt VALUES('Eevee','Quick Attack',27);
INSERT INTO Attacks_Learnt VALUES('Eevee','Tail Whip',31);
INSERT INTO Attacks_Learnt VALUES('Eevee','Bite',37);
INSERT INTO Attacks_Learnt VALUES('Eevee','Take Down',45);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Quick Attack',27);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Water Gun',31);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Tail Whip',37);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Bite',40);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Acid Armor',42);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Haze',44);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Mist',48);
INSERT INTO Attacks_Learnt VALUES('Vaporeon','Hydro Pump',54);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Quick Attack',27);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Thunder Shock',31);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Tail Whip',37);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Thunder Wave',40);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Double Kick',42);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Agility',44);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Pin Missile',48);
INSERT INTO Attacks_Learnt VALUES('Jolteon','Thunder',54);
INSERT INTO Attacks_Learnt VALUES('Flareon','Quick Attack',27);
INSERT INTO Attacks_Learnt VALUES('Flareon','Ember',31);
INSERT INTO Attacks_Learnt VALUES('Flareon','Tail Whip',37);
INSERT INTO Attacks_Learnt VALUES('Flareon','Bite',40);
INSERT INTO Attacks_Learnt VALUES('Flareon','Leer',42);
INSERT INTO Attacks_Learnt VALUES('Flareon','Fire Spin',44);
INSERT INTO Attacks_Learnt VALUES('Flareon','Rage',48);
INSERT INTO Attacks_Learnt VALUES('Flareon','Flamethrower',54);
INSERT INTO Attacks_Learnt VALUES('Porygon','Tackle',0);
INSERT INTO Attacks_Learnt VALUES('Porygon','Sharpen',0);
INSERT INTO Attacks_Learnt VALUES('Porygon','Conversion',0);
INSERT INTO Attacks_Learnt VALUES('Porygon','Psybeam',23);
INSERT INTO Attacks_Learnt VALUES('Porygon','Recover',28);
INSERT INTO Attacks_Learnt VALUES('Porygon','Agility',35);
INSERT INTO Attacks_Learnt VALUES('Porygon','Tri Attack',42);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Water Gun',0);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Withdraw',0);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Horn Attack',34);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Leer',39);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Spike Cannon',46);
INSERT INTO Attacks_Learnt VALUES('Omanyte','Hydro Pump',53);
INSERT INTO Attacks_Learnt VALUES('Omastar','Spike Cannon',44);
INSERT INTO Attacks_Learnt VALUES('Omastar','Hydro Pump',49);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Scratch',0);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Harden',0);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Absorb',34);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Slash',39);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Leer',44);
INSERT INTO Attacks_Learnt VALUES('Kabuto','Hydro Pump',49);
INSERT INTO Attacks_Learnt VALUES('Kabutops','Leer',46);
INSERT INTO Attacks_Learnt VALUES('Kabutops','Hydro Pump',53);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Wing Attack',0);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Agility',0);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Supersonic',33);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Bite',38);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Take Down',45);
INSERT INTO Attacks_Learnt VALUES('Aerodactyl','Hyper Beam',54);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Headbutt',0);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Amnesia',0);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Rest',0);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Body Slam',35);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Harden',41);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Double-Edge',48);
INSERT INTO Attacks_Learnt VALUES('Snorlax','Hyper Beam',56);
INSERT INTO Attacks_Learnt VALUES('Articuno','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Articuno','Ice Beam',0);
INSERT INTO Attacks_Learnt VALUES('Articuno','Blizzard',51);
INSERT INTO Attacks_Learnt VALUES('Articuno','Agility',55);
INSERT INTO Attacks_Learnt VALUES('Articuno','Mist',60);
INSERT INTO Attacks_Learnt VALUES('Zapdos','Thunder Shock',0);
INSERT INTO Attacks_Learnt VALUES('Zapdos','Drill Peck',0);
INSERT INTO Attacks_Learnt VALUES('Zapdos','Thunder',51);
INSERT INTO Attacks_Learnt VALUES('Zapdos','Agility',55);
INSERT INTO Attacks_Learnt VALUES('Zapdos','Light Screen',60);
INSERT INTO Attacks_Learnt VALUES('Moltres','Peck',0);
INSERT INTO Attacks_Learnt VALUES('Moltres','Fire Spin',0);
INSERT INTO Attacks_Learnt VALUES('Moltres','Leer',51);
INSERT INTO Attacks_Learnt VALUES('Moltres','Agility',55);
INSERT INTO Attacks_Learnt VALUES('Moltres','Sky Attack',60);
INSERT INTO Attacks_Learnt VALUES('Dratini','Wrap',0);
INSERT INTO Attacks_Learnt VALUES('Dratini','Leer',0);
INSERT INTO Attacks_Learnt VALUES('Dratini','Thunder Wave',10);
INSERT INTO Attacks_Learnt VALUES('Dratini','Agility',20);
INSERT INTO Attacks_Learnt VALUES('Dratini','Slam',30);
INSERT INTO Attacks_Learnt VALUES('Dratini','Dragon Rage',40);
INSERT INTO Attacks_Learnt VALUES('Dratini','Hyper Beam',50);
INSERT INTO Attacks_Learnt VALUES('Dragonair','Slam',35);
INSERT INTO Attacks_Learnt VALUES('Dragonair','Dragon Rage',45);
INSERT INTO Attacks_Learnt VALUES('Dragonair','Hyper Beam',55);
INSERT INTO Attacks_Learnt VALUES('Dragonite','Hyper Beam',60);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Confusion',0);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Disable',0);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Swift',0);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Barrier',63);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Psychic',66);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Recover',70);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Mist',75);
INSERT INTO Attacks_Learnt VALUES('Mewtwo','Amnesia',81);
INSERT INTO Attacks_Learnt VALUES('Mew','Pound',0);
INSERT INTO Attacks_Learnt VALUES('Mew','Transform',10);
INSERT INTO Attacks_Learnt VALUES('Mew','Mega Punch',20);
INSERT INTO Attacks_Learnt VALUES('Mew','Metronome',30);
INSERT INTO Attacks_Learnt VALUES('Mew','Psychic',40);
