\c pokedabe
DELETE FROM Type;

INSERT INTO Type VALUES('NORMAL','The Normal type is the most basic type of Pokémon. They are very common and appear from the very first route you visit. Most Normal Pokémon are single type, but there is a large contingent having a second type of Flying.');
INSERT INTO Type VALUES('FIRE','Fire is one of the three basic elemental types along with Water and Grass, which constitute the three starter Pokémon.Fire types are notoriously rare in the early stages of the games so choosing the Fire variation starter is often a plus.');
INSERT INTO Type VALUES('WATER','Water is one of the three basic elemental types along with Fire and Grass, which constitute the three starter Pokémon. Water is the most common type with over 100 Pokémon, which are based on a wide variety of fish and other sea-dwelling creatures.');
INSERT INTO Type VALUES('ELECTRIC','There are relatively few Electric Pokémon; in fact only four were added in the third generation. Most are based on rodents or inanimate objects.');
INSERT INTO Type VALUES('GRASS','Grass is one of the three basic elemental types along with Fire and Water, which constitute the three starter Pokémon. This creates a simple triangle to explain the type concept easily to new players.Grass is one of the weakest types statistically, with 5 defensive weaknesses and 7 types that are resistant to Grass moves. Furthermore, many Grass Pokémon have Poison as their secondary type, adding a Psychic vulnerability. The type combination with the most weaknesses is Grass/Psychic');
INSERT INTO Type VALUES('ICE','Ice type Pokémon are now the rarest of all types: there are just 33 in total (ignoring Megas/Formes). They are ranked quite well defensively in terms of stats, although multiple type weaknesses let them down. Some are based on typical Arctic creatures like seals or yaks, while others are more mythical.');
INSERT INTO Type VALUES('FIGHTING','Fighting Pokémon are strong and muscle-bound, often based on martial artists. Fighting moves are super-effective against five other types (as is Ground), making them very good offensively. Most Fighting type moves are in the Physical category, for obvious reasons.');
INSERT INTO Type VALUES('POISON','The Poison type is regarded as one of the weakest offensively. Prior to Pokémon X/Y it was super-effective only against Grass (many of which are dual Poison so neutralizes the effect). It now has an extra advantage against the new Fairy type. In the first generation it was also super-effective against Bug but this was changed. It fares a little better defensively but its best advantage is through status moves like Toxic.');
INSERT INTO Type VALUES('GROUND','Ground is one of the strongest types offensively: it is super-effective against five other types (as is Fighting) and Earthquake is one of the strongest moves in the game with power and accuracy both 100. Unfortunately, many Ground type Pokémon are dual Rock types, lumbering them with 4x Grass and Water disadvantages.');
INSERT INTO Type VALUES('FLYING','Most Flying type Pokémon are based on birds or insects, along with some mythical creatures like dragons. On average they are faster than any other type.Nearly every Flying type has Flying as the secondary type, usually with Normal. There is only one pure Flying Pokémon (Tornadus), and one line with Flying as a primary type (Noibat/Noivern). As of Generation 6, the type has also been paired with every other type.');
INSERT INTO Type VALUES('PSYCHIC','The Psychic type has few outright strengths, however, it also has few weaknesses. In the first generation it ended up being massively overpowered, mainly due to a complete lack of powerful Bug moves, its only weakness. Furthermore, a mistake in the game meant that Ghost-type moves had no effect on Psychic (although this only affected the low-powered Lick). Generation 2 rectified the situation with the addition of the Dark type along with better Pokémon and moves of all types.');
INSERT INTO Type VALUES('BUG','Most Bug Pokémon grow quickly and evolve sooner than other types. As a result, they are often very weak. In Generation I, bugs were almost useless since the few Bug type moves available were very weak. The situation improved in later games with better moves and an advantage against the Dark type.');
INSERT INTO Type VALUES('ROCK','Rock is a solid type as one might expect. Like Steel, Rock Pokémon usually have high defense - however, since many Rock Pokémon are part Ground they have a 4x weakness to both Grass and Water whose moves often come as Special type.');
INSERT INTO Type VALUES('GHOST','Ghosts are rare Pokémon, and the only type to have two immunities. In total there are just 34 Ghost type Pokémon (not including Megas/Formes), slightly above Ice.In the first generation, Ghost moves has no effect on Psychic Pokémon, however, it was later changed to be super-effective. When paired with the Dark type it was the only type combination to have no weaknesses prior to Gen 6.');
INSERT INTO Type VALUES('DRAGON','Dragons are among the most elusive and powerful of all Pokémon. Nine legendary Pokémon are part Dragon type and four have legendary-like stats.They are notoriously difficult to train due to requiring more EXP points per level than most non-legendary Pokémon, and the fact they evolve much later and thus are in their weaker forms for longer. Interestingly, many final-evolution Dragon types have a 4x weakness to the Ice type.');
INSERT INTO Type VALUES('DARK','The Dark type was introduced in the second generation of Pokémon games as a measure to balance the types. In particular, its resistance to Psychic cut down that types advantage by a long way. When paired with the Ghost type it was the only type combination to have no weaknesses prior to Gen 6.');
INSERT INTO Type VALUES('STEEL','The Steel type was introduced in the second generation of Pokémon games. It is the strongest type defensively, with 10 types being not very effective against it and the Poison type having no effect. From Pokémon X/Y onwards, it lost its Ghost and Dark resistance, those types now dealing neutral damage. The Steel type also has the highest average Defense stat in the games.');
INSERT INTO Type VALUES('FAIRY','The Fairy type was introduced in Generation 6 - the first new type for more than 12 years! Its main intention was to balance the type chart by reducing the power of dragons, while also giving an offensive boost to the Poison and Steel types. Several old Pokémon were retyped and new Pokémon introduced. In total there are just 34 Fairy type Pokémon (not including Megas/Formes), slightly above Ice.');
