\c pokedabe
DELETE FROM Pokemon_Evolution;
INSERT INTO Pokemon_Evolution VALUES('Bulbasaur','Ivysaur','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Ivysaur','Venusaur','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Charmander','Charmeleon','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Charmeleon','Charizard','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Squirtle','Wartortle','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Wartortle','Blastoise','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Caterpie','Metapod','Level - 7');
INSERT INTO Pokemon_Evolution VALUES('Metapod','Butterfree','Level - 10');
INSERT INTO Pokemon_Evolution VALUES('Weedle','Kakuna','Level - 7');
INSERT INTO Pokemon_Evolution VALUES('Kakuna','Beedrill','Level - 10');
INSERT INTO Pokemon_Evolution VALUES('Pidgey','Pidgeotto','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Pidgeotto','Pidgeot','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Rattata','Raticate','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Rattata','Raticate','Level - 20; Nighttime');
INSERT INTO Pokemon_Evolution VALUES('Spearow','Fearow','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Ekans','Arbok','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Sandshrew','Sandslash','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Nidoran♀','Nidorina','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Nidoran♂','Nidorino','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Zubat','Golbat','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Oddish','Gloom','Level - 21');
INSERT INTO Pokemon_Evolution VALUES('Paras','Parasect','Level - 24');
INSERT INTO Pokemon_Evolution VALUES('Venonat','Venomoth','Level - 31');
INSERT INTO Pokemon_Evolution VALUES('Diglett','Dugtrio','Level - 26');
INSERT INTO Pokemon_Evolution VALUES('Meowth','Persian','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Psyduck','Golduck','Level - 33');
INSERT INTO Pokemon_Evolution VALUES('Mankey','Primeape','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Poliwag','Poliwhirl','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Abra','Kadabra','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Machop','Machoke','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Bellsprout','Weepinbell','Level - 21');
INSERT INTO Pokemon_Evolution VALUES('Tentacool','Tentacruel','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Geodude','Graveler','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Ponyta','Rapidash','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Slowpoke','Slowbro','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Magnemite','Magneton','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Doduo','Dodrio','Level - 31');
INSERT INTO Pokemon_Evolution VALUES('Seel','Dewgong','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Grimer','Muk','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Gastly','Haunter','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Drowzee','Hypno','Level - 26');
INSERT INTO Pokemon_Evolution VALUES('Krabby','Kingler','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Voltorb','Electrode','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Cubone','Marowak','Level - 28; outside Alola');
INSERT INTO Pokemon_Evolution VALUES('Cubone','Marowak','Level - 28; Nighttime, in Alola');
INSERT INTO Pokemon_Evolution VALUES('Tyrogue','Hitmonlee','Level - 20; Attack > Defense');
INSERT INTO Pokemon_Evolution VALUES('Tyrogue','Hitmonchan','Level - 20; Attack < Defense');
INSERT INTO Pokemon_Evolution VALUES('Tyrogue','Hitmontop','Level - 20; Attack = Defense');
INSERT INTO Pokemon_Evolution VALUES('Koffing','Weezing','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Rhyhorn','Rhydon','Level - 42');
INSERT INTO Pokemon_Evolution VALUES('Horsea','Seadra','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Goldeen','Seaking','Level - 33');
INSERT INTO Pokemon_Evolution VALUES('Smoochum','Jynx','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Elekid','Electabuzz','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Magby','Magmar','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Magikarp','Gyarados','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Omanyte','Omastar','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Kabuto','Kabutops','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Dratini','Dragonair','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Dragonair','Dragonite','Level - 55');
INSERT INTO Pokemon_Evolution VALUES('Chikorita','Bayleef','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Bayleef','Meganium','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Cyndaquil','Quilava','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Quilava','Typhlosion','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Totodile','Croconaw','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Croconaw','Feraligatr','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Sentret','Furret','Level - 15');
INSERT INTO Pokemon_Evolution VALUES('Hoothoot','Noctowl','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Ledyba','Ledian','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Spinarak','Ariados','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Chinchou','Lanturn','Level - 27');
INSERT INTO Pokemon_Evolution VALUES('Natu','Xatu','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Mareep','Flaaffy','Level - 15');
INSERT INTO Pokemon_Evolution VALUES('Flaaffy','Ampharos','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Marill','Azumarill','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Hoppip','Skiploom','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Skiploom','Jumpluff','Level - 27');
INSERT INTO Pokemon_Evolution VALUES('Wooper','Quagsire','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Wynaut','Wobbuffet','Level - 15');
INSERT INTO Pokemon_Evolution VALUES('Pineco','Forretress','Level - 31');
INSERT INTO Pokemon_Evolution VALUES('Snubbull','Granbull','Level - 23');
INSERT INTO Pokemon_Evolution VALUES('Teddiursa','Ursaring','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Slugma','Magcargo','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Swinub','Piloswine','Level - 33');
INSERT INTO Pokemon_Evolution VALUES('Remoraid','Octillery','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Houndour','Houndoom','Level - 24');
INSERT INTO Pokemon_Evolution VALUES('Phanpy','Donphan','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Larvitar','Pupitar','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Pupitar','Tyranitar','Level - 55');
INSERT INTO Pokemon_Evolution VALUES('Treecko','Grovyle','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Grovyle','Sceptile','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Torchic','Combusken','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Combusken','Blaziken','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Mudkip','Marshtomp','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Marshtomp','Swampert','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Poochyena','Mightyena','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Zigzagoon','Linoone','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Wurmple','Silcoon','Level - 7; random based on personality');
INSERT INTO Pokemon_Evolution VALUES('Silcoon','Beautifly','Level - 10');
INSERT INTO Pokemon_Evolution VALUES('Wurmple','Cascoon','Level - 7; random based on personality');
INSERT INTO Pokemon_Evolution VALUES('Cascoon','Dustox','Level - 10');
INSERT INTO Pokemon_Evolution VALUES('Lotad','Lombre','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Seedot','Nuzleaf','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Taillow','Swellow','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Wingull','Pelipper','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Ralts','Kirlia','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Kirlia','Gardevoir','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Surskit','Masquerain','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Shroomish','Breloom','Level - 23');
INSERT INTO Pokemon_Evolution VALUES('Slakoth','Vigoroth','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Vigoroth','Slaking','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Nincada','Ninjask','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Nincada','Shedinja','Level - 20; empty spot in party, Pokéball in bag');
INSERT INTO Pokemon_Evolution VALUES('Whismur','Loudred','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Loudred','Exploud','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Makuhita','Hariyama','Level - 24');
INSERT INTO Pokemon_Evolution VALUES('Aron','Lairon','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Lairon','Aggron','Level - 42');
INSERT INTO Pokemon_Evolution VALUES('Meditite','Medicham','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Electrike','Manectric','Level - 26');
INSERT INTO Pokemon_Evolution VALUES('Gulpin','Swalot','Level - 26');
INSERT INTO Pokemon_Evolution VALUES('Carvanha','Sharpedo','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Wailmer','Wailord','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Numel','Camerupt','Level - 33');
INSERT INTO Pokemon_Evolution VALUES('Spoink','Grumpig','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Trapinch','Vibrava','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Vibrava','Flygon','Level - 45');
INSERT INTO Pokemon_Evolution VALUES('Cacnea','Cacturne','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Swablu','Altaria','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Barboach','Whiscash','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Corphish','Crawdaunt','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Baltoy','Claydol','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Lileep','Cradily','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Anorith','Armaldo','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Shuppet','Banette','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Duskull','Dusclops','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Snorunt','Glalie','Level - 42');
INSERT INTO Pokemon_Evolution VALUES('Spheal','Sealeo','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Sealeo','Walrein','Level - 44');
INSERT INTO Pokemon_Evolution VALUES('Bagon','Shelgon','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Shelgon','Salamence','Level - 50');
INSERT INTO Pokemon_Evolution VALUES('Beldum','Metang','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Metang','Metagross','Level - 45');
INSERT INTO Pokemon_Evolution VALUES('Turtwig','Grotle','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Grotle','Torterra','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Chimchar','Monferno','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Monferno','Infernape','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Piplup','Prinplup','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Prinplup','Empoleon','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Starly','Staravia','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Staravia','Staraptor','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Bidoof','Bibarel','Level - 15');
INSERT INTO Pokemon_Evolution VALUES('Kricketot','Kricketune','Level - 10');
INSERT INTO Pokemon_Evolution VALUES('Shinx','Luxio','Level - 15');
INSERT INTO Pokemon_Evolution VALUES('Luxio','Luxray','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Cranidos','Rampardos','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Shieldon','Bastiodon','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Burmy','Mothim','Level - 20; Male');
INSERT INTO Pokemon_Evolution VALUES('Burmy','Wormadam','Level - 20; Female, in grass');
INSERT INTO Pokemon_Evolution VALUES('Combee','Vespiquen','Level - 21; Female');
INSERT INTO Pokemon_Evolution VALUES('Buizel','Floatzel','Level - 26');
INSERT INTO Pokemon_Evolution VALUES('Cherubi','Cherrim','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Shellos','Gastrodon','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Drifloon','Drifblim','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Glameow','Purugly','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Stunky','Skuntank','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Bronzor','Bronzong','Level - 33');
INSERT INTO Pokemon_Evolution VALUES('Gible','Gabite','Level - 24');
INSERT INTO Pokemon_Evolution VALUES('Gabite','Garchomp','Level - 48');
INSERT INTO Pokemon_Evolution VALUES('Hippopotas','Hippowdon','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Skorupi','Drapion','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Croagunk','Toxicroak','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Finneon','Lumineon','Level - 31');
INSERT INTO Pokemon_Evolution VALUES('Snover','Abomasnow','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Snivy','Servine','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Servine','Serperior','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Tepig','Pignite','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Pignite','Emboar','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Oshawott','Dewott','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Dewott','Samurott','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Patrat','Watchog','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Lillipup','Herdier','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Herdier','Stoutland','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Purrloin','Liepard','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Pidove','Tranquill','Level - 21');
INSERT INTO Pokemon_Evolution VALUES('Tranquill','Unfezant','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Blitzle','Zebstrika','Level - 27');
INSERT INTO Pokemon_Evolution VALUES('Roggenrola','Boldore','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Drilbur','Excadrill','Level - 31');
INSERT INTO Pokemon_Evolution VALUES('Timburr','Gurdurr','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Tympole','Palpitoad','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Palpitoad','Seismitoad','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Sewaddle','Swadloon','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Venipede','Whirlipede','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Whirlipede','Scolipede','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Sandile','Krokorok','Level - 29');
INSERT INTO Pokemon_Evolution VALUES('Krokorok','Krookodile','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Darumaka','Darmanitan','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Dwebble','Crustle','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Scraggy','Scrafty','Level - 39');
INSERT INTO Pokemon_Evolution VALUES('Yamask','Cofagrigus','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Tirtouga','Carracosta','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Archen','Archeops','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Trubbish','Garbodor','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Zorua','Zoroark','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Gothita','Gothorita','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Gothorita','Gothitelle','Level - 41');
INSERT INTO Pokemon_Evolution VALUES('Solosis','Duosion','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Duosion','Reuniclus','Level - 41');
INSERT INTO Pokemon_Evolution VALUES('Ducklett','Swanna','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Vanillite','Vanillish','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Vanillish','Vanilluxe','Level - 47');
INSERT INTO Pokemon_Evolution VALUES('Deerling','Sawsbuck','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Foongus','Amoonguss','Level - 39');
INSERT INTO Pokemon_Evolution VALUES('Frillish','Jellicent','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Joltik','Galvantula','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Ferroseed','Ferrothorn','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Klink','Klang','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Klang','Klinklang','Level - 49');
INSERT INTO Pokemon_Evolution VALUES('Tynamo','Eelektrik','Level - 39');
INSERT INTO Pokemon_Evolution VALUES('Elgyem','Beheeyem','Level - 42');
INSERT INTO Pokemon_Evolution VALUES('Litwick','Lampent','Level - 41');
INSERT INTO Pokemon_Evolution VALUES('Axew','Fraxure','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Fraxure','Haxorus','Level - 48');
INSERT INTO Pokemon_Evolution VALUES('Cubchoo','Beartic','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Mienfoo','Mienshao','Level - 50');
INSERT INTO Pokemon_Evolution VALUES('Golett','Golurk','Level - 43');
INSERT INTO Pokemon_Evolution VALUES('Pawniard','Bisharp','Level - 52');
INSERT INTO Pokemon_Evolution VALUES('Rufflet','Braviary','Level - 54');
INSERT INTO Pokemon_Evolution VALUES('Vullaby','Mandibuzz','Level - 54');
INSERT INTO Pokemon_Evolution VALUES('Deino','Zweilous','Level - 50');
INSERT INTO Pokemon_Evolution VALUES('Zweilous','Hydreigon','Level - 64');
INSERT INTO Pokemon_Evolution VALUES('Larvesta','Volcarona','Level - 59');
INSERT INTO Pokemon_Evolution VALUES('Chespin','Quilladin','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Quilladin','Chesnaught','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Fennekin','Braixen','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Braixen','Delphox','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Froakie','Frogadier','Level - 16');
INSERT INTO Pokemon_Evolution VALUES('Frogadier','Greninja','Level - 36');
INSERT INTO Pokemon_Evolution VALUES('Bunnelby','Diggersby','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Fletchling','Fletchinder','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Fletchinder','Talonflame','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Scatterbug','Spewpa','Level - 9');
INSERT INTO Pokemon_Evolution VALUES('Spewpa','Vivillon','Level - 12');
INSERT INTO Pokemon_Evolution VALUES('Litleo','Pyroar','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Flabébé','Floette','Level - 19');
INSERT INTO Pokemon_Evolution VALUES('Skiddo','Gogoat','Level - 32');
INSERT INTO Pokemon_Evolution VALUES('Pancham','Pangoro','Level - 32; Dark type Pokémon in party');
INSERT INTO Pokemon_Evolution VALUES('Espurr','Meowstic','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Honedge','Doublade','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Inkay','Malamar','Level - 30; holding console upside down');
INSERT INTO Pokemon_Evolution VALUES('Binacle','Barbaracle','Level - 39');
INSERT INTO Pokemon_Evolution VALUES('Skrelp','Dragalge','Level - 48');
INSERT INTO Pokemon_Evolution VALUES('Clauncher','Clawitzer','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Tyrunt','Tyrantrum','Level - 39; Daytime');
INSERT INTO Pokemon_Evolution VALUES('Amaura','Aurorus','Level - 39; Nighttime');
INSERT INTO Pokemon_Evolution VALUES('Goomy','Sliggoo','Level - 40');
INSERT INTO Pokemon_Evolution VALUES('Sliggoo','Goodra','Level - 50; during rain');
INSERT INTO Pokemon_Evolution VALUES('Bergmite','Avalugg','Level - 37');
INSERT INTO Pokemon_Evolution VALUES('Noibat','Noivern','Level - 48');
INSERT INTO Pokemon_Evolution VALUES('Rowlet','Dartrix','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Dartrix','Decidueye','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Litten','Torracat','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Torracat','Incineroar','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Popplio','Brionne','Level - 17');
INSERT INTO Pokemon_Evolution VALUES('Brionne','Primarina','Level - 34');
INSERT INTO Pokemon_Evolution VALUES('Pikipek','Trumbeak','Level - 14');
INSERT INTO Pokemon_Evolution VALUES('Trumbeak','Toucannon','Level - 28');
INSERT INTO Pokemon_Evolution VALUES('Yungoos','Gumshoos','Level - 20; Daytime');
INSERT INTO Pokemon_Evolution VALUES('Grubbin','Charjabug','Level - 20');
INSERT INTO Pokemon_Evolution VALUES('Cutiefly','Ribombee','Level - 25');
INSERT INTO Pokemon_Evolution VALUES('Rockruff','Lycanroc','Level - 25; Daytime, in Pokémon Sun or Ultra Sun');
INSERT INTO Pokemon_Evolution VALUES('Mareanie','Toxapex','Level - 38');
INSERT INTO Pokemon_Evolution VALUES('Mudbray','Mudsdale','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Dewpider','Araquanid','Level - 22');
INSERT INTO Pokemon_Evolution VALUES('Fomantis','Lurantis','Level - 34; Daytime');
INSERT INTO Pokemon_Evolution VALUES('Morelull','Shiinotic','Level - 24');
INSERT INTO Pokemon_Evolution VALUES('Salandit','Salazzle','Level - 33; Female');
INSERT INTO Pokemon_Evolution VALUES('Stufful','Bewear','Level - 27');
INSERT INTO Pokemon_Evolution VALUES('Bounsweet','Steenee','Level - 18');
INSERT INTO Pokemon_Evolution VALUES('Wimpod','Golisopod','Level - 30');
INSERT INTO Pokemon_Evolution VALUES('Sandygast','Palossand','Level - 42');
INSERT INTO Pokemon_Evolution VALUES('Jangmo-o','Hakamo-o','Level - 35');
INSERT INTO Pokemon_Evolution VALUES('Hakamo-o','Kommo-o','Level - 45');
INSERT INTO Pokemon_Evolution VALUES('Cosmog','Cosmoem','Level - 43');
INSERT INTO Pokemon_Evolution VALUES('Cosmoem','Solgaleo','Level - 53; in Pokémon Sun or Ultra Sun');
INSERT INTO Pokemon_Evolution VALUES('Cosmoem','Lunala','Level - 53; in Pokémon Moon or Ultra Moon');
INSERT INTO Pokemon_Evolution VALUES('Poliwhirl','Politoed','Trading while holding Kings Rock');
INSERT INTO Pokemon_Evolution VALUES('Kadabra','Alakazam','Trading');
INSERT INTO Pokemon_Evolution VALUES('Machoke','Machamp','Trading');
INSERT INTO Pokemon_Evolution VALUES('Graveler','Golem','Trading');
INSERT INTO Pokemon_Evolution VALUES('Graveler','Golem','Trading');
INSERT INTO Pokemon_Evolution VALUES('Slowpoke','Slowking','Trading while holding Kings Rock');
INSERT INTO Pokemon_Evolution VALUES('Haunter','Gengar','Trading');
INSERT INTO Pokemon_Evolution VALUES('Onix','Steelix','Trading while holding Metal Coat');
INSERT INTO Pokemon_Evolution VALUES('Rhydon','Rhyperior','Trading while holding Protector');
INSERT INTO Pokemon_Evolution VALUES('Seadra','Kingdra','Trading while holding Dragon Scale');
INSERT INTO Pokemon_Evolution VALUES('Scyther','Scizor','Trading while holding Metal Coat');
INSERT INTO Pokemon_Evolution VALUES('Electabuzz','Electivire','Trading while holding Electirizer');
INSERT INTO Pokemon_Evolution VALUES('Magmar','Magmortar','Trading while holding Magmarizer');
INSERT INTO Pokemon_Evolution VALUES('Porygon','Porygon2','Trading while holding Up Grade');
INSERT INTO Pokemon_Evolution VALUES('Porygon2','Porygon-Z','Trading while holding Dubious Disc');
INSERT INTO Pokemon_Evolution VALUES('Feebas','Milotic','Trading while holding Prism Scale, or level up with max Beauty');
INSERT INTO Pokemon_Evolution VALUES('Dusclops','Dusknoir','Trading while holding Reaper Cloth');
INSERT INTO Pokemon_Evolution VALUES('Clamperl','Huntail','Trading while holding Deep Sea Tooth');
INSERT INTO Pokemon_Evolution VALUES('Clamperl','Gorebyss','Trading while holding Deep Sea Scale');
INSERT INTO Pokemon_Evolution VALUES('Boldore','Gigalith','Trading');
INSERT INTO Pokemon_Evolution VALUES('Gurdurr','Conkeldurr','Trading');
INSERT INTO Pokemon_Evolution VALUES('Karrablast','Escavalier','Trading while holding Trade with Shelmet');
INSERT INTO Pokemon_Evolution VALUES('Shelmet','Accelgor','Trading while holding Trade with Karrablast');
INSERT INTO Pokemon_Evolution VALUES('Spritzee','Aromatisse','Trading while holding Sachet');
INSERT INTO Pokemon_Evolution VALUES('Swirlix','Slurpuff','Trading while holding Whipped Dream');
INSERT INTO Pokemon_Evolution VALUES('Phantump','Trevenant','Trading');
INSERT INTO Pokemon_Evolution VALUES('Pumpkaboo','Gourgeist','Trading');
INSERT INTO Pokemon_Evolution VALUES('Pikachu','Raichu','Using Thunder Stone, in or outside Alola');
INSERT INTO Pokemon_Evolution VALUES('Sandshrew','Sandslash','Using Ice Stone');
INSERT INTO Pokemon_Evolution VALUES('Nidorina','Nidoqueen','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Nidorino','Nidoking','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Clefairy','Clefable','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Vulpix','Ninetales','Using Fire Stone');
INSERT INTO Pokemon_Evolution VALUES('Vulpix','Ninetales','Using Ice Stone');
INSERT INTO Pokemon_Evolution VALUES('Jigglypuff','Wigglytuff','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Gloom','Vileplume','Using Leaf Stone');
INSERT INTO Pokemon_Evolution VALUES('Gloom','Bellossom','Using Sun Stone');
INSERT INTO Pokemon_Evolution VALUES('Growlithe','Arcanine','Using Fire Stone');
INSERT INTO Pokemon_Evolution VALUES('Poliwhirl','Poliwrath','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Weepinbell','Victreebel','Using Leaf Stone');
INSERT INTO Pokemon_Evolution VALUES('Shellder','Cloyster','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Exeggcute','Exeggutor','Using Leaf Stone, in or outside Alola');
INSERT INTO Pokemon_Evolution VALUES('Staryu','Starmie','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Eevee','Vaporeon','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Eevee','Jolteon','Using Thunder Stone');
INSERT INTO Pokemon_Evolution VALUES('Eevee','Flareon','Using Fire Stone');
INSERT INTO Pokemon_Evolution VALUES('Togetic','Togekiss','Using Shiny Stone');
INSERT INTO Pokemon_Evolution VALUES('Sunkern','Sunflora','Using Sun Stone');
INSERT INTO Pokemon_Evolution VALUES('Murkrow','Honchkrow','Using Dusk Stone');
INSERT INTO Pokemon_Evolution VALUES('Misdreavus','Mismagius','Using Dusk Stone');
INSERT INTO Pokemon_Evolution VALUES('Lombre','Ludicolo','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Nuzleaf','Shiftry','Using Leaf Stone');
INSERT INTO Pokemon_Evolution VALUES('Kirlia','Gallade','Using Dawn Stone, Male');
INSERT INTO Pokemon_Evolution VALUES('Skitty','Delcatty','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Roselia','Roserade','Using Shiny Stone');
INSERT INTO Pokemon_Evolution VALUES('Snorunt','Froslass','Using Dawn Stone, Female');
INSERT INTO Pokemon_Evolution VALUES('Pansage','Simisage','Using Leaf Stone');
INSERT INTO Pokemon_Evolution VALUES('Pansear','Simisear','Using Fire Stone');
INSERT INTO Pokemon_Evolution VALUES('Panpour','Simipour','Using Water Stone');
INSERT INTO Pokemon_Evolution VALUES('Munna','Musharna','Using Moon Stone');
INSERT INTO Pokemon_Evolution VALUES('Cottonee','Whimsicott','Using Sun Stone');
INSERT INTO Pokemon_Evolution VALUES('Petilil','Lilligant','Using Sun Stone');
INSERT INTO Pokemon_Evolution VALUES('Minccino','Cinccino','Using Shiny Stone');
INSERT INTO Pokemon_Evolution VALUES('Eelektrik','Eelektross','Using Thunder Stone');
INSERT INTO Pokemon_Evolution VALUES('Lampent','Chandelure','Using Dusk Stone');
INSERT INTO Pokemon_Evolution VALUES('Floette','Florges','Using Shiny Stone');
INSERT INTO Pokemon_Evolution VALUES('Doublade','Aegislash','Using Dusk Stone');
INSERT INTO Pokemon_Evolution VALUES('Helioptile','Heliolisk','Using Sun Stone');
INSERT INTO Pokemon_Evolution VALUES('Pichu','Pikachu','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Cleffa','Clefairy','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Igglybuff','Jigglypuff','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Golbat','Crobat','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Meowth','Persian','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Chansey','Blissey','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Eevee','Espeon','Friendship during Daytime');
INSERT INTO Pokemon_Evolution VALUES('Eevee','Umbreon','Friendship during Nighttime');
INSERT INTO Pokemon_Evolution VALUES('Munchlax','Snorlax','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Togepi','Togetic','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Azurill','Marill','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Budew','Roselia','Friendship during Daytime');
INSERT INTO Pokemon_Evolution VALUES('Chingling','Chimecho','Friendship during Nighttime');
INSERT INTO Pokemon_Evolution VALUES('Buneary','Lopunny','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Riolu','Lucario','Friendship during Daytime');
INSERT INTO Pokemon_Evolution VALUES('Woobat','Swoobat','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Swadloon','Leavanny','Friendship');
INSERT INTO Pokemon_Evolution VALUES('Type: Null','Silvally','Friendship');