\c pokedabe
DELETE FROM pokemon_found_in_town;
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Omanyte','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Kabuto','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Aerodactyl','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Lileep','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Anorith','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Cranidos','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Shieldon','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Latias','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Latios','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Hoothoot','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Pineco','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Wurmple','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Starly','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Xatu','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Haunter','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Rapidash','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Gloom','Pewter');
INSERT INTO pokemon_found_in_town VALUES('Squirtle','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Persian','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Arcanine','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Tentacruel','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Wingull','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Shellder','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Chinchou','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Lanturn','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Spearow','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Heracross','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Combee','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Diglett','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Shuckle','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Horsea','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Staryu','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Farfetchd','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Spearow','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Snorlax','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Vermilion');
INSERT INTO pokemon_found_in_town VALUES('Bulbasaur','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Seaking','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Hoothoot','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Pineco','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Combee','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Horsea','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Jynx','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Poliwhirl','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Kingler','Cerulean');
INSERT INTO pokemon_found_in_town VALUES('Diglett','Lavender');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Lavender');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Lavender');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Lavender');
INSERT INTO pokemon_found_in_town VALUES('Eevee','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Vulpix','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Sandshrew','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Grimer','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Muk','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Heracross','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Combee','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Mr. Mime','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Eevee','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Porygon','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Koffing','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Clefairy','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Abra','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Scyther','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Pinsir','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Dratini','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Pikachu','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Larvitar','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Poliwhirl','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Nidorina','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Nidorino','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Wigglytuff','Celadon');
INSERT INTO pokemon_found_in_town VALUES('Pikachu','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Eevee','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Tentacruel','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Shellder','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Chinchou','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Lanturn','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Charmander','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Squirtle','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Hoothoot','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Ledyba','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Spinarak','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Pineco','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Wurmple','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Horsea','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Staryu','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Kingler','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Seadra','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Bulbasaur','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Charmander','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Squirtle','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Pallet');
INSERT INTO pokemon_found_in_town VALUES('Zubat','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Golbat','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Seel','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Jynx','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Slowbro','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Dewgong','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Squirtle','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Shellder','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Tentacruel','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Cloyster','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Articuno','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Golduck','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Makuhita','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Absol','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Chingling','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Bronzor','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Horsea','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Kingler','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Seadra','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Staryu','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Seafoam Islands');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Tentacruel','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Horsea','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Qwilfish','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Remoraid','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Kingler','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Seadra','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Outcast Island');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Poliwhirl','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Hoothoot','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Ledyba','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Spinarak','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Pineco','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Wurmple','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Tentacool','Viridian');
INSERT INTO pokemon_found_in_town VALUES('Pidgey','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Pidgeotto','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Pidgeot','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Magikarp','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Hoothoot','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Ledyba','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Spinarak','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Wurmple','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Psyduck','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Slowpoke','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Goldeen','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Seaking','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Poliwag','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Krabby','Fuchsia');
INSERT INTO pokemon_found_in_town VALUES('Gyarados','Fuchsia');