\c pokedabe
DELETE FROM Items;

INSERT INTO Items VALUES('Ability Capsule','Hold items','A capsule that allows a Pokemon with two Abilities to switch between these Abilities when it is used.');
INSERT INTO Items VALUES('Ability Urge','Battle items','When used, it activates the Ability of an ally Pokemon.');
INSERT INTO Items VALUES('Abomasite','Hold items','Enables Abomasnow to Mega Evolve during battle.');
INSERT INTO Items VALUES('Absolite','Hold items','Enables Absol to Mega Evolve during battle.');
INSERT INTO Items VALUES('Absorb Bulb','Hold items','A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.');
INSERT INTO Items VALUES('Adamant Orb','Hold items','Increases the power of Dragon- and Steel-type moves when held by Dialga.');
INSERT INTO Items VALUES('Adrenaline Orb','Hold items','Using it makes wild Pokemon more likely to call for help. If held by a Pokemon, it boosts Speed when intimidated. It can be used only once.');
INSERT INTO Items VALUES('Aerodactylite','Hold items','Enables Aerodactyl to Mega Evolve during battle.');
INSERT INTO Items VALUES('Aggronite','Hold items','Enables Aggron to Mega Evolve during battle.');
INSERT INTO Items VALUES('Aguav Berry','Berries','Restores HP if it s low, but may cause confusion.');
INSERT INTO Items VALUES('Air Balloon','Hold items','When held by a Pokemon, the Pokemon will float into the air. When the holder is attacked, this item will burst.');
INSERT INTO Items VALUES('Alakazite','Hold items','Enables Alakazam to Mega Evolve during battle.');
INSERT INTO Items VALUES('Aloraichium Z','Hold items','Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.');
INSERT INTO Items VALUES('Altarianite','Hold items','Enables Altaria to Mega Evolve during battle.');
INSERT INTO Items VALUES('Ampharosite','Hold items','Enables Ampharos to Mega Evolve during battle.');
INSERT INTO Items VALUES('Amulet Coin','Hold items','Doubles prize money if held.');
INSERT INTO Items VALUES('Antidote','Medicine','A spray-type medicine. It lifts the effect of poison from one Pokemon.');
INSERT INTO Items VALUES('Apicot Berry','Berries','Raises Special Defense when HP is low.');
INSERT INTO Items VALUES('Armor Fossil','General items','A fossil from a prehistoric Pokemon that lived on the land. It appears to be part of a collar.');
INSERT INTO Items VALUES('Aspear Berry','Berries','If held by a Pokemon, it defrosts it.');
INSERT INTO Items VALUES('Assault Vest','Hold items','Raises Special Defense but prevents the use of status moves.');
INSERT INTO Items VALUES('Audinite','Hold items','Enables Audino to Mega Evolve during battle.');
INSERT INTO Items VALUES('Autograph',null,null);
INSERT INTO Items VALUES('Awakening','Medicine','A spray-type medicine. It awakens a Pokemon from the clutches of sleep.');
INSERT INTO Items VALUES('Babiri Berry','Berries','Weakens a supereffective Steel-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Balm Mushroom','General items','A rare mushroom which gives off a nice fragrance. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Banettite','Hold items','Enables Banette to Mega Evolve during battle.');
INSERT INTO Items VALUES('Beach Glass','General items',null);
INSERT INTO Items VALUES('Beast Ball','Pokeballs','A special Poké Ball designed to catch Ultra Beasts. It has a low success rate for catching others.');
INSERT INTO Items VALUES('Beedrillite','Hold items','Enables Beedrill to Mega Evolve during battle.');
INSERT INTO Items VALUES('Belue Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Berry Juice','Medicine','A 100% pure juice made of Berries. It restores the HP of one Pokemon by just 20 points.');
INSERT INTO Items VALUES('Big Malasada','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Big Mushroom','General items','A large and rare mushroom. It is sought after by collectors.');
INSERT INTO Items VALUES('Big Nugget','General items','A big nugget of pure gold that gives off a lustrous gleam. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Big Pearl','General items','A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.');
INSERT INTO Items VALUES('Big Root','Hold items','Recovers more HP from HP-stealing moves.');
INSERT INTO Items VALUES('Binding Band','Hold items','A band that increases the power of binding moves when held.');
INSERT INTO Items VALUES('Black Apricorn','General items','A black Apricorn It has an indescribable scent.');
INSERT INTO Items VALUES('Black Belt','Hold items','Increases the power of Fighting-type moves.');
INSERT INTO Items VALUES('Black Flute','General items','A toy flute made from black glass. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Black Glasses','Hold items','Increases the power of Dark-type moves.');
INSERT INTO Items VALUES('Black Sludge','Hold items','A held item that gradually restores the HP of Poison-type Pokemon. It inflicts damage on all other types.');
INSERT INTO Items VALUES('Blastoisinite','Hold items','Enables Blastoise to Mega Evolve during battle.');
INSERT INTO Items VALUES('Blazikenite','Hold items','Enables Blaziken to Mega Evolve during battle.');
INSERT INTO Items VALUES('Blue Apricorn','General items','A blue Apricorn. It smells a bit like grass.');
INSERT INTO Items VALUES('Blue Flute','General items','A toy flute made from blue glass. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Blue Scarf','General items','Raises holder s Beauty aspect in a Contest.');
INSERT INTO Items VALUES('Blue Shard','General items','A small blue shard. It appears to be from some sort of implement made long ago.');
INSERT INTO Items VALUES('Bluk Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Bottle Cap','General items','Maximizes one IV stat in Hyper Training.');
INSERT INTO Items VALUES('Bright Powder','Hold items','Lowers the opponent s accuracy.');
INSERT INTO Items VALUES('Bug Gem','Hold items','Increases the power of a Bug-type move only once.');
INSERT INTO Items VALUES('Bug Memory','Hold items','Changes Silvally and its move Multi-Attack to Bug type.');
INSERT INTO Items VALUES('Buginium Z','Hold items','Allows the use of Savage Spin-Out, the Bug type Z-Move.');
INSERT INTO Items VALUES('Burn Drive','Hold items','Changes Techno Blast to a Fire-type move when held by Genesect.');
INSERT INTO Items VALUES('Burn Heal','Medicine','A spray-type medicine. It heals a single Pokemon that is suffering from a burn.');
INSERT INTO Items VALUES('Calcium','Medicine','Increases Special Attack EVs by 10.');
INSERT INTO Items VALUES('Cameruptite','Hold items','Enables Camerupt to Mega Evolve during battle.');
INSERT INTO Items VALUES('Carbos','Medicine','Increases Speed EVs by 10.');
INSERT INTO Items VALUES('Casteliacone','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Cell Battery','Hold items','A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.');
INSERT INTO Items VALUES('Chalky Stone','General items',null);
INSERT INTO Items VALUES('Charcoal','Hold items','Increases the power of Fire-type moves.');
INSERT INTO Items VALUES('Charizardite X','Hold items','Enables Charizard to Mega Evolve during battle.');
INSERT INTO Items VALUES('Charizardite Y','Hold items','Enables Charizard to Mega Evolve during battle.');
INSERT INTO Items VALUES('Charti Berry','Berries','Weakens a supereffective Rock-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Cheri Berry','Berries','If held by a Pokemon, it recovers from paralysis.');
INSERT INTO Items VALUES('Cherish Ball','Pokeballs','A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.');
INSERT INTO Items VALUES('Chesto Berry','Berries','If held by a Pokemon, it recovers from sleep.');
INSERT INTO Items VALUES('Chilan Berry','Berries','Weakens a Normal-type attack against the Pokemon holding this berry.');
INSERT INTO Items VALUES('Chill Drive','Hold items','Changes Techno Blast to an Ice-type move when held by Genesect.');
INSERT INTO Items VALUES('Choice Band','Hold items','Raises Attack, but only one move can be used.');
INSERT INTO Items VALUES('Choice Scarf','Hold items','Raises Speed, but only one move can be used.');
INSERT INTO Items VALUES('Choice Specs','Hold items','Raises Special Attack, but only one move can be used.');
INSERT INTO Items VALUES('Chople Berry','Berries','Weakens a supereffective Fighting-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Claw Fossil','General items','A fossil of an ancient Pokemon that lived in the sea. It appears to be part of a claw.');
INSERT INTO Items VALUES('Cleanse Tag','Hold items','An item to be held by a Pokemon. It helps keep wild Pokemon away if the holder is the first one in the party.');
INSERT INTO Items VALUES('Clever Wing','Medicine','Increases Special Defense EVs by 1.');
INSERT INTO Items VALUES('Coba Berry','Berries','Weakens a supereffective Flying-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Colbur Berry','Berries','Weakens a supereffective Dark-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Colress Machine','Hold items','A special device that wrings out the potential of Pokemon. It is an imperfect prototype.');
INSERT INTO Items VALUES('Comet Shard','General items','A shard which fell to the ground when a comet approached. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Cornn Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Courage Candy','Medicine','Increases a Pokemon s Special Defense stat by 1.');
INSERT INTO Items VALUES('Courage Candy L','Medicine','Increases a Pokemon s Special Defense stat.');
INSERT INTO Items VALUES('Courage Candy XL','Medicine','Increases a Pokemon s Special Defense stat.');
INSERT INTO Items VALUES('Cover Fossil','General items','A fossil of an ancient Pokemon that lived in the sea in ancient times. It appears to be part of its back.');
INSERT INTO Items VALUES('Custap Berry','Berries','Holder can move first when HP is low.');
INSERT INTO Items VALUES('Damp Mulch','General items','A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Damp Rock','Hold items','A Pokemon held item that extends the duration of the move Rain Dance used by the holder.');
INSERT INTO Items VALUES('Dark Gem','Hold items','Increases the power of a Dark-type move only once.');
INSERT INTO Items VALUES('Dark Memory','Hold items','Changes Silvally and its move Multi-Attack to Dark type.');
INSERT INTO Items VALUES('Darkinium Z','Hold items','Allows the use of Black Hole Eclipse, the Dark type Z-Move.');
INSERT INTO Items VALUES('Dawn Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Decidium Z','Hold items','Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.');
INSERT INTO Items VALUES('Deep Sea Scale','Hold items','Increases Special Defense when held by Clamperl. Evolves Clamperl when traded holding the item.');
INSERT INTO Items VALUES('Deep Sea Tooth','Hold items','Increases Special Attack when held by Clamperl. Evolves Clamperl when traded holding the item.');
INSERT INTO Items VALUES('Destiny Knot','Hold items','A long, thin, bright-red string to be held by a Pokemon. If the holder becomes infatuated, the foe does too.');
INSERT INTO Items VALUES('Diancite','Hold items','Enables Diancie to Mega Evolve during battle.');
INSERT INTO Items VALUES('Dire Hit','Battle items','Raises critical-hit ratio of a Pokemon in battle.');
INSERT INTO Items VALUES('Dire Hit 2','Battle items','Raises a Pokemon s critical-hit ratio in battle.');
INSERT INTO Items VALUES('Dire Hit 3','Battle items','Greatly raises a Pokemon s critical-hit ratio in battle.');
INSERT INTO Items VALUES('Discount Coupon','General items','This special coupon allows you to buy items at a discount when you are shopping at a boutique.');
INSERT INTO Items VALUES('Dive Ball','Pokeballs','A somewhat different Poké Ball that works especially well on Pokemon that live underwater.');
INSERT INTO Items VALUES('DNA Splicers','General items','A splicer that fuses Kyurem and a certain Pokemon. They are said to have been one in the beginning.');
INSERT INTO Items VALUES('Dome Fossil','General items','A fossil of an ancient Pokemon that lived in the sea. It appears to be part of a shell.');
INSERT INTO Items VALUES('Douse Drive','Hold items','Changes Techno Blast to a Water-type move when held by Genesect.');
INSERT INTO Items VALUES('Draco Plate','Hold items','Increases power of Dragon-type moves. Changes Arceus  type to Dragon.');
INSERT INTO Items VALUES('Dragon Fang','Hold items','Increases the power of Dragon-type moves.');
INSERT INTO Items VALUES('Dragon Gem','Hold items','Increases the power of a Dragon-type move only once.');
INSERT INTO Items VALUES('Dragon Memory','Hold items','Changes Silvally and its move Multi-Attack to Dragon type.');
INSERT INTO Items VALUES('Dragon Scale','General items','Evolves Seadra when traded holding the item.');
INSERT INTO Items VALUES('Dragonium Z','Hold items','Allows the use of Devastating Drake, the Dragon type Z-Move.');
INSERT INTO Items VALUES('Dread Plate','Hold items','Increases power of Dark-type moves. Changes Arceus  type to Dark.');
INSERT INTO Items VALUES('Dream Ball','Pokeballs','A special Poké Ball that appears out of nowhere in a bag at the Entree Forest. It can catch any Pokemon.');
INSERT INTO Items VALUES('Dropped Item','Hold items','The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.');
INSERT INTO Items VALUES('Dubious Disc','General items','Evolves Porygon2 when traded holding the item.');
INSERT INTO Items VALUES('Durin Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Dusk Ball','Pokeballs','A somewhat different Poké Ball that makes it easier to catch wild Pokemon at night or in dark places like caves.');
INSERT INTO Items VALUES('Dusk Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Earth Plate','Hold items','Increases power of Ground-type moves. Changes Arceus  type to Ground.');
INSERT INTO Items VALUES('Eevium Z','Hold items','Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.');
INSERT INTO Items VALUES('Eject Button','Hold items','If the holder is hit by an attack, it will switch with another Pokemon in your party.');
INSERT INTO Items VALUES('Electirizer','General items','Evolves Electabuzz when traded holding the item.');
INSERT INTO Items VALUES('Electric Gem','Hold items','Increases the power of an Electric-type move only once.');
INSERT INTO Items VALUES('Electric Memory','Hold items','Changes Silvally and its move Multi-Attack to Electric type.');
INSERT INTO Items VALUES('Electric Seed','Hold items','An item to be held by a Pokemon. It boosts Defense on Electric Terrain. It can only be used once.');
INSERT INTO Items VALUES('Electrium Z','Hold items','Allows the use of Gigavolt Havoc, the Electric type Z-Move.');
INSERT INTO Items VALUES('Elevator Key','Hold items','A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flare s logo.');
INSERT INTO Items VALUES('Elixir','Medicine','It restores the PP of all the moves learned by the targeted Pokemon by 10 points each.');
INSERT INTO Items VALUES('Energy Powder','Medicine','Restores 60 HP but lowers Friendship.');
INSERT INTO Items VALUES('Energy Root','Medicine','Restores 120 HP but lowers Friendship.');
INSERT INTO Items VALUES('Enigma Berry','Berries','If held by a Pokemon, it restores its HP if it is hit by any supereffective attack.');
INSERT INTO Items VALUES('Escape Rope','General items','A long, durable rope. Use it to escape instantly from a cave or a dungeon.');
INSERT INTO Items VALUES('Ether','Medicine','It restores the PP of a Pokemon s selected move by a maximum of 10 points.');
INSERT INTO Items VALUES('Everstone','Hold items','An item to be held by a Pokemon. The Pokemon holding this peculiar stone is prevented from evolving.');
INSERT INTO Items VALUES('Eviolite','Hold items','A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokemon that can still evolve.');
INSERT INTO Items VALUES('Exp. Share','Hold items','An item to be held by a Pokemon. The holder gets a share of a battle s Exp. Points without battling.');
INSERT INTO Items VALUES('Expert Belt','Hold items','Increases the power of super-effective moves.');
INSERT INTO Items VALUES('Fairium Z','Hold items','Allows the use of Twinkle Tackle, the Fairy type Z-Move.');
INSERT INTO Items VALUES('Fairy Gem','General items','Increases the power of a Fairy-type move only once.');
INSERT INTO Items VALUES('Fairy Memory','Hold items','Changes Silvally and its move Multi-Attack to Fairy type.');
INSERT INTO Items VALUES('Fast Ball','Pokeballs','A Poké Ball that makes it easier to catch Pokemon which are quick to run away.');
INSERT INTO Items VALUES('Festival Ticket','General items','A ticket that allows you to host a mission in Festival Plaza.');
INSERT INTO Items VALUES('Fighting Gem','Hold items','Increases the power of a Fighting-type move only once.');
INSERT INTO Items VALUES('Fighting Memory','Hold items','Changes Silvally and its move Multi-Attack to Fighting type.');
INSERT INTO Items VALUES('Fightinium Z','Hold items','Allows the use of All-Out Pummeling, the Fighting type Z-Move.');
INSERT INTO Items VALUES('Figy Berry','Berries','Restores HP if it s low, but may cause confusion.');
INSERT INTO Items VALUES('Fire Gem','Hold items','Increases the power of a Fire-type move only once.');
INSERT INTO Items VALUES('Fire Memory','Hold items','Changes Silvally and its move Multi-Attack to Fire type.');
INSERT INTO Items VALUES('Fire Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Firium Z','Hold items','Allows the use of Inferno Overdrive, the Fire type Z-Move.');
INSERT INTO Items VALUES('Fist Plate','Hold items','Increases power of Fighting-type moves. Changes Arceus  type to Fighting.');
INSERT INTO Items VALUES('Flame Orb','Hold items','An item to be held by a Pokemon. It is a bizarre orb that inflicts a burn on the holder in battle.');
INSERT INTO Items VALUES('Flame Plate','Hold items','Increases power of Fire-type moves. Changes Arceus  type to Fire.');
INSERT INTO Items VALUES('Float Stone','Hold items','A very light stone. It reduces the weight of a Pokemon when held.');
INSERT INTO Items VALUES('Fluffy Tail','General items','An item that attracts Pokemon. Use it to flee from any battle with a wild Pokemon.');
INSERT INTO Items VALUES('Flying Gem','Hold items','Increases the power of a Flying-type move only once.');
INSERT INTO Items VALUES('Flying Memory','Hold items','Changes Silvally and its move Multi-Attack to Flying type.');
INSERT INTO Items VALUES('Flyinium Z','Hold items','Allows the use of Supersonic Skystrike, the Flying type Z-Move.');
INSERT INTO Items VALUES('Focus Band','Hold items','An item to be held by a Pokemon. The holder may endure a potential KO attack, leaving it with just 1 HP.');
INSERT INTO Items VALUES('Focus Sash','Hold items','An item to be held by a Pokemon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.');
INSERT INTO Items VALUES('Fresh Water','Medicine','Restores 30 HP.');
INSERT INTO Items VALUES('Friend Ball','Pokeballs','A Poké Ball that makes caught Pokemon more friendly.');
INSERT INTO Items VALUES('Full Heal','Medicine','A spray-type medicine. It heals all the status problems of a single Pokemon.');
INSERT INTO Items VALUES('Full Incense','Hold items','Holder always attacks last. Breeding Snorlax produces Munchlax when held.');
INSERT INTO Items VALUES('Full Restore','Medicine','A medicine that fully restores the HP and heals any status problems of a single Pokemon.');
INSERT INTO Items VALUES('Galladite','Hold items','Enables Gallade to Mega Evolve during battle.');
INSERT INTO Items VALUES('Ganlon Berry','Berries','Raises Defense when HP is low.');
INSERT INTO Items VALUES('Garchompite','Hold items','Enables Garchomp to Mega Evolve during battle.');
INSERT INTO Items VALUES('Gardevoirite','Hold items','Enables Gardevoir to Mega Evolve during battle.');
INSERT INTO Items VALUES('Gengarite','Hold items','Enables Gengar to Mega Evolve during battle.');
INSERT INTO Items VALUES('Genius Wing','Medicine','Increases Special Attack EVs by 1.');
INSERT INTO Items VALUES('Ghost Gem','Hold items','Increases the power of a Ghost-type move only once.');
INSERT INTO Items VALUES('Ghost Memory','Hold items','Changes Silvally and its move Multi-Attack to Ghost type.');
INSERT INTO Items VALUES('Ghostium Z','Hold items','Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.');
INSERT INTO Items VALUES('Glalitite','Hold items','Enables Glalie to Mega Evolve during battle.');
INSERT INTO Items VALUES('Gold Bottle Cap','General items','Maximizes all of a Pokemon s IV stats in Hyper Training.');
INSERT INTO Items VALUES('Gold Leaf','General items',null);
INSERT INTO Items VALUES('Golden Nanab Berry','Berries','Drastically calms a Pokemon in battle, in Let s Go Pikachu/Eevee.');
INSERT INTO Items VALUES('Golden Pinap Berry','Berries','Drastically increases chance of getting items when a Pokemon is caught, in Pokemon Let s Go.');
INSERT INTO Items VALUES('Golden Razz Berry','Berries','Makes a Pokemon easier to catch in Pokemon Let s Go.');
INSERT INTO Items VALUES('Gooey Mulch','General items','A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Grass Gem','Hold items','Increases the power of a Grass-type move only once.');
INSERT INTO Items VALUES('Grass Memory','Hold items','Changes Silvally and its move Multi-Attack to Grass type.');
INSERT INTO Items VALUES('Grassium Z','Hold items','Allows the use of Bloom Doom, the Grass type Z-Move.');
INSERT INTO Items VALUES('Grassy Seed','Hold items','An item to be held by a Pokemon. It boosts Defense on Grassy Terrain. It can only be used once.');
INSERT INTO Items VALUES('Great Ball','Pokeballs','A good, high-performance Ball that provides a higher Pokemon catch rate than a standard Poké Ball.');
INSERT INTO Items VALUES('Green Apricorn','General items','A green Apricorn. It has a mysterious, aromatic scent.');
INSERT INTO Items VALUES('Green Scarf','General items','Raises holder s Smart aspect in a Contest.');
INSERT INTO Items VALUES('Green Shard','General items','A small green shard. It appears to be from some sort of implement made long ago.');
INSERT INTO Items VALUES('Grepa Berry','Berries','Increases Friendship but lowers Special Defense EVs.');
INSERT INTO Items VALUES('Grip Claw','Hold items','A Pokemon held item that extends the duration of multiturn attacks like Bind and Wrap.');
INSERT INTO Items VALUES('Griseous Orb','Hold items','Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.');
INSERT INTO Items VALUES('Ground Gem','Hold items','Increases the power of a Ground-type move only once.');
INSERT INTO Items VALUES('Ground Memory','Hold items','Changes Silvally and its move Multi-Attack to Ground type.');
INSERT INTO Items VALUES('Groundium Z','Hold items','Allows the use of Tectonic Rage, the Ground type Z-Move.');
INSERT INTO Items VALUES('Growth Mulch','General items','A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Grubby Hanky','Hold items','A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokemon.');
INSERT INTO Items VALUES('Guard Spec.','Battle items','Prevents stat reduction for five turns.');
INSERT INTO Items VALUES('Gyaradosite','Hold items','Enables Gyarados to Mega Evolve during battle.');
INSERT INTO Items VALUES('Haban Berry','Berries','Weakens a supereffective Dragon-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Hard Stone','Hold items','Increases the power of Rock-type moves.');
INSERT INTO Items VALUES('Heal Ball','Pokeballs','A remedial Poké Ball that restores the caught Pokemon s HP and eliminates any status problem.');
INSERT INTO Items VALUES('Heal Powder','Medicine','Heals all status problems, but lowers Friendship.');
INSERT INTO Items VALUES('Health Candy','Medicine','Increases a Pokemon s HP stat by 1.');
INSERT INTO Items VALUES('Health Candy L','Medicine','Increases a Pokemon s HP stat.');
INSERT INTO Items VALUES('Health Candy XL','Medicine','Increases a Pokemon s HP stat.');
INSERT INTO Items VALUES('Health Wing','Medicine','Increases HP EVs by 1.');
INSERT INTO Items VALUES('Heart Scale','General items','A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.');
INSERT INTO Items VALUES('Heat Rock','Hold items','A Pokemon held item that extends the duration of the move Sunny Day used by the holder.');
INSERT INTO Items VALUES('Heavy Ball','Pokeballs','A Poké Ball for catching very heavy Pokemon.');
INSERT INTO Items VALUES('Helix Fossil','General items','A fossil of an ancient Pokemon that lived in the sea. It appears to be part of a seashell.');
INSERT INTO Items VALUES('Heracronite','Hold items','Enables Heracross to Mega Evolve during battle.');
INSERT INTO Items VALUES('HM01','Machines','Teaches the move Cut.');
INSERT INTO Items VALUES('HM02','Machines','Teaches the move Fly.');
INSERT INTO Items VALUES('HM03','Machines','Teaches the move Surf.');
INSERT INTO Items VALUES('HM04','Machines','Teaches the move Strength.');
INSERT INTO Items VALUES('HM05','Machines','Teaches the move Flash/Defog/Whirlpool/Waterfall.');
INSERT INTO Items VALUES('HM06','Machines','Teaches the move Whirlpool/Rock Smash/Dive.');
INSERT INTO Items VALUES('HM07','Machines','Teaches the move Waterfall.');
INSERT INTO Items VALUES('HM08','Machines','Teaches the move Dive/Rock Climb.');
INSERT INTO Items VALUES('Hondew Berry','Berries','Increases Friendship but lowers Special Attack EVs.');
INSERT INTO Items VALUES('Honey','General items','A sweet honey with a lush aroma that attracts wild Pokemon when it is used in grass, caves, or on special trees.');
INSERT INTO Items VALUES('Honor Of Kalos','Hold items','A precious symbol that is awarded only to an individual who has done great things for the Kalos region.');
INSERT INTO Items VALUES('Houndoominite','Hold items','Enables Houndoom to Mega Evolve during battle.');
INSERT INTO Items VALUES('HP Up','Medicine','Increases HP EVs by 10.');
INSERT INTO Items VALUES('Hyper Potion','Medicine','Restores 120 HP.');
INSERT INTO Items VALUES('Iapapa Berry','Berries','Restores HP if it s low, but may cause confusion.');
INSERT INTO Items VALUES('Ice Gem','Hold items','Increases the power of an Ice-type move only once.');
INSERT INTO Items VALUES('Ice Heal','Medicine','A spray-type medicine. It defrosts a Pokemon that has been frozen solid.');
INSERT INTO Items VALUES('Ice Memory','Hold items','Changes Silvally and its move Multi-Attack to Ice type.');
INSERT INTO Items VALUES('Ice Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Icicle Plate','Hold items','Increases power of Ice-type moves. Changes Arceus  type to Ice.');
INSERT INTO Items VALUES('Icium Z','Hold items','Allows the use of Subzero Slammer, the Ice type Z-Move.');
INSERT INTO Items VALUES('Icy Rock','Hold items','A Pokemon held item that extends the duration of the move Hail used by the holder.');
INSERT INTO Items VALUES('Incinium Z','Hold items','Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.');
INSERT INTO Items VALUES('Insect Plate','Hold items','Increases power of Bug-type moves. Changes Arceus  type to Bug.');
INSERT INTO Items VALUES('Intriguing Stone','Hold items','A rather curious stone that might appear to be valuable to some. It s all in the eye of the beholder.');
INSERT INTO Items VALUES('Iron','Medicine','Increases Defense EVs by 10.');
INSERT INTO Items VALUES('Iron Ball','Hold items','A Pokemon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.');
INSERT INTO Items VALUES('Iron Plate','Hold items','Increases power of Steel-type moves. Changes Arceus  type to Steel.');
INSERT INTO Items VALUES('Item Drop','Battle items','When used, it causes an ally Pokemon to drop a held item.');
INSERT INTO Items VALUES('Item Urge','Battle items','When used, it causes an ally Pokemon to use its held item.');
INSERT INTO Items VALUES('Jaboca Berry','Berries','If held by a Pokemon and a physical attack lands, the attacker also takes damage.');
INSERT INTO Items VALUES('Kangaskhanite','Hold items','Enables Kangaskhan to Mega Evolve during battle.');
INSERT INTO Items VALUES('Kasib Berry','Berries','Weakens a supereffective Ghost-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Kebia Berry','Berries','Weakens a supereffective Poison-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Kee Berry','Berries','If held by a Pokemon, this Berry will increase the holder s Defense if it s hit with a physical move.');
INSERT INTO Items VALUES('Kelpsy Berry','Berries','Increases Friendship but lowers Attack EVs.');
INSERT INTO Items VALUES('King s Rock','Hold items','May cause opponent to flinch. Evolves Poliwhirl and Slowpoke when traded holding the item.');
INSERT INTO Items VALUES('Kommonium Z','Hold items','Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.');
INSERT INTO Items VALUES('Lagging Tail','Hold items','Holder always attacks last.');
INSERT INTO Items VALUES('Lansat Berry','Berries','Increases critical-hit ratio when HP is low.');
INSERT INTO Items VALUES('Latiasite','Hold items','Enables Latias to Mega Evolve during battle.');
INSERT INTO Items VALUES('Latiosite','Hold items','Enables Latios to Mega Evolve during battle.');
INSERT INTO Items VALUES('Lava Cookie','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Lax Incense','Hold items','Lowers the opponent s accuracy. Breeding Wobbuffet produces Wynaut when held.');
INSERT INTO Items VALUES('Leaf Letter','General items','A letter written on a leaf. Something is written using Eevee s footprints.');
INSERT INTO Items VALUES('Leaf Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Leftovers','Hold items','An item to be held by a Pokemon. The holder s HP is gradually restored during battle.');
INSERT INTO Items VALUES('Lemonade','Medicine','Restores 70 HP.');
INSERT INTO Items VALUES('Leppa Berry','Berries','If held by a Pokemon, it restores a move s PP by 10.');
INSERT INTO Items VALUES('Level Ball','Pokeballs','A Poké Ball for catching Pokemon that are a lower level than your own.');
INSERT INTO Items VALUES('Liechi Berry','Berries','Raises Attack when HP is low.');
INSERT INTO Items VALUES('Life Orb','Hold items','Increases the power of moves, but loses HP each turn.');
INSERT INTO Items VALUES('Light Ball','Hold items','An item to be held by PIKACHU. It is a puzzling orb that raises the Attack and Sp. Atk stat.');
INSERT INTO Items VALUES('Light Clay','Hold items','A Pokemon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.');
INSERT INTO Items VALUES('Lone Earring','General items',null);
INSERT INTO Items VALUES('Looker Ticket','Hold items','A ticket that was handmade by Looker. It s decorated with a liberal amount of glittery paint.');
INSERT INTO Items VALUES('Lopunnite','Hold items','Enables Lopunny to Mega Evolve during battle.');
INSERT INTO Items VALUES('Love Ball','Pokeballs','Poké Ball for catching Pokemon that are the opposite gender of your Pokemon.');
INSERT INTO Items VALUES('Lucarionite','Hold items','Enables Lucario to Mega Evolve during battle.');
INSERT INTO Items VALUES('Luck Incense','Hold items','Doubles prize money if held. Breeding Chansey or Blissey produces Happiny when held.');
INSERT INTO Items VALUES('Lucky Egg','Hold items','An item to be held by a Pokemon. It is an egg filled with happiness that earns extra Exp. Points in battle.');
INSERT INTO Items VALUES('Lucky Punch','Hold items','Increases critical-hit ratio when held by Chansey.');
INSERT INTO Items VALUES('Lum Berry','Berries','If held by a Pokemon, it recovers from any status problem.');
INSERT INTO Items VALUES('Luminous Moss','Hold items','Raises Special Defense if hit by a Water-type move.');
INSERT INTO Items VALUES('Lumiose Galette','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Lunalium Z','Hold items','Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.');
INSERT INTO Items VALUES('Lure','General items','Attracts Pokemon in the wild.');
INSERT INTO Items VALUES('Lure Ball','Pokeballs','A Poké Ball for catching Pokemon hooked by a Rod when fishing.');
INSERT INTO Items VALUES('Lustrous Orb','Hold items','Increases the power of Dragon- and Water-type moves when held by Palkia.');
INSERT INTO Items VALUES('Luxury Ball','Pokeballs','A comfortable Poké Ball that makes a caught wild Pokemon quickly grow friendly.');
INSERT INTO Items VALUES('Lycanium Z','Hold items','Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.');
INSERT INTO Items VALUES('Macho Brace','Hold items','An item to be held by a Pokemon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.');
INSERT INTO Items VALUES('Magmarizer','General items','Evolves Magmar when traded holding the item.');
INSERT INTO Items VALUES('Magnet','Hold items','Increases the power of Electric-type moves.');
INSERT INTO Items VALUES('Mago Berry','Berries','Restores HP if it s low, but may cause confusion.');
INSERT INTO Items VALUES('Magost Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Manectite','Hold items','Enables Manectric to Mega Evolve during battle.');
INSERT INTO Items VALUES('Maranga Berry','Berries','If held by a Pokemon, this Berry will increase the holder s Sp. Def if it s hit with a special move.');
INSERT INTO Items VALUES('Marble','General items',null);
INSERT INTO Items VALUES('Marshadium Z','Hold items','Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.');
INSERT INTO Items VALUES('Master Ball','Pokeballs','The best Ball with the ultimate level of performance. It will catch any wild Pokemon without fail.');
INSERT INTO Items VALUES('Mawilite','Hold items','Enables Mawile to Mega Evolve during battle.');
INSERT INTO Items VALUES('Max Elixir','Medicine','It fully restores the PP of all the moves learned by the targeted Pokemon.');
INSERT INTO Items VALUES('Max Ether','Medicine','It fully restores the PP of a single selected move that has been learned by the target Pokemon.');
INSERT INTO Items VALUES('Max Lure','General items','Attracts Pokemon in the wild.');
INSERT INTO Items VALUES('Max Potion','Medicine','Fully restores HP.');
INSERT INTO Items VALUES('Max Repel','General items','An item that prevents weak wild Pokemon from appearing for 250 steps after its use.');
INSERT INTO Items VALUES('Max Revive','Medicine','A medicine that revives a fainted Pokemon. It fully restores the Pokemon s HP.');
INSERT INTO Items VALUES('Meadow Plate','Hold items','Increases power of Grass-type moves. Changes Arceus  type to Grass.');
INSERT INTO Items VALUES('Medichamite','Hold items','Enables Medicham to Mega Evolve during battle.');
INSERT INTO Items VALUES('Mental Herb','Hold items','An item to be held by a Pokemon. It snaps the holder out of infatuation. It can be used only once.');
INSERT INTO Items VALUES('Metagrossite','Hold items','Enables Metagross to Mega Evolve during battle.');
INSERT INTO Items VALUES('Metal Coat','Hold items','Increases the power of Steel-type moves. Evolves Onix and Scyther when traded holding the item.');
INSERT INTO Items VALUES('Metal Powder','Hold items','Increases Defense when held by Ditto.');
INSERT INTO Items VALUES('Metronome','Hold items','Increases the power of moves used consecutively.');
INSERT INTO Items VALUES('Mewnium Z','Hold items','Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.');
INSERT INTO Items VALUES('Mewtwonite X','Hold items','Enables Mewtwo to Mega Evolve during battle.');
INSERT INTO Items VALUES('Mewtwonite Y','Hold items','Enables Mewtwo to Mega Evolve during battle.');
INSERT INTO Items VALUES('Micle Berry','Berries','Increases a move s accuracy when HP is low.');
INSERT INTO Items VALUES('Mighty Candy','Medicine','Increases a Pokemon s Attack stat by 1.');
INSERT INTO Items VALUES('Mighty Candy L','Medicine','Increases a Pokemon s Attack stat.');
INSERT INTO Items VALUES('Mighty Candy XL','Medicine','Increases a Pokemon s Attack stat.');
INSERT INTO Items VALUES('Mimikium Z','Hold items','Allows Mimikyu to upgrade Play Rough to a Z-Move, Let s Snuggle Forever.');
INSERT INTO Items VALUES('Mind Plate','Hold items','Increases power of Psychic-type moves. Changes Arceus  type to Psychic.');
INSERT INTO Items VALUES('Miracle Seed','Hold items','Increases the power of Grass-type moves.');
INSERT INTO Items VALUES('Misty Seed','Hold items','An item to be held by a Pokemon. It boosts Sp. Def on Misty Terrain. It can only be used once.');
INSERT INTO Items VALUES('Moomoo Milk','Medicine','Milk with a very high nutrition content. It restores the HP of one Pokemon by 100 points.');
INSERT INTO Items VALUES('Moon Ball','Pokeballs','A Poké Ball for catching Pokemon that evolve using the Moon Stone.');
INSERT INTO Items VALUES('Moon Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Muscle Band','Hold items','Increases the power of Physical-category moves.');
INSERT INTO Items VALUES('Muscle Wing','Medicine','Increases Attack EVs by 1.');
INSERT INTO Items VALUES('Mystic Water','Hold items','Increases the power of Water-type moves.');
INSERT INTO Items VALUES('Nanab Berry','Berries','A Berry to be used in cooking. Calms a Pokemon in battle, in Let s Go Pikachu/Eevee.');
INSERT INTO Items VALUES('Nest Ball','Pokeballs','A somewhat different Poké Ball that works especially well on weaker Pokemon in the wild.');
INSERT INTO Items VALUES('Net Ball','Pokeballs','A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokemon.');
INSERT INTO Items VALUES('Never-Melt Ice','Hold items','Increases the power of Ice-type moves.');
INSERT INTO Items VALUES('Nomel Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Normal Gem','Hold items','Increases the power of a Normal-type move only once.');
INSERT INTO Items VALUES('Normalium Z','Hold items','Allows the use of Breakneck Blitz, the Normal type Z-Move.');
INSERT INTO Items VALUES('Nugget','General items','A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.');
INSERT INTO Items VALUES('Occa Berry','Berries','Weakens a supereffective Fire-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Odd Incense','Hold items','Increases the power of Psychic-type moves. Breeding Mr. Mime produces Mime Jr. when held.');
INSERT INTO Items VALUES('Odd Keystone','General items','A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.');
INSERT INTO Items VALUES('Old Amber','General items','A piece of amber that contains the genetic material of an ancient Pokemon. It is clear with a reddish tint.');
INSERT INTO Items VALUES('Old Gateau','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Oran Berry','Berries','If held by a Pokemon, it heals the user by just 10 HP.');
INSERT INTO Items VALUES('Oval Charm','General items','An oval charm said to increase the chance of Pokemon Eggs being found at the Day Care.');
INSERT INTO Items VALUES('Oval Stone','General items','Evolves Happiny when held.');
INSERT INTO Items VALUES('Pamtre Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Paralyze Heal','Medicine','A spray-type medicine. It eliminates paralysis from a single Pokemon.');
INSERT INTO Items VALUES('Park Ball','Pokeballs','A special Poké Ball for the Pal Park.');
INSERT INTO Items VALUES('Pass Orb','Hold items','A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.');
INSERT INTO Items VALUES('Passho Berry','Berries','Weakens a supereffective Water-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Payapa Berry','Berries','Weakens a supereffective Psychic-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Pearl','General items','A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.');
INSERT INTO Items VALUES('Pearl String','General items','Very large pearls that sparkle in a pretty silver color. A maniac will buy them for a high price.');
INSERT INTO Items VALUES('Pecha Berry','Berries','If held by a Pokemon, it recovers from poison.');
INSERT INTO Items VALUES('Permit','General items','A permit that is needed to enter the Nature Preserve. Not many know about it.');
INSERT INTO Items VALUES('Persim Berry','Berries','If held by a Pokemon, it recovers from confusion.');
INSERT INTO Items VALUES('Petaya Berry','Berries','Raises Special Attack when HP is low.');
INSERT INTO Items VALUES('Pewter Crunchies','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Pidgeotite','Hold items','Enables Pidgeot to Mega Evolve during battle.');
INSERT INTO Items VALUES('Pikanium Z','Hold items','Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.');
INSERT INTO Items VALUES('Pikashunium Z','Hold items','Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.');
INSERT INTO Items VALUES('Pinap Berry','Berries','A Berry to be used in cooking. Increases chances of getting items when a Pokemon is caught, in Pokemon Let s Go.');
INSERT INTO Items VALUES('Pink Apricorn','General items','A pink Apricorn. It has a nice, sweet scent.');
INSERT INTO Items VALUES('Pink Nectar','Hold items','The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokemon.');
INSERT INTO Items VALUES('Pink Scarf','General items','Raises holder s Cute aspect in a Contest.');
INSERT INTO Items VALUES('Pinsirite','Hold items','Enables Pinsir to Mega Evolve during battle.');
INSERT INTO Items VALUES('Pixie Plate','Hold items','Increases power of Fairy-type moves. Changes Arceus  type to Fairy.');
INSERT INTO Items VALUES('Plasma Card','Hold items','A card key needed to enter the password inside the Plasma Frigate.');
INSERT INTO Items VALUES('Plume Fossil','General items','A fossil of an ancient Pokemon that flew in the sky in ancient times. It appears to be part of its wing.');
INSERT INTO Items VALUES('Poison Barb','Hold items','Increases the power of Poison-type moves.');
INSERT INTO Items VALUES('Poison Gem','Hold items','Increases the power of a Poison-type move only once.');
INSERT INTO Items VALUES('Poison Memory','Hold items','Changes Silvally and its move Multi-Attack to Poison type.');
INSERT INTO Items VALUES('Poisonium Z','Hold items','Allows the use of Acid Downpour, the Poison type Z-Move.');
INSERT INTO Items VALUES('Poké Ball','Pokeballs','A device for catching wild Pokemon. It is thrown like a ball at the target. It is designed as a capsule system.');
INSERT INTO Items VALUES('Poké Doll','General items','A doll that attracts Pokemon. Use it to flee from any battle with a wild Pokemon.');
INSERT INTO Items VALUES('Poké Toy','General items','An item that attracts Pokemon. Use it to flee from any battle with a wild Pokemon.');
INSERT INTO Items VALUES('Polished Mud Ball','General items',null);
INSERT INTO Items VALUES('Pomeg Berry','Berries','Increases Friendship but lowers HP EVs.');
INSERT INTO Items VALUES('Potion','Medicine','Restores 20 HP.');
INSERT INTO Items VALUES('Power Anklet','Hold items','A Pokemon held item that promotes Speed gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('Power Band','Hold items','A Pokemon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('Power Belt','Hold items','A Pokemon held item that promotes Defense gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('Power Bracer','Hold items','A Pokemon held item that promotes Attack gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('Power Herb','Hold items','A single-use item to be held by a Pokemon. It allows the immediate use of a move that charges on the first turn.');
INSERT INTO Items VALUES('Power Lens','Hold items','A Pokemon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('Power Plant Pass','Hold items','This pass serves as an ID card for gaining access to the power plant that lies along Route 13.');
INSERT INTO Items VALUES('Power Weight','Hold items','A Pokemon held item that promotes HP gain on leveling, but reduces the Speed stat.');
INSERT INTO Items VALUES('PP Max','Medicine','It maximally raises the top PP of a selected move that has been learned by the target Pokemon.');
INSERT INTO Items VALUES('PP Up','Medicine','It slightly raises the maximum PP of a selected move that has been learned by the target Pokemon.');
INSERT INTO Items VALUES('Premier Ball','Pokeballs','A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.');
INSERT INTO Items VALUES('Pretty Wing','General items','Though this feather is beautiful, it s just a regular feather and has no effect on Pokemon.');
INSERT INTO Items VALUES('Primarium Z','Hold items','Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.');
INSERT INTO Items VALUES('Prism Scale','General items','Evolves Feebas when traded holding the item.');
INSERT INTO Items VALUES('Prison Bottle','Hold items','Transforms Hoopa Confined to Hoopa Unbound.');
INSERT INTO Items VALUES('Prof s Letter','Hold items','A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.');
INSERT INTO Items VALUES('Protective Pads','Hold items','An item to be held by a Pokemon. These pads protect the holder from effects caused by making direct contact with the target.');
INSERT INTO Items VALUES('Protector','General items','Evolves Rhydon when traded holding the item.');
INSERT INTO Items VALUES('Protein','Medicine','Increases Attack EVs by 10.');
INSERT INTO Items VALUES('Psychic Gem','Hold items','Increases the power of a Psychic-type move only once.');
INSERT INTO Items VALUES('Psychic Memory','Hold items','Changes Silvally and its move Multi-Attack to Psychic type.');
INSERT INTO Items VALUES('Psychic Seed','Hold items','An item to be held by a Pokemon. It boosts Sp. Def on Psychic Terrain. It can only be used once.');
INSERT INTO Items VALUES('Psychium Z','Hold items','Allows the use of Shattered Psyche, the Psychic type Z-Move.');
INSERT INTO Items VALUES('Pure Incense','Hold items','Descreases the likelihood of meeting wild Pokemon. Breeding Chimecho produces Chingling when held.');
INSERT INTO Items VALUES('Purple Nectar','Hold items','A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokemon.');
INSERT INTO Items VALUES('Qualot Berry','Berries','Increases Friendship but lowers Defense EVs.');
INSERT INTO Items VALUES('Quick Ball','Pokeballs','A somewhat different Poké Ball that provides a better catch rate if it is used at the start of a wild encounter.');
INSERT INTO Items VALUES('Quick Candy','Medicine','Increases a Pokemon s Speed stat by 1.');
INSERT INTO Items VALUES('Quick Candy L','Medicine','Increases a Pokemon s Speed stat.');
INSERT INTO Items VALUES('Quick Candy XL','Medicine','Increases a Pokemon s Speed stat.');
INSERT INTO Items VALUES('Quick Claw','Hold items','An item to be held by a Pokemon. A light, sharp claw that lets the bearer move first occasionally.');
INSERT INTO Items VALUES('Quick Powder','Hold items','Increases Speed when held by Ditto.');
INSERT INTO Items VALUES('Rabuta Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Rage Candy Bar','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Rare Bone','General items','A bone that is extremely valuable for Pokemon archeology. It can be sold for a high price to shops.');
INSERT INTO Items VALUES('Rare Candy','Medicine','A candy that is packed with energy. It raises the level of a single Pokemon by one.');
INSERT INTO Items VALUES('Rawst Berry','Berries','If held by a Pokemon, it recovers from a burn.');
INSERT INTO Items VALUES('Razor Claw','Hold items','Increases critical-hit ratio. Evolves Sneasel when held at night.');
INSERT INTO Items VALUES('Razor Fang','Hold items','May cause opponent to flinch. Evolves Gligar when held at night.');
INSERT INTO Items VALUES('Razz Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Reaper Cloth','General items','Evolves Dusclops when traded holding the item.');
INSERT INTO Items VALUES('Red Apricorn','General items','A red Apricorn. It assails your nostrils.');
INSERT INTO Items VALUES('Red Card','Hold items','A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.');
INSERT INTO Items VALUES('Red Flute','General items','A toy flute made from red glass. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Red Nectar','Hold items','A flower nectar obtained at Ula ula Meadow. It changes the form of certain species of Pokemon.');
INSERT INTO Items VALUES('Red Scarf','General items','Raises holder s Cool aspect in a Contest.');
INSERT INTO Items VALUES('Red Shard','General items','A small red shard. It appears to be from some sort of implement made long ago.');
INSERT INTO Items VALUES('Relic Band','General items','A bracelet made in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Copper','General items','A copper coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Crown','General items','A crown made in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Gold','General items','A gold coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Silver','General items','A silver coin used in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Statue','General items','A stone figure made in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Relic Vase','General items','A vase made in a civilization about 3,000 years ago. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Repeat Ball','Pokeballs','A somewhat different Poké Ball that works especially well on Pokemon species that were previously caught.');
INSERT INTO Items VALUES('Repel','General items','An item that prevents weak wild Pokemon from appearing for 100 steps after its use.');
INSERT INTO Items VALUES('Reset Urge','Battle items','When used, it restores any stat changes of an ally Pokemon.');
INSERT INTO Items VALUES('Resist Wing','Medicine','Increases Defense EVs by 1.');
INSERT INTO Items VALUES('Reveal Glass','General items','A looking glass that reveals the truth. It s a mysterious glass that returns a Pokemon to its original shape.');
INSERT INTO Items VALUES('Revival Herb','Medicine','Revives a Pokemon to max HP, but lowers Friendship.');
INSERT INTO Items VALUES('Revive','Medicine','A medicine that revives a fainted Pokemon. It restores half the Pokemon s maximum HP.');
INSERT INTO Items VALUES('Rindo Berry','Berries','Weakens a supereffective Grass-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Ring Target','Hold items','Moves that would otherwise have no effect will land on the Pokemon that holds it.');
INSERT INTO Items VALUES('Rock Gem','Hold items','Increases the power of a Rock-type move only once.');
INSERT INTO Items VALUES('Rock Incense','Hold items','Increases the power of Rock-type moves. Breeding Sudowoodo produces Bonsly when held.');
INSERT INTO Items VALUES('Rock Memory','Hold items','Changes Silvally and its move Multi-Attack to Rock type.');
INSERT INTO Items VALUES('Rockium Z','Hold items','Allows the use of Continental Crush, the Rock type Z-Move.');
INSERT INTO Items VALUES('Rocky Helmet','Hold items','If the holder of this item takes damage, the attacker will also be damaged upon contact.');
INSERT INTO Items VALUES('Roller Skates','General items','Attaches roller skates to the bottom of your shoes, allowing you to glide quickly around and perform tricks.');
INSERT INTO Items VALUES('Root Fossil','General items','A fossil of an ancient Pokemon that lived in the sea. It appears to be part of a plant root.');
INSERT INTO Items VALUES('Rose Incense','Hold items','Increases the power of Grass-type moves. Breeding Roselia or Roserade produces Budew when held.');
INSERT INTO Items VALUES('Roseli Berry','Berries','If held by a Pokemon, this Berry will lessen the damage taken from one supereffective Fairy-type attack.');
INSERT INTO Items VALUES('Roto Bargain','Battle items','Reduces the prices of products at Poké Marts by half.');
INSERT INTO Items VALUES('Roto Boost','Battle items','Raises all stats of your battling Pokemon.');
INSERT INTO Items VALUES('Roto Catch','Battle items','Increases the chance to catch Pokemon a lot.');
INSERT INTO Items VALUES('Roto Encounter','Battle items','Increases the chance of encountering high-level wild Pokemon a lot for a certain period of time.');
INSERT INTO Items VALUES('Roto Exp. Points','Battle items','Increases the Exp. Points your Pokemon receive after battle a little.');
INSERT INTO Items VALUES('Roto Friendship','Battle items','Helps Pokemon in your party grow friendly faster.');
INSERT INTO Items VALUES('Roto Hatch','Battle items','Helps Eggs hatch faster.');
INSERT INTO Items VALUES('Roto HP Restore','Battle items','Fully restores the HP of your battling Pokemon.');
INSERT INTO Items VALUES('Roto PP Restore','Battle items','Fully restores the PP of your battling Pokemon.');
INSERT INTO Items VALUES('Roto Prize Money','Battle items','Triples the prize money you receive after battle.');
INSERT INTO Items VALUES('Roto Stealth','Battle items','Prevents you from encountering wild Pokemon for a certain period of time.');
INSERT INTO Items VALUES('Rowap Berry','Berries','If held by a Pokemon and a special attack lands, the attacker also takes damage.');
INSERT INTO Items VALUES('Sablenite','Hold items','Enables Sableye to Mega Evolve during battle.');
INSERT INTO Items VALUES('Sachet','General items','Evolves Spritzee when traded holding the item.');
INSERT INTO Items VALUES('Sacred Ash','Medicine','It revives all fainted Pokemon. In doing so, it also fully restores their HP.');
INSERT INTO Items VALUES('Safari Ball','Pokeballs','A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.');
INSERT INTO Items VALUES('Safety Goggles','Hold items','Prevents damage from weather and powder.');
INSERT INTO Items VALUES('Salac Berry','Berries','Raises Speed when HP is low.');
INSERT INTO Items VALUES('Salamencite','Hold items','Enables Salamence to Mega Evolve during battle.');
INSERT INTO Items VALUES('Sceptilite','Hold items','Enables Sceptile to Mega Evolve during battle.');
INSERT INTO Items VALUES('Scizorite','Hold items','Enables Scizor to Mega Evolve during battle.');
INSERT INTO Items VALUES('Scope Lens','Hold items','Increases critical-hit ratio.');
INSERT INTO Items VALUES('Sea Incense','Hold items','Increases the power of Water-type moves. Breeding Marill or Azumarill produces Azurill when held.');
INSERT INTO Items VALUES('Shalour Sable','Medicine','Heals all major status conditions.');
INSERT INTO Items VALUES('Sharp Beak','Hold items','Increases the power of Flying-type moves.');
INSERT INTO Items VALUES('Sharpedonite','Hold items','Enables Sharpedo to Mega Evolve during battle.');
INSERT INTO Items VALUES('Shed Shell','Hold items','A tough, discarded carapace to be held by a Pokemon. It enables the holder to switch with a waiting Pokemon in battle.');
INSERT INTO Items VALUES('Shell Bell','Hold items','An item to be held by a Pokemon. The holder s HP is restored a little every time it inflicts damage.');
INSERT INTO Items VALUES('Shiny Charm','General items','A shiny charm said to increase the chance of finding a Shiny Pokemon in the wild.');
INSERT INTO Items VALUES('Shiny Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Shoal Salt','General items','Pure salt that can be discovered deep inside the Shoal Cave. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Shoal Shell','General items','A pretty seashell that can be found deep inside the Shoal Cave. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Shock Drive','Hold items','Changes Techno Blast to an Electric-type move when held by Genesect.');
INSERT INTO Items VALUES('Shuca Berry','Berries','Weakens a supereffective Ground-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Silk Scarf','Hold items','Increases the power of Normal-type moves.');
INSERT INTO Items VALUES('Silver Leaf','General items',null);
INSERT INTO Items VALUES('Silver Nanab Berry','Berries','Greatly calms a Pokemon in battle, in Let s Go Pikachu/Eevee.');
INSERT INTO Items VALUES('Silver Pinap Berry','Berries','Greatly increases chance of getting items when a Pokemon is caught, in Pokemon Let s Go.');
INSERT INTO Items VALUES('Silver Powder','Hold items','Increases the power of Bug-type moves.');
INSERT INTO Items VALUES('Silver Razz Berry','Berries','Makes a Pokemon easier to catch in Pokemon Let s Go.');
INSERT INTO Items VALUES('Sitrus Berry','Berries','If held by a Pokemon, it heals the user s HP a little.');
INSERT INTO Items VALUES('Skull Fossil','General items','A fossil from a prehistoric Pokemon that lived on the land. It appears to be part of a head.');
INSERT INTO Items VALUES('Sky Plate','Hold items','Increases power of Flying-type moves. Changes Arceus  type to Flying.');
INSERT INTO Items VALUES('Slowbronite','Hold items','Enables Slowbro to Mega Evolve during battle.');
INSERT INTO Items VALUES('Small Bouquet','General items',null);
INSERT INTO Items VALUES('Smart Candy','Medicine','Increases a Pokemon s Special Attack stat by 1.');
INSERT INTO Items VALUES('Smart Candy L','Medicine','Increases a Pokemon s Special Attack stat.');
INSERT INTO Items VALUES('Smart Candy XL','Medicine','Increases a Pokemon s Special Attack stat.');
INSERT INTO Items VALUES('Smoke Ball','Hold items','An item to be held by a Pokemon. It enables the holder to flee from any wild Pokemon without fail.');
INSERT INTO Items VALUES('Smooth Rock','Hold items','A Pokemon held item that extends the duration of the move Sandstorm used by the holder.');
INSERT INTO Items VALUES('Snorlium Z','Hold items','Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.');
INSERT INTO Items VALUES('Snowball','Hold items','Raises Attack if hit by an Ice-type move.');
INSERT INTO Items VALUES('Soda Pop','Medicine','Restores 50 HP.');
INSERT INTO Items VALUES('Soft Sand','Hold items','Increases the power of Ground-type moves.');
INSERT INTO Items VALUES('Solganium Z','Hold items','Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.');
INSERT INTO Items VALUES('Soothe Bell','Hold items','An item to be held by a Pokemon. It is a bell with a comforting chime that calms the holder and makes it friendly.');
INSERT INTO Items VALUES('Soul Dew','Hold items','Increases the power of Psychic- and Dragon-type moves when held by Latios or Latias. Increases Sp.Atk/Sp.Def prior to Gen 7.');
INSERT INTO Items VALUES('Spell Tag','Hold items','Increases the power of Ghost-type moves.');
INSERT INTO Items VALUES('Spelon Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Splash Plate','Hold items','Increases power of Water-type moves. Changes Arceus  type to Water.');
INSERT INTO Items VALUES('Spooky Plate','Hold items','Increases power of Ghost-type moves. Changes Arceus  type to Ghost.');
INSERT INTO Items VALUES('Sport Ball','Pokeballs','A special Poké Ball for the Bug-Catching Contest.');
INSERT INTO Items VALUES('Sprinklotad','General items','A watering can shaped like a Lotad. It helps promote the healthy growth of any Berries planted in good, soft soil.');
INSERT INTO Items VALUES('Stable Mulch','General items','A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Star Piece','General items','A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.');
INSERT INTO Items VALUES('Stardust','General items','Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.');
INSERT INTO Items VALUES('Starf Berry','Berries','Sharply raises a random stat when HP is low.');
INSERT INTO Items VALUES('Steel Gem','Hold items','Increases the power of a Steel-type move only once.');
INSERT INTO Items VALUES('Steel Memory','Hold items','Changes Silvally and its move Multi-Attack to Steel type.');
INSERT INTO Items VALUES('Steelium Z','Hold items','Allows the use of Corkscrew Crash, the Steel type Z-Move.');
INSERT INTO Items VALUES('Steelixite','Hold items','Enables Steelix to Mega Evolve during battle.');
INSERT INTO Items VALUES('Stick','Hold items','Increases critical-hit ratio when held by Farfetch d.');
INSERT INTO Items VALUES('Sticky Barb','Hold items','A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.');
INSERT INTO Items VALUES('Stone Plate','Hold items','Increases power of Rock-type moves. Changes Arceus  type to Rock.');
INSERT INTO Items VALUES('Strange Souvenir','General items','An ornament depicting a Pokemon that is venerated as a protector in some region far from Kalos.');
INSERT INTO Items VALUES('Stretchy Spring','General items',null);
INSERT INTO Items VALUES('Sun Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Super Lure','General items','Attracts Pokemon in the wild.');
INSERT INTO Items VALUES('Super Potion','Medicine','Restores 60 HP.');
INSERT INTO Items VALUES('Super Repel','General items','An item that prevents weak wild Pokemon from appearing for 200 steps after its use.');
INSERT INTO Items VALUES('Swampertite','Hold items','Enables Swampert to Mega Evolve during battle.');
INSERT INTO Items VALUES('Sweet Heart','Medicine','Very sweet chocolate. It restores the HP of one Pokemon by only 20 points.');
INSERT INTO Items VALUES('Swift Wing','Medicine','Increases Speed EVs by 1.');
INSERT INTO Items VALUES('Tamato Berry','Berries','Increases Friendship but lowers Speed EVs.');
INSERT INTO Items VALUES('Tanga Berry','Berries','Weakens a supereffective Bug-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Tapunium Z','Hold items','Allows the Tapus to upgrade Nature s Madness to a Z-Move, Guardian of Alola.');
INSERT INTO Items VALUES('Terrain Extender','Hold items','An item to be held by a Pokemon. It extends the duration of the terrain caused by the holder s move or Ability.');
INSERT INTO Items VALUES('Thick Club','Hold items','Increases Attack when held by Cubone or Marowak.');
INSERT INTO Items VALUES('Thunder Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Timer Ball','Pokeballs','A somewhat different BALL that becomes progressively better the more turns there are in a battle.');
INSERT INTO Items VALUES('Tiny Mushroom','General items','A small and rare mushroom. It is sought after by collectors.');
INSERT INTO Items VALUES('TM01','Machines','Teaches the move Mega Punch/Dynamic Punch/Focus Punch/Hone Claws/Work Up/Headbutt.');
INSERT INTO Items VALUES('TM02','Machines','Teaches the move Razor Wind/Headbutt/Dragon Claw/Taunt.');
INSERT INTO Items VALUES('TM03','Machines','Teaches the move Swords Dance/Curse/Water Pulse/Psyshock/Helping Hand.');
INSERT INTO Items VALUES('TM04','Machines','Teaches the move Whirlwind/Rollout/Calm Mind/Teleport.');
INSERT INTO Items VALUES('TM05','Machines','Teaches the move Mega Kick/Roar/Rest.');
INSERT INTO Items VALUES('TM06','Machines','Teaches the move Toxic/Light Screen.');
INSERT INTO Items VALUES('TM07','Machines','Teaches the move Horn Drill/Zap Cannon/Hail/Protect.');
INSERT INTO Items VALUES('TM08','Machines','Teaches the move Body Slam/Rock Smash/Bulk Up/Substitute.');
INSERT INTO Items VALUES('TM09','Machines','Teaches the move Take Down/Psych Up/Bullet Seed/Venoshock/Reflect.');
INSERT INTO Items VALUES('TM10','Machines','Teaches the move Double-Edge/Hidden Power/Dig.');
INSERT INTO Items VALUES('TM100','Machines','Teaches the move Confide.');
INSERT INTO Items VALUES('TM11','Machines','Teaches the move BubbleBeam/Sunny Day/Will-O-Wisp.');
INSERT INTO Items VALUES('TM12','Machines','Teaches the move Water Gun/Sweet Scent/Taunt/Facade.');
INSERT INTO Items VALUES('TM13','Machines','Teaches the move Snore/Ice Beam/Brick Break.');
INSERT INTO Items VALUES('TM14','Machines','Teaches the move Blizzard/Fly.');
INSERT INTO Items VALUES('TM15','Machines','Teaches the move Hyper Beam/Seismic Toss.');
INSERT INTO Items VALUES('TM16','Machines','Teaches the move Pay Day/Icy Wind/Light Screen/Thunder Wave.');
INSERT INTO Items VALUES('TM17','Machines','Teaches the move Submission/Protect/Dragon Tail.');
INSERT INTO Items VALUES('TM18','Machines','Teaches the move Counter/Rain Dance/U-turn.');
INSERT INTO Items VALUES('TM19','Machines','Teaches the move Seismic Toss/Giga Drain/Telekinesis/Roost/Iron Tail.');
INSERT INTO Items VALUES('TM20','Machines','Teaches the move Rage/Endure/Safeguard/Dark Pulse.');
INSERT INTO Items VALUES('TM21','Machines','Teaches the move Mega Drain/Frustration/Foul Play.');
INSERT INTO Items VALUES('TM22','Machines','Teaches the move SolarBeam/Rock Slide.');
INSERT INTO Items VALUES('TM23','Machines','Teaches the move Dragon Rage/Iron Tail/Smack Down/Thunder Punch.');
INSERT INTO Items VALUES('TM24','Machines','Teaches the move Thunderbolt/DragonBreath/X-Scissor.');
INSERT INTO Items VALUES('TM25','Machines','Teaches the move Thunder/Waterfall.');
INSERT INTO Items VALUES('TM26','Machines','Teaches the move Earthquake/Poison Jab.');
INSERT INTO Items VALUES('TM27','Machines','Teaches the move Fissure/Return/Toxic.');
INSERT INTO Items VALUES('TM28','Machines','Teaches the move Dig/Leech Life/Tri Attack.');
INSERT INTO Items VALUES('TM29','Machines','Teaches the move Psychic/Scald.');
INSERT INTO Items VALUES('TM30','Machines','Teaches the move Teleport/Shadow Ball/Bulk Up.');
INSERT INTO Items VALUES('TM31','Machines','Teaches the move Mimic/Mud-Slap/Brick Break/Fire Punch.');
INSERT INTO Items VALUES('TM32','Machines','Teaches the move Double Team/Dazzling Gleam.');
INSERT INTO Items VALUES('TM33','Machines','Teaches the move Ice Punch/Reflect/Calm Mind.');
INSERT INTO Items VALUES('TM34','Machines','Teaches the move Bide/Swagger/Shock Wave/Sludge Wave/Dragon Pulse.');
INSERT INTO Items VALUES('TM35','Machines','Teaches the move Metronome/Sleep Talk/Flamethrower/Ice Punch.');
INSERT INTO Items VALUES('TM36','Machines','Teaches the move Selfdestruct/Sludge Bomb/Thunderbolt.');
INSERT INTO Items VALUES('TM37','Machines','Teaches the move Egg Bomb/Sandstorm/Flamethrower.');
INSERT INTO Items VALUES('TM38','Machines','Teaches the move Fire Blast/Thunder.');
INSERT INTO Items VALUES('TM39','Machines','Teaches the move Swift/Rock Tomb/Outrage.');
INSERT INTO Items VALUES('TM40','Machines','Teaches the move Skull Bash/Defense Curl/Aerial Ace/Psychic.');
INSERT INTO Items VALUES('TM41','Machines','Teaches the move Softboiled/ThunderPunch/Torment/Earthquake.');
INSERT INTO Items VALUES('TM42','Machines','Teaches the move Dream Eater/Facade/Self-Destruct.');
INSERT INTO Items VALUES('TM43','Machines','Teaches the move Sky Attack/Detect/Secret Power/Flame Charge/Shadow Ball.');
INSERT INTO Items VALUES('TM44','Machines','Teaches the move Rest/Play Rough.');
INSERT INTO Items VALUES('TM45','Machines','Teaches the move Thunder Wave/Attract/Solar Beam.');
INSERT INTO Items VALUES('TM46','Machines','Teaches the move Psywave/Thief/Fire Blast.');
INSERT INTO Items VALUES('TM47','Machines','Teaches the move Explosion/Steel Wing/Low Sweep/Surf.');
INSERT INTO Items VALUES('TM48','Machines','Teaches the move Rock Slide/Fire Punch/Skill Swap/Round/Hyper Beam.');
INSERT INTO Items VALUES('TM49','Machines','Teaches the move Tri Attack/Fury Cutter/Snatch/Echoed Voice/Superpower.');
INSERT INTO Items VALUES('TM50','Machines','Teaches the move Substitute/Nightmare/Overheat/Roost.');
INSERT INTO Items VALUES('TM51','Machines','Teaches the move Roost/Ally Switch/Steel Wing/Blizzard.');
INSERT INTO Items VALUES('TM52','Machines','Teaches the move Focus Blast/Sludge Bomb.');
INSERT INTO Items VALUES('TM53','Machines','Teaches the move Energy Ball/Mega Drain.');
INSERT INTO Items VALUES('TM54','Machines','Teaches the move False Swipe/Flash Cannon.');
INSERT INTO Items VALUES('TM55','Machines','Teaches the move Brine/Scald/Ice Beam.');
INSERT INTO Items VALUES('TM56','Machines','Teaches the move Fling/Stealth Rock.');
INSERT INTO Items VALUES('TM57','Machines','Teaches the move Charge Beam/Pay Day.');
INSERT INTO Items VALUES('TM58','Machines','Teaches the move Endure/Sky Drop/Drill Run.');
INSERT INTO Items VALUES('TM59','Machines','Teaches the move Dragon Pulse/Incinerate/Brutal Swing/Dream Eater.');
INSERT INTO Items VALUES('TM60','Machines','Teaches the move Drain Punch/Quash/Megahorn.');
INSERT INTO Items VALUES('TM61','Machines','Teaches the move Will-O-Wisp.');
INSERT INTO Items VALUES('TM62','Machines','Teaches the move Silver Wind/Acrobatics.');
INSERT INTO Items VALUES('TM63','Machines','Teaches the move Embargo.');
INSERT INTO Items VALUES('TM64','Machines','Teaches the move Explosion.');
INSERT INTO Items VALUES('TM65','Machines','Teaches the move Shadow Claw.');
INSERT INTO Items VALUES('TM66','Machines','Teaches the move Payback.');
INSERT INTO Items VALUES('TM67','Machines','Teaches the move Recycle/Retaliate/Smart Strike.');
INSERT INTO Items VALUES('TM68','Machines','Teaches the move Giga Impact.');
INSERT INTO Items VALUES('TM69','Machines','Teaches the move Rock Polish.');
INSERT INTO Items VALUES('TM70','Machines','Teaches the move Flash/Aurora Veil.');
INSERT INTO Items VALUES('TM71','Machines','Teaches the move Stone Edge.');
INSERT INTO Items VALUES('TM72','Machines','Teaches the move Avalanche/Volt Switch.');
INSERT INTO Items VALUES('TM73','Machines','Teaches the move Thunder Wave.');
INSERT INTO Items VALUES('TM74','Machines','Teaches the move Gyro Ball.');
INSERT INTO Items VALUES('TM75','Machines','Teaches the move Swords Dance.');
INSERT INTO Items VALUES('TM76','Machines','Teaches the move Stealth Rock/Struggle Bug/Fly.');
INSERT INTO Items VALUES('TM77','Machines','Teaches the move Psych Up.');
INSERT INTO Items VALUES('TM78','Machines','Teaches the move Captivate/Bulldoze.');
INSERT INTO Items VALUES('TM79','Machines','Teaches the move Dark Pulse/Frost Breath.');
INSERT INTO Items VALUES('TM80','Machines','Teaches the move Rock Slide.');
INSERT INTO Items VALUES('TM81','Machines','Teaches the move X-Scissor.');
INSERT INTO Items VALUES('TM82','Machines','Teaches the move Sleep Talk/Dragon Tail.');
INSERT INTO Items VALUES('TM83','Machines','Teaches the move Natural Gift/Work Up/Infestation.');
INSERT INTO Items VALUES('TM84','Machines','Teaches the move Poison Jab.');
INSERT INTO Items VALUES('TM85','Machines','Teaches the move Dream Eater.');
INSERT INTO Items VALUES('TM86','Machines','Teaches the move Grass Knot.');
INSERT INTO Items VALUES('TM87','Machines','Teaches the move Swagger.');
INSERT INTO Items VALUES('TM88','Machines','Teaches the move Pluck/Sleep Talk.');
INSERT INTO Items VALUES('TM89','Machines','Teaches the move U-turn.');
INSERT INTO Items VALUES('TM90','Machines','Teaches the move Substitute.');
INSERT INTO Items VALUES('TM91','Machines','Teaches the move Flash Cannon.');
INSERT INTO Items VALUES('TM92','Machines','Teaches the move Trick Room.');
INSERT INTO Items VALUES('TM93','Machines','Teaches the move Wild Charge.');
INSERT INTO Items VALUES('TM94','Machines','Teaches the move Rock Smash/Surf.');
INSERT INTO Items VALUES('TM95','Machines','Teaches the move Snarl.');
INSERT INTO Items VALUES('TM96','Machines','Teaches the move Nature Power.');
INSERT INTO Items VALUES('TM97','Machines','Teaches the move Dark Pulse.');
INSERT INTO Items VALUES('TM98','Machines','Teaches the move Power-Up Punch/Waterfall.');
INSERT INTO Items VALUES('TM99','Machines','Teaches the move Dazzling Gleam.');
INSERT INTO Items VALUES('TMV Pass','General items','A commuter pass that allows the holder to ride the TMV between Lumiose City and Kiloude City at any time.');
INSERT INTO Items VALUES('Tough Candy','Medicine','Increases a Pokemon s Defense stat by 1.');
INSERT INTO Items VALUES('Tough Candy L','Medicine','Increases a Pokemon s Defense stat.');
INSERT INTO Items VALUES('Tough Candy XL','Medicine','Increases a Pokemon s Defense stat.');
INSERT INTO Items VALUES('Toxic Orb','Hold items','An item to be held by a Pokemon. It is a bizarre orb that badly poisons the holder in battle.');
INSERT INTO Items VALUES('Toxic Plate','Hold items','Increases power of Poison-type moves. Changes Arceus  type to Poison.');
INSERT INTO Items VALUES('Tropical Shell','General items',null);
INSERT INTO Items VALUES('Twisted Spoon','Hold items','Increases the power of Psychic-type moves.');
INSERT INTO Items VALUES('Tyranitarite','Hold items','Enables Tyranitar to Mega Evolve during battle.');
INSERT INTO Items VALUES('Ultra Ball','Pokeballs','An ultra-performance Ball that provides a higher Pokemon catch rate than a Great Ball.');
INSERT INTO Items VALUES('Ultranecrozium Z','Hold items','Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.');
INSERT INTO Items VALUES('Up-Grade','General items','Evolves Porygon when traded holding the item.');
INSERT INTO Items VALUES('Venusaurite','Hold items','Enables Venusaur to Mega Evolve during battle.');
INSERT INTO Items VALUES('Wacan Berry','Berries','Weakens a supereffective Electric-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Water Gem','Hold items','Increases the power of a Water-type move only once.');
INSERT INTO Items VALUES('Water Memory','Hold items','Changes Silvally and its move Multi-Attack to Water type.');
INSERT INTO Items VALUES('Water Stone','General items','Evolves certain species of Pokemon.');
INSERT INTO Items VALUES('Waterium Z','Hold items','Allows the use of Hydro Vortex, the Water type Z-Move.');
INSERT INTO Items VALUES('Watmel Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Wave Incense','Hold items','Increases the power of Water-type moves. Breeding Mantine produces Mantyke when held.');
INSERT INTO Items VALUES('Weakness Policy','Hold items','Sharply raises Attack and Special Attack if hit by a super-effective move.');
INSERT INTO Items VALUES('Wepear Berry','Berries','A Berry which is very rare in the Unova region. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Whipped Dream','General items','Evolves Swirlix when traded holding the item.');
INSERT INTO Items VALUES('White Apricorn','General items','A white Apricorn. It doesn t smell like anything.');
INSERT INTO Items VALUES('White Flute','General items','A toy flute made from white glass. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('White Herb','Hold items','An item to be held by a Pokemon. It restores any lowered stat in battle. It can be used only once.');
INSERT INTO Items VALUES('Wide Lens','Hold items','Increases the accuracy of moves.');
INSERT INTO Items VALUES('Wiki Berry','Berries','Restores HP if it s low, but may cause confusion.');
INSERT INTO Items VALUES('Wise Glasses','Hold items','Increases the power of Special-category moves.');
INSERT INTO Items VALUES('X Accuracy','Battle items','Raises Accuracy of a Pokemon in battle.');
INSERT INTO Items VALUES('X Accuracy 2','Battle items','Sharply raises Accuracy of a Pokemon in battle.');
INSERT INTO Items VALUES('X Accuracy 3','Battle items','Drastically raises Accuracy of a Pokemon in battle.');
INSERT INTO Items VALUES('X Accuracy 6','Battle items','Immensely raises Accuracy of a Pokemon in battle.');
INSERT INTO Items VALUES('X Attack','Battle items','Raises Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Attack 2','Battle items','Sharply raises Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Attack 3','Battle items','Drastically raises Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Attack 6','Battle items','Immensely raises Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Defense','Battle items','Raises Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Defense 2','Battle items','Sharply raises Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Defense 3','Battle items','Drastically raises Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Defense 6','Battle items','Immensely raises Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Atk','Battle items','Raises Special Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Atk 2','Battle items','Sharply raises Special Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Atk 3','Battle items','Drastically raises Special Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Atk 6','Battle items','Immensely raises Special Attack of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Def','Battle items','Raises Special Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Def 2','Battle items','Sharply raises Special Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Def 3','Battle items','Drastically raises Special Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Sp. Def 6','Battle items','Immensely raises Special Defense of a Pokemon in battle.');
INSERT INTO Items VALUES('X Speed','Battle items','Raises Speed of a Pokemon in battle.');
INSERT INTO Items VALUES('X Speed 2','Battle items','Sharply raises Speed of a Pokemon in battle.');
INSERT INTO Items VALUES('X Speed 3','Battle items','Drastically raises Speed of a Pokemon in battle.');
INSERT INTO Items VALUES('X Speed 6','Battle items','Immensely raises Speed of a Pokemon in battle.');
INSERT INTO Items VALUES('Yache Berry','Berries','Weakens a supereffective Ice-type attack against the holding Pokemon.');
INSERT INTO Items VALUES('Yellow Apricorn','General items','A yellow Apricorn. It has an invigorating scent.');
INSERT INTO Items VALUES('Yellow Flute','General items','A toy flute made from yellow glass. A maniac will buy it for a high price.');
INSERT INTO Items VALUES('Yellow Nectar','Hold items','A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokemon.');
INSERT INTO Items VALUES('Yellow Scarf','General items','Raises holder s Tough aspect in a Contest.');
INSERT INTO Items VALUES('Yellow Shard','General items','A small yellow shard. It appears to be from some sort of implement made long ago.');
INSERT INTO Items VALUES('Zap Plate','Hold items','Increases power of Electric-type moves. Changes Arceus  type to Electric.');
INSERT INTO Items VALUES('Zinc','Medicine','Increases Special Defense EVs by 10.');
INSERT INTO Items VALUES('Zoom Lens','Hold items','Raises a move s accuracy if the holder moves after its target.');
