\c postgres
DROP DATABASE IF EXISTS PokeDabe;
CREATE DATABASE PokeDabe;
\c pokedabe

CREATE TABLE 	Type
 (	Name VARCHAR(30) NOT NULL, 
	Descrpition VARCHAR(530) NOT NULL,
	PRIMARY KEY (Name)
);

CREATE TABLE 	Region
 (	Name VARCHAR(30) NOT NULL,
	Game VARCHAR(30) NOT NULL, 
	Map VARCHAR(200) NOT NULL,
	PRIMARY KEY (Name)
);

CREATE TABLE 	Pokemon
 (	ID_Number INT NOT NULL UNIQUE,
	 Name VARCHAR(30) NOT NULL , 
	Weight DECIMAL(5,2) NOT NULL , 
	Height DECIMAL(6,2) NOT NULL,
	Type1 VARCHAR(30) NOT NULL,
	Type2 VARCHAR(30),
	Description VARCHAR(150),
	Abilities VARCHAR(75),
	PRIMARY KEY (Name),
	FOREIGN KEY (Type1) REFERENCES Type(Name) ON DELETE CASCADE,
	FOREIGN KEY (Type2) REFERENCES Type(Name) ON DELETE CASCADE
);

CREATE TABLE 	Base_Stats
 (	Name VARCHAR(30)  NOT NULL,
	HP INT NOT NULL, 
	Attacks INT NOT NULL,
	Defense INT NOT NULL,
	Speed INT NOT NULL,
	FOREIGN KEY (Name) REFERENCES Pokemon(Name)  ON DELETE CASCADE
);
	
CREATE TABLE 	Type_Strength
 (	Name VARCHAR(30) NOT NULL, 
	Dominant_Over VARCHAR(30),
	FOREIGN KEY (Name) REFERENCES Type(Name),
	FOREIGN KEY (Dominant_Over) REFERENCES Type(Name)  ON DELETE CASCADE
);

CREATE TABLE 	Type_Weakness
 (	Name VARCHAR(30) NOT NULL, 
	Weak_Against VARCHAR(30) NOT NULL,
	FOREIGN KEY (Name) REFERENCES Type(Name),
	FOREIGN KEY (Weak_Against) REFERENCES Type(Name)  ON DELETE CASCADE
);

CREATE TABLE 	Attacks
(   Name VARCHAR(30)  NOT NULL,
	PP INT ,
	Accuracy INT ,
	Power INT , 
	Effect VARCHAR(200) ,
	Type VARCHAR(30),
	PRIMARY KEY (Name),
	FOREIGN KEY (Type) REFERENCES Type(Name)  ON DELETE CASCADE
);

CREATE TABLE 	Items
 (	Name CHAR(30) NOT NULL,
	Category VARCHAR(20) , 
	Effect VARCHAR(200) ,
	PRIMARY KEY (Name)
);

CREATE TABLE 	Town
 (	Name VARCHAR(30) NOT NULL,
	Region VARCHAR(30) NOT NULL, 
	Description VARCHAR(40) NOT NULL,
	PRIMARY KEY(Name),
	FOREIGN KEY (Region) REFERENCES Region(Name)  ON DELETE CASCADE	
);

CREATE TABLE 	Trainer
 (	Trainer_ID INT NOT NULL,
 	Name VARCHAR(30) NOT NULL,
	Lives_In VARCHAR(30) NOT NULL, 
	Level INT NOT NULL,
	PRIMARY KEY(Trainer_ID),
	FOREIGN KEY (Lives_In) REFERENCES Town(Name)  ON DELETE CASCADE	
);

CREATE TABLE 	Pokemon_GYM
 (	Badge_Name VARCHAR(30) NOT NULL,
	Gym_Leader INT NOT NULL,
	Region VARCHAR(10) NOT NULL,
	Type VARCHAR(30) NOT NULL,
	PRIMARY KEY (Badge_Name),
	FOREIGN KEY (Gym_Leader) REFERENCES Trainer(Trainer_ID)  ON DELETE CASCADE,
	FOREIGN KEY (Type) REFERENCES Type(Name)  ON DELETE CASCADE			
);

CREATE TABLE 	Pokemon_Evolution
 (	Name_From VARCHAR(30) NOT NULL,
	Name_To VARCHAR(30) NOT NULL, 
	Factor VARCHAR(70) NOT NULL,
	FOREIGN KEY (Name_From) REFERENCES Pokemon(Name)  ON DELETE CASCADE,
	FOREIGN KEY (Name_To) REFERENCES Pokemon(Name)	 ON DELETE CASCADE
);

CREATE TABLE 	Routes
 (	Name INT NOT NULL,
 	Name_From VARCHAR(30) NOT NULL,
	Name_To VARCHAR(30), 
	Map VARCHAR(200) NOT NULL,
	PRIMARY KEY(Name)	
);

CREATE TABLE 	Pokemon_Trainer_Owns
 (	Trainer_ID INT NOT NULL,
	Pokemon_Name VARCHAR(30) NOT NULL, 
	Count INT NOT NULL,
	Level INT NOT NULL,
	FOREIGN KEY (Trainer_ID) REFERENCES Trainer(Trainer_ID)  ON DELETE CASCADE,
	FOREIGN KEY (Pokemon_Name) REFERENCES Pokemon(Name)	 ON DELETE CASCADE
);

CREATE TABLE 	Trainer_Items
 (	Item_Name VARCHAR(30) NOT NULL,
	Trainer_ID INT NOT NULL, 
	Count VARCHAR(50) NOT NULL,
	FOREIGN KEY (Trainer_ID) REFERENCES Trainer(Trainer_ID) ON DELETE CASCADE,
	FOREIGN KEY (Item_Name) REFERENCES Items(Name)  ON DELETE CASCADE
);


CREATE TABLE 	Attacks_Learnt
 (	Pokemon_Name VARCHAR(30) NOT NULL,
	Attack_Name VARCHAR(30) NOT NULL, 
	Level INT NOT NULL,
	FOREIGN KEY (Pokemon_Name) REFERENCES Pokemon(Name) ON DELETE CASCADE,
	FOREIGN KEY (Attack_Name) REFERENCES Attacks(Name) ON DELETE CASCADE	
);

CREATE TABLE 	Pokemon_Found_In_Town
 (	Pokemon_Name VARCHAR(30) NOT NULL,
	Town_Name VARCHAR(30) NOT NULL, 
	FOREIGN KEY (Pokemon_Name) REFERENCES Pokemon(Name) ON DELETE CASCADE,
	FOREIGN KEY (Town_Name) REFERENCES Town(Name) ON DELETE CASCADE	
);

CREATE TABLE 	Pokemon_Belongs_In_Route
 (	Pokemon_Name VARCHAR(30) NOT NULL,
	Route INT NOT NULL, 
	FOREIGN KEY (Pokemon_Name) REFERENCES Pokemon(Name) ON DELETE CASCADE,
	FOREIGN KEY (Route) REFERENCES Routes(Name) ON DELETE CASCADE	
);